kopia/kopia

internal/logfile/logfile.go, main.go, site/cli2md/cli2md.go
=> site: included logging-related flags, cleanup

cli/command_repository_connect_from_config.go, cli/command_repository_create.go, cli/storage_filesystem.go, cli/storage_gcs.go, cli/storage_providers.go, cli/storage_s3.go, cli/storage_webdav.go
- create filesystem directory if it does not exists
- removed dangerous --overwrite option
- changed default splitter to a non-deprecated one
=> initialization improvements

repo/block/block_formatter.go, repo/block/block_formatter_test.go, repo/block/block_formatting_options.go, repo/block/block_index_recovery.go, repo/block/block_manager.go
This allows authenticated encryption, custom IVs and checksums.
Implemented SALSA20-HMAC and XSALSA20-HMAC which append HMAC-SHA256
checksum to the ciphertext.
=> Added support for encryption with padding.

repo/blob/filesystem/filesystem_storage.go, repo/blob/sharded/sharded.go, repo/blob/webdav/webdav_storage.go
(filesystem, webdav and upcoming sftp) into shared package
=> refactored common bits of blob providers that use sharding

repo/blob/sftp/sftp_storage_test.go
Uses environment variables from the CI server, to connect to a test
sftp server
=> Add e2e tests for sftp storage provider

cli/app.go, cli/command_repository_connect.go, cli/command_repository_create.go, cli/command_repository_status.go, cli/command_snapshot_create.go, cli/command_snapshot_estimate.go, cli/command_snapshot_migrate.go, cli/config.go, cli/password.go
also - error handling improvements in the CLI
=> cli: resolve symlinks for snapshot roots

cli/app.go, cli/profile.go, cli/profile_disabled.go, go.mod, go.sum, main.go, snapshot/snapshotfs/upload.go
Usage `go install -tags profiling`
=> cli: added profile flags, built only with 'profiling' tag

snapshot/snapshotfs/upload.go
Thanks to @ntolia for debugging.
Fixes #97
=> upload: fixed time comparison which was sometimes causing re-hashing of contents

site/content/docs/Compatibility/_index.md
Fixes #108
Preview link: https://deploy-preview-118--kopia.netlify.com/docs/compatibility/
=> site: added version compatibility page

site/content/docs/Encryption/_index.md
Notes about the encryption of the format blob.
=> Documentation about the encryption of the format blob

.gitattributes, cli/profile.go, go.mod
Also, allow specifying the memory sampling rate for the memory profiler
=> Allow multiple simultaneous profilers

main.go, repo/blob/filesystem/filesystem_storage.go, repo/blob/progress.go, repo/content/context.go, snapshot/snapshotfs/dir_reader.go
=> Trivial: prefer const where possible

internal/mockfs/mockfs.go, snapshot/stats_test.go
Also, set directory mode and default permissions in `mockfs.NewDirectory`
=> Test for snapshot.Stats

Makefile, htmlui/env.sh, htmlui/package-lock.json, htmlui/package.json, htmlui/src/App.js, htmlui/src/DirectoryItems.js, htmlui/src/DirectoryObject.js, htmlui/src/PoliciesTable.js, htmlui/src/SnapshotsTable.js, htmlui/src/SourcesTable.js, htmlui/src/uiutil.js, internal/server/api_object_get.go, internal/server/server.go
To try:
```
make install && kopia server --ui
```
Navigate to http://localhost:51515/
=> Added UI to browse directories and download files in `kopia server --ui`

cli/command_server_start.go, internal/server/server.go
This fixes the Reload behavior in the browser.
=> server: handle known UI routes specially by serving root index file

htmlui/src/SnapshotsTable.js, htmlui/src/SourcesTable.js, htmlui/src/Table.js, htmlui/src/uiutil.js
=> htmlui: addressed feedback from PR #152

fs/entry.go, fs/entry_test.go
=> fs: added functions Update() and Remove() on fs.Entries which return a copy of entries with specified entry updated or removed

repo/object/object_manager_test.go, repo/object/object_writer.go
This effectively defeated the purpose of compression, caused high memory usage and other kinds of bad behavior.
Refactored the code to prevent this issue by resetting the buffer at the caller not callee.
Fixed inadequate e2e test to catch the issue mentioned in #166, verified it fails against master and passes with this change.
Thanks @flibustenet for the report, note to self - we need test on larger pieces of data, even if that makes the test run slower.
=> object: fixed compression bug where we were not clearing the buffer

cli/storage_s3.go, repo/blob/s3/s3_options.go, repo/blob/s3/s3_storage.go
=> s3: added optional --region parameter

cli/command_blob_delete.go
Fix probable copy paste error on "blob delete" subcommand from
the "blob show" description.
=> [Trivial] Fix command description for blob delete

site/content/_index.html
Until we have a CONTRIBUTING.md, this will do.
=> Fix contrib link

site/config.toml, site/content/_index.html
- Make sure Slack is front-and-center for users too (community page)
- Tweak homepage
=> Website tweaks

repo/blob/sftp/sftp_storage_test.go
=> disable failing sftp test on Windows, to be investigated

README.md, cli/app.go, cli/cli_progress.go, cli/command_snapshot_create.go, cli/command_snapshot_migrate.go, cli/storage_filesystem.go, internal/server/source_manager.go, repo/blob/filesystem/filesystem_storage.go, repo/content/content_cache.go, repo/content/content_manager.go, repo/content/content_manager_lock_free.go, snapshot/snapshotfs/upload.go, snapshot/snapshotfs/upload_progress.go, tests/end_to_end_test/index_optimize_test.go, tests/end_to_end_test/snapshot_fail_test.go
See https://asciinema.org/a/J2QUzQg4zsr9oSqIVlBYgZukC
=> revamped progress output and cleaned up logging

repo/blob/s3/s3_storage_test.go
It is observed that travis CI fails sometimes due
to access key validation issue in TestS3StorageWithSessionToken.
Assuming this issue is due to eventual consistency,
we have added retries while creating S3 Storage obj
Signed-off-by: Prasad Ghangal <prasad.ghangal@gmail.com>
Fixes: #235
=> Add retries when creating S3 Storage obj in test

.travis.yml, Makefile, app/Makefile, app/package.json, htmlui/Makefile, site/Makefile, tools/tools.mk
with only minimal deps (make/curl/unzip)
This allows CLI to be fully built on Windows.
=> Makefile: refactored tools to be installable on Windows

cli/command_policy_show.go, cli/command_repository_create.go, snapshot/policy/policy_tree.go, snapshot/policy/retention_policy.go
Also set some sensible defaults on global policy.
=> cli: removed flags for configuring global policy on repository creation

go.mod, go.sum, internal/blobtesting/asserts.go, internal/blobtesting/concurrent.go, repo/blob/filesystem/filesystem_storage.go, repo/blob/filesystem/filesystem_storage_test.go
Wrote a test first which failed 100% on Windows. After adding retries it passed 20 times in a row, execution time is ~10s.
=> blob: added retries to Filesystem provider, fixes #249

.gitignore, Makefile, htmlui/Makefile, htmlui/env.sh, htmlui/package-lock.json, htmlui/package.json, htmlui/src/App.test.js, htmlui/src/DirectoryObject.js, htmlui/src/RepoStatus.js, htmlui/src/SetupRepository.js, htmlui/src/SetupSFTP.js, htmlui/src/forms.js, htmlui/src/tests/SetupFilesystem.test.js, htmlui/src/tests/SetupGCS.test.js, htmlui/src/tests/SetupRepository.test.js, htmlui/src/tests/SetupS3.test.js, htmlui/src/tests/SetupSFTP.test.js, htmlui/src/tests/SetupToken.test.js, htmlui/src/tests/SetupWebDAV.test.js, htmlui/src/tests/api_mocks.js, htmlui/src/tests/testutils.js
Covered are:
- connect and create flow
- parameter pages for all providers
- connect using token
=> Added unit tests for HTML UI to make it a bit harder to regress.

app/package-lock.json, app/package.json, app/public/electron.js, htmlui/src/PoliciesTable.js, htmlui/src/RepoStatus.js
- disabled MacOS dock icon
- cleaned up MacOS menu bar
- added retry when opening main window, which is unavailable shortly after starting up server
- open main window on first run
- retry checking for updates every 24h
- fixed bug preventing Repository tab from finishing loading
- updated to latest package versions
=> Misc Kopia UI changes

app/Makefile, app/public/electron.js, htmlui/package-lock.json, htmlui/package.json, htmlui/src/App.css, htmlui/src/App.js, htmlui/src/DirectoryObject.js, htmlui/src/SourcesTable.js, htmlui/src/Table.js, htmlui/src/forms.js, htmlui/src/preload.js, htmlui/src/uiutil.js, internal/server/source_manager.go, snapshot/snapshotfs/upload_progress.go
- added ability to make new snapshots from the UI
- added directory picker
- hide/show macOS dock icon automatically
- fixed copy/paste on Mac (apparently if you don't have 'Edit' menu
in your app, copy/paste and many other shortcut keys simply don't
work)
- added smart time formatting ("X minutes ago", etc.) in lists
using 'moment' library
- added progress information to snapshots
=> htmlui: approaching usability by mere mortals

htmlui/src/App.js, htmlui/src/PoliciesTable.js, htmlui/src/RepoStatus.js, htmlui/src/SnapshotsTable.js, htmlui/src/SourcesTable.js, htmlui/src/forms.js, htmlui/src/uiutil.js
- better initial configuration flow
- fixed few fields that were mistakenly marked as required
=> ui: few more tweaks

Makefile
which should avoid dirty git state
=> Makefile: refactored travis-release to run goreleaser first

repo/blob/s3/s3_storage_test.go
- Add a way to execute S3 storage test on AWS
- Create kopia bucket and user with unique ID on minio
- Create AWS bucket before running tests
=> Add a way to execute S3 storage test on AWS

Makefile, cli/storage_sftp.go, htmlui/src/SetupRepository.js, htmlui/src/SetupSFTP.js, htmlui/src/forms.js, htmlui/src/tests/SetupSFTP.test.js, repo/blob/sftp/sftp_options.go, repo/blob/sftp/sftp_storage.go, repo/blob/sftp/sftp_storage_test.go
- did not work on windows due to use of filepath which uses backslash
instead of slash
- added support for embedding SFTP key
- fixed UI controls
- misc fixes for KopiaUI
- added progress reporting
=> sftp: Fixed issues in SFTP provider, Fixes #216

tests/end_to_end_test/snapshot_fail_test.go
Make each test case combination a sub-test, and running independently it in parallel. This gives a 3-4x speedup vs master in local testing.
=> Parallelizing snapshot fail test to decrease test time

cli/command_repository_connect.go, cli/command_repository_disconnect.go, cli/config.go, cli/update_check.go, go.mod, go.sum, tests/end_to_end_test/auto_update_test.go, tests/testenv/cli_test_env.go
User experience:
connection:
https://asciinema.org/a/e4t8a4jLLr7RLsCfpXCKJ8BWW
notification:
https://asciinema.org/a/RJiCLpoUw6KFyLuNUwnGpbpxT
=> cli: implemented update check, fixes #119

app/Makefile, app/public/electron.js, app/public/index.html, app/public/server.js, app/src/App.css, app/src/App.js, app/src/ServerConfig.js, app/src/ServerStatus.js, htmlui/public/index.html, htmlui/src/App.css, tools/tools.mk
- launch server on a randomized port in KopiaUI
- added support for connecting to remote server
- embedded version info in the app and htmlui
=> kopia-ui: misc

Makefile
=> Layering test

Makefile
=> Makefile: fixed layering test

cli/app.go, cli/command_server_start.go, cli/config.go, go.mod, go.sum, repo/content/content_cache.go, repo/content/content_cache_metrics.go, repo/content/content_manager.go, repo/content/content_manager_metrics.go
(the metrics exported are just the beginning, this is to discuss and establish the right pattern)
=> Added OpenCensus

snapshot/snapshotfs/upload.go, snapshot/snapshotfs/upload_test.go, snapshot/stats.go
This is first in series of refactorings to dramatically reduce memory usage of large uploads.
Improves #93
=> Improved upload performance and memory usage

site/config.toml, site/content/docs/Privacy Policy/_index.md, site/layouts/partials/hooks/head-end.html
=> Privacy policy

cli/cli_progress.go
--no-progress - disables progress completely
--progress-update-interval=T - controls how frequently progress is updated
Fixes #344
=> cli: added flags to control progress output

repo/content/content_cache.go, repo/content/content_formatter_test.go, repo/content/content_manager_test.go
- also fixed couple cases where we were not closing content manager
=> content: wait for cache sweep goroutine to close

repo/blob/s3/s3_storage.go, repo/content/builder.go, repo/content/content_id_to_bytes.go, repo/content/index.go, repo/content/packindex_internal_test.go, snapshot/snapshotfs/upload.go
=> Various commits from 345

app/public/server.js, site/content/docs/Reference/Command-Line/_index.md
=> correct a typo in kopia UI

tools/tools.mk
solve https://github.com/kopia/kopia/issues/375
=> Fix makefile for windows

cli/app.go, cli/cli_progress.go, cli/command_ls.go, cli/command_snapshot_create.go, cli/command_snapshot_list.go, fs/entry.go, htmlui/src/DirectoryItems.js, htmlui/src/SnapshotsTable.js, htmlui/src/SourcesTable.js, htmlui/src/uiutil.js, internal/server/source_manager.go, internal/serverapi/serverapi.go, snapshot/snapshotfs/upload.go, snapshot/snapshotfs/upload_progress.go, snapshot/snapshotfs/upload_test.go
Preview:
CLI: https://asciinema.org/a/fxHhpbVNjZKTSTiGXUun0ng6c
UI: https://youtu.be/fl1sneKbHxA
=> Highlight snapshot errors in the UI and CLI

cli/command_benchmark_crypto.go, internal/repotesting/repotesting.go, repo/encryption/encryption.go, repo/encryption/encryption_test.go, repo/encryption/null_encryptor.go, repo/initialize.go, repo/manifest/manifest_manager_test.go, repo/repository_test.go
=> repo: deprecated NONE algorithm, will not be available for new repositories

cli/storage_sftp.go
=> cli: add missing options for configuring sftp known_hosts

repo/content/content_manager.go, repo/content/content_manager_test.go, snapshot/gc/gc.go, snapshot/gc/stats.go
Undelete deleted and re-referenced content.
This implementation is based on `content.Manager.ContentRewrite()`
=> GC content repair

htmlui/src/SetupSFTP.js, site/content/docs/Getting started/_index.md
to "Getting started" documentation page, "Setting Up Repository" chapter
=> add sftp and webdav as repositories

cli/command_snapshot_create.go
Remove `--hostname` and `--username` flags
=> Remove legacy flags from snapshot create command

go.mod, go.sum, tests/tools/fswalker/fswalker.go, tests/tools/fswalker/fswalker_test.go, tests/tools/fswalker/reporter/reporter.go, tests/tools/fswalker/reporter/reporter_test.go, tests/tools/fswalker/walker/walker.go, tests/tools/fswalker/walker/walker_test.go
Upgrade github.com/google/fswalker to get fixes for Darwin/macOS
#212
google/fswalker#25
=> Build test/tools in Darwin as well

repo/connect.go, repo/open.go
=> repo: moved creating cache directory from connect to first use

repo/blob/b2/b2_storage.go
=> b2: fix GetMetadata() implementation

app/package.json
=> kopia-ui: build deb and rpm packages

BUILD.md
Fix `make` command for `kopia-ui`.
=> Fix BUILD.md

app/public/auto-launch.js, app/public/config.js, app/public/config_window.js, app/public/electron.js, app/public/server.js, app/src/App.js
=> kopia-ui: cleaned up console logging

htmlui/src/SetupS3.js, htmlui/src/forms.js, htmlui/src/tests/SetupS3.test.js, htmlui/src/tests/testutils.js
=> kopia-ui: added option to disable TLS and force HTTP

internal/server/api_policies.go
=> server: automatically flush the repository after setting or deleting a policy

app/public/auto-launch.js
=> kopia-ui: fixed missing 'log' when clicking 'Launch At Startup'

tests/end_to_end_test/restore_fail_test.go
Fix parsing of pack blob ID by using a specific regex instead of a strings.Contains. This prevents the test from misidentifying other blob IDs as pack blobs, such as `kopia.maintenance`.
Fixes #519
=> [Fix #519] Fix pack blob parse in TestRestoreFail

htmlui/src/SourcesTable.js
=> app: Disabled progress percentage display above 100%

app/package-lock.json, app/package.json
=> kopia-ui: roll back electron to v7.1.14 since it's crashing on Ubuntu

tests/robustness/engine/engine.go, tests/robustness/engine/engine_test.go, tests/robustness/robustness_test/main_test.go, tests/robustness/snapmeta/kopia_meta.go, tests/tools/kopiarunner/kopia_snapshotter.go, tests/tools/kopiarunner/kopiarun.go, tests/tools/kopiarunner/kopiarun_test.go
- Apply fix similar to #293 for the robustness kopia runner.
- Add control for runner working directory.
=> [Robustness] Fix for kopia runner and custom working directory

internal/server/api_content.go, internal/server/api_manifest.go, internal/server/api_policies.go, internal/server/api_repo.go, internal/server/api_snapshots.go, internal/server/api_sources.go, internal/server/server.go
=> server: pre-read request body to fix HTTP/2 deadlock

htmlui/src/RepoStatus.js, htmlui/src/SetupKopiaServer.js, htmlui/src/SetupRepository.js, htmlui/src/SourcesTable.js, internal/server/api_repo.go, internal/server/api_sources.go, internal/serverapi/serverapi.go, repo/api_server_repository.go
=> kopia-ui: added ability to connect to kopia server and few other minor tweaks

cli/command_server_tls.go, cli/storage_rclone.go, go.mod, go.sum, htmlui/src/SetupRclone.js, htmlui/src/SetupRepository.js, internal/apiclient/apiclient.go, internal/tlsutil/tlsutil.go, repo/blob/rclone/rclone_options.go, repo/blob/rclone/rclone_storage.go, repo/blob/rclone/rclone_storage_test.go, repo/blob/webdav/webdav_options.go, repo/blob/webdav/webdav_storage.go, site/content/docs/Repositories/_index.md
=> Experimental rclone backend

tests/tools/fio/workload.go, tests/tools/fio/workload_test.go
Followup on recent PR #529, some suggestions and discussion after it was merged:
- Express probability as float in range [0,1]
- Add a unit test for DeleteContentsAtDepth
- Add a comment on writeFilesAtDepth explaining depth vs branchDepth
- Refactor pickRandSubdirPath for easier readability and understanding
Upon some reflection, I decided to refactor pickRandSubdirPath() to gather indexes and pick randomly from them instead of the previous reservoir sampling approach. I think this is easier to understand going forward without extra explanation, doesn't have much additional memory overhead, and reduces the number of rand calls to 1.
=> Address additional suggestions from fio workload PR #529

site/themes/docsy/layouts/partials/page-meta-links.html
=> site: fixed edit link

htmlui/src/RepoStatus.js
=> ui: fixed typo

cli/command_repository_connect_server.go, tests/end_to_end_test/api_server_repository_test.go
=> cli: ignore trailing / in repository server URL

cli/command_repository_sync.go, internal/blobtesting/eventually_consistent.go, internal/blobtesting/faulty.go, internal/blobtesting/map.go, internal/blobtesting/verify.go, repo/blob/azure/azure_storage.go, repo/blob/b2/b2_storage.go, repo/blob/filesystem/filesystem_storage.go, repo/blob/gcs/gcs_storage.go, repo/blob/logging/logging_storage.go, repo/blob/logging/logging_storage_test.go, repo/blob/readonly/readonly_storage.go, repo/blob/s3/s3_storage.go, repo/blob/sftp/sftp_storage.go, repo/blob/sharded/sharded.go, repo/blob/storage.go, repo/blob/webdav/webdav_storage.go, tests/end_to_end_test/repository_sync_test.go
Also added '--times' option to 'repository sync'
=> blob: added SetTime() method which may be optionally implemented by blob.Storage

cli/command_policy_set.go, cli/command_policy_show.go, cli/command_snapshot_estimate.go, fs/ignorefs/ignorefs.go, htmlui/src/PolicyEditor.js, repo/open.go, snapshot/policy/files_policy.go, snapshot/snapshotfs/upload.go, tests/testenv/faketimeserver.go
=> implemented Cache Directory Tagging Specification + CLI + UI

snapshot/snapshotfs/upload.go
=> upload: fixed ForceHashPercentage behavior to be non-deterministic

.golangci.yml, cli/app.go, cli/command_policy.go, cli/command_repository_connect.go, cli/command_repository_set_client.go, cli/command_repository_status.go, cli/command_snapshot_create.go, cli/command_snapshot_estimate.go, cli/command_snapshot_expire.go, cli/command_snapshot_list.go, cli/command_snapshot_migrate.go, cli/command_snapshot_verify.go, fs/localfs/local_fs.go, htmlui/src/RepoStatus.js, internal/scrubber/scrub_sensitive.go, internal/server/api_repo.go, internal/server/api_sources.go, internal/server/source_manager.go, internal/serverapi/serverapi.go, repo/api_server_repository.go, repo/blob/azure/azure_storage.go, repo/blob/rclone/rclone_storage_test.go, repo/connect.go, repo/local_config.go, repo/maintenance/maintenance_run.go, repo/open.go, repo/repository.go, tests/end_to_end_test/repository_set_client_test.go
=> Added support for setting and changing repository client options (description, read-only, hostname, username)

internal/faketime/faketime.go, internal/faketime/faketime_test.go, internal/repotesting/repotesting_test.go, repo/content/index_blob_manager_test.go, snapshot/snapshotfs/upload_test.go
* Allow `faketime.TimeAdvance` to  auto-advance
* Implement `faketime.AutoAdvance` in terms of `TimeAdvance`
* Add concurrent test for `TimeAdvance`
=> Refactor faketime

repo/object/object_manager.go
=> Trivial: loadSeekTable helper

cli/cli_progress.go, fs/entry.go, repo/object/object_manager_test.go, repo/object/object_writer.go, snapshot/snapshotfs/checkpoint_registry.go, snapshot/snapshotfs/checkpoint_registry_test.go, snapshot/snapshotfs/upload.go, snapshot/snapshotfs/upload_progress.go, snapshot/snapshotfs/upload_test.go, snapshot/stats.go
=> Fixed checkpointing to not restart the entire upload process

internal/fusemount/fusefs.go
We don't have automated tests for this but I verified this by
restoring 13GB file over fuse and memory usage never exceeded 400MB.
=> fuse: changed file read implementation from ReadAll() to a Handle to avoid OOMing

snapshot/snapshotfs/upload.go
Fixes: #631
Verified manually on Raspberry PI 4 on 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
=> upload: fixed armhf alignment issue

internal/blobtesting/verify.go, internal/testutil/retriable_t.go, repo/blob/b2/b2_storage.go
=> b2: fixed handling of 'no_such_file' to indicate NOT_FOUND

go.mod, go.sum, repo/blob/webdav/webdav_storage.go
=> Upgrade webdav client dependency to include bugfix for the race condition

internal/faketime/faketime_test.go
TestTimeAdvanceConcurrent was depending on t.Parallel() to be scheduled quickly, which is not guaranteed.
Fixes #654
=> testing: fixed deadlock in faketime_test

cli/command_restore.go, snapshot/restore/restore.go
Demo: https://asciinema.org/a/8RV8SwBVt2CI0HSsklYwO8FhP
=> cli: improved restore progress information

fs/ignorefs/ignorefs_test.go, internal/ignore/ignore.go, internal/ignore/ignore_test.go
- Add test cases for absolute patterns
- Support globs for absolute patterns
See https://github.com/kopia/kopia/issues/492#issuecomment-662842450 for details.
=> Improve ignore logic.

go.sum, tests/robustness/engine/engine.go, tests/robustness/snap/snap.go, tests/robustness/snapmeta/kopia_meta.go, tests/tools/kopiarunner/kopia_snapshotter.go, tests/tools/kopiarunner/kopiarun.go
Adds single client to server robustness tests.
Implemented by @rahulchheda
=> robustness: add support for kopia server storage repo

tools/robustness-job.sh
Helper script to run robustness job
=> robustness: wrapper script to run robustness job tests

internal/mount/mount_webdav.go
More details at https://github.com/kopia/kopia/issues/716
=> Fix hang at unmount when Ctrl-C is pressed

cli/command_benchmark_compression.go
=> crypto -vs- compress

cli/config.go, repo/api_server_repository.go, repo/object/indirect.go, repo/object/object_manager.go, repo/object/object_manager_test.go, repo/object/object_reader.go, repo/open.go, repo/repository.go
- reads are now package-level functions
- object.Manager is now only responsible for writes
=> Cleaned up and refactored object manager

app/package-lock.json, app/package.json, app/public/electron.js
=> Upgrade electron 11.2.1

htmlui/src/App.css, htmlui/src/App.js, htmlui/src/DirectoryObject.js, htmlui/src/PoliciesTable.js, htmlui/src/PolicyEditor.js, htmlui/src/RepoStatus.js, htmlui/src/SnapshotsTable.js, htmlui/src/SourcesTable.js, htmlui/src/TaskDetails.js, htmlui/src/TaskLogs.js, htmlui/src/TasksTable.js, htmlui/src/uiutil.js, internal/server/api_tasks.go, internal/server/server.go, internal/server/source_manager.go, internal/serverapi/serverapi.go, internal/uitask/uitask.go, internal/uitask/uitask_counter.go, internal/uitask/uitask_manager.go, internal/uitask/uitask_test.go, snapshot/snapshotfs/upload.go, snapshot/snapshotfs/upload_progress.go
This allows access to progress, logs and cancelation for long-running
tasks (Snapshots, Maintenance, and in the future Restore, Estimate,
Verify)
https://imgur.com/c2DBB3M
https://imgur.com/7671PVJ
=> Added support for Tasks in the UI

htmlui/src/App.css, htmlui/src/App.js, htmlui/src/BeginRestore.js, htmlui/src/DirectoryObject.js, htmlui/src/TaskDetails.js, internal/server/api_restore.go, internal/server/server.go, internal/serverapi/serverapi.go, snapshot/restore/local_fs_output.go, snapshot/restore/restore.go
See: https://youtu.be/cuG6xMI-3DM
=> Restore UI

go.mod, go.sum, internal/fusemount/fusefs.go, internal/mount/mount_fuse.go
This supports latest MacFUSE (tested on 4.0.5 on Intel Mac).
=> fuse: switched to github.com/hanwen/go-fuse/v2 implementation

internal/server/server_test.go
Addresses https://github.com/kopia/kopia/runs/1915273219?check_suite_focus=true
Verified by testing 100 times.
=> server: test flake fix

internal/blobtesting/map.go, repo/blob/retrying/retrying_storage_test.go, repo/content/content_cache_test.go, repo/content/content_manager_test.go, snapshot/snapshotfs/upload_test.go
The intention is to stabilize code coverage results.
=> Added cases for missing code coverage where we only had randomized tests

tests/robustness/engine/engine_test.go
Instead of a flaky timing check, calculate the amount of data that was actually written to the fio file tree.
=> Fix robustness engine i/o limit test flake

.github/workflows/make.yml, Makefile, tools/tools.mk
This will be embedded in KopiaUI which is built on macOS runner.
=> Makefile: build fat macOS binary (amd64 and arm64)

htmlui/src/DirectoryItems.js, htmlui/src/PolicyEditor.js, htmlui/src/SnapshotsTable.js, htmlui/src/SourcesTable.js, htmlui/src/uiutil.js
=> htmlui: urlencode path components

htmlui/src/BeginRestore.js, htmlui/src/DirectoryObject.js, htmlui/src/PolicyEditor.js, htmlui/src/SnapshotsTable.js, htmlui/src/SourcesTable.js, htmlui/src/TaskLogs.js, htmlui/src/TasksTable.js, htmlui/src/uiutil.js
=> Fixed error flicker - replaced fancy error Popover which flickers with a simple tooltip.

cli/command_repository_connect_server.go, htmlui/src/SetupRepository.js, repo/grpc_repository_client.go
Many users are confused w.r.t. the user that's currently connecting;
=> ui: show the current username@hostname as it is connecting to repository

repo/compression/compressor_test.go
Usage:
$ go test -run NONE -bench=. ./repo/compression/... | tee file.txt
To compare: https://pkg.go.dev/golang.org/x/tools/cmd/benchcmp
=> compression: added benchmark to measure impact of library upgrades

go.mod, go.sum
Bug reported upstream https://github.com/efarrer/iothrottler/issues/4
=> Rollback github.com/efarrer/iothrottler to v0.0.1

.github/workflows/make.yml, .goreleaser.yml, Makefile, app/Makefile, htmlui/Makefile, tools/scoop-kopia.json.template, tools/scoop-publish.sh, tools/tools.mk
post-submit tested in https://github.com/jkowalski/kopia/actions
=> Makefile refactoring + publish scoop package

cli/command_acl_list.go, cli/command_blob_list.go, cli/command_content_list.go, cli/command_index_list.go, cli/command_maintenance_info.go, cli/command_manifest_ls.go, cli/command_policy_ls.go, cli/command_policy_show.go, cli/command_snapshot_create.go, cli/command_snapshot_list.go, cli/command_user_list.go, cli/json_output.go, fs/entry.go, snapshot/manifest.go, snapshot/policy/policy.go, tests/end_to_end_test/api_server_repository_test.go, tests/end_to_end_test/policy_test.go, tests/end_to_end_test/snapshot_create_test.go, tests/end_to_end_test/snapshot_gc_test.go
=> cli: added standard --json flags to several commands

cli/storage_filesystem.go, internal/ospath/ospath.go, internal/server/api_estimate.go, internal/server/api_sources.go, tests/end_to_end_test/repository_connect_test.go
=> filesystem: support ~ in repository path, require absolute paths

main.go, tests/end_to_end_test/maintenance_test.go
=> cli: output usage to stdout but errors to stderr

repo/maintenance/maintenance_run.go, repo/maintenance/maintenance_run_test.go, snapshot/snapshotmaintenance/snapshotmaintenance_test.go
This ensures all maintenance tasks run with reasonable frequency.
=> maintenance: fixed possible starvation of full blob deletion by quick maintenance

cli/password.go
=> cli: fixed password prompt on Windows

.goreleaser.yml, internal/mount/mount_fuse.go, internal/mount/mount_posix_webdav_helper.go, internal/mount/mount_unsupported.go, snapshot/restore/local_fs_output_unix.go
=> build: added freebsd build (untested) with FUSE mounting disabled

internal/ospath/ospath_openbsd.go
=> simple version of ospath to get default paths for openbsd systems.

.github/workflows/make.yml
=> ci: do not upload artifacts from self-hosted runners, fixes build race

htmlui/src/PolicyEditor.js
=> ui: open .gitignore help in a new window

htmlui/src/PolicyEditor.js
=> ui: show a spinner when saving/deleting policy

site/content/docs/Features/_index.md
Another option could have been "which provide excellent features for *a* very reasonable price. Either grammar fix works but I personally prefer the plural version included in the PR.
=> Grammar fix.

cli/command_snapshot_create.go, cli/command_snapshot_list.go, cli/command_snapshot_migrate.go, cli/command_snapshot_verify.go, internal/server/api_snapshots.go, snapshot/manager.go, snapshot/manifest.go, snapshot/snapshot_test.go, snapshot/snapshotgc/gc.go, tests/end_to_end_test/snapshot_create_test.go
=> Tagging of kopia snapshots and listing of snapshots by tag

site/content/docs/Advanced/Maintenance/_index.md
Full maintenance is now enabled by default in >=0.8.0
=> Update full maintenance automation explanation

repo/content/builder.go, repo/content/committed_content_index.go, repo/content/committed_content_index_cache_test.go, repo/content/committed_read_manager.go, repo/content/content_index_recovery.go, repo/content/content_manager.go, repo/content/content_manager_indexes.go, repo/content/content_manager_test.go, repo/content/index.go, repo/content/index_encode_util.go, repo/content/index_v1.go, repo/content/index_v2.go, repo/content/info.go, repo/content/merged_test.go, repo/content/packindex_test.go
Only unit tested, not in use by content manager yet.
Related to #745
=> Implemented index v2 builder and parser

.github/workflows/code-coverage.yml, .github/workflows/make.yml, Makefile, cli/command_blob_show_test.go, cli/command_cache_set_test.go, cli/command_cache_sync_test.go, cli/command_content_verify_test.go, cli/command_index_inspect_test.go, cli/command_server_start.go, cli/command_snapshot_estimate.go, cli/command_snapshot_estimate_test.go, htmlui/src/NewSnapshot.js, internal/server/api_estimate.go, internal/serverapi/client_wrappers.go, internal/serverapi/serverapi.go, internal/uitask/uitask.go, snapshot/snapshotfs/estimate.go, snapshot/snapshotfs/upload_scan.go, tests/end_to_end_test/server_start_test.go
Added --max-examples-per-bucket flag to 'kopia snapshot estimate'
Fixes #1054
=> cli: test + misc improvements

cli/storage_sftp.go, cli/storage_sftp_test.go, repo/blob/sftp/sftp_storage.go, repo/blob/sftp/sftp_storage_test.go
=> sftp: ensure key file and known hosts are absolute paths

repo/blob/webdav/webdav_storage.go
=> webdav: disable server-side compression

cli/command_benchmark_crypto.go, cli/command_blob_show.go, repo/content/blob_crypto.go, repo/content/committed_read_manager.go, repo/content/content_formatter_test.go, repo/content/content_index_reader.go, repo/content/content_index_recovery.go, repo/content/content_manager_indexes.go, repo/content/content_manager_lock_free.go, repo/content/index_blob_manager.go, repo/content/index_blob_manager_test.go, repo/content/sessions.go, repo/repository.go
This is purely mechanical refactoring to encapsulate hash and
encryption in a single data structure that also provides utilities
for encrypting and decrypting whole blobs of data.
=> content: introduced content.Crypter

repo/content/committed_content_index.go, repo/content/committed_read_manager.go, repo/content/content_manager.go, repo/content/content_manager_indexes.go, repo/repository.go
Cleaned up and reorganized some very old index loading code.
=> Content manager cleanups

cli/command_content_verify.go, internal/timetrack/estimator.go, repo/content/content_cache_metadata.go
Also improved 'content verify' progress reporting.
=> cli: 'kopia content verify' performance improvements

internal/epoch/complete_set.go, internal/epoch/complete_set_test.go, internal/epoch/epoch_advance.go, internal/epoch/epoch_advance_test.go, internal/epoch/epoch_manager.go, internal/epoch/epoch_manager_test.go, internal/epoch/epoch_utils.go, internal/epoch/epoch_utils_test.go, internal/faketime/faketime.go
This implements the core algorithm described in #1090 - it's not in use yet, but is unit tested and should be handling some difficult corner cases.
=> epoch: added epoch manager + unit tests

site/content/docs/Advanced/Storage Tiers/_index.md, site/content/docs/Repositories/_index.md
Based on Jarek Kowalski's fine advice in the Slack channel.
=> Added documentation with storage tier advice

.github/workflows/code-coverage.yml, .github/workflows/make.yml, .github/workflows/stress-test.yml, Makefile, internal/testutil/tmpdir.go, repo/content/committed_content_index.go, repo/content/committed_read_manager.go, repo/content/content_manager.go, repo/content/content_manager_indexes.go, repo/manifest/committed_manifest_manager.go, tests/repository_stress_test/repomodel/content_set.go, tests/repository_stress_test/repomodel/manifest_set.go, tests/repository_stress_test/repomodel/open_repository_model.go, tests/repository_stress_test/repomodel/repository_data_model.go, tests/repository_stress_test/repomodel/repository_session_model.go, tests/repository_stress_test/repository_stress_test.go, tests/stress_test/stress_test.go, tests/testenv/cli_exe_runner.go, tests/testenv/cli_test_env.go
Also added lock to protect `committedContentIndex`
=> Fixed few subtle threading bugs uncovered by stress test and rewrote the test to be model-based

cli/storage_sftp.go, repo/blob/sftp/sftp_options.go, repo/blob/sftp/sftp_storage.go
=> sftp: added automatic reconnect and connection pooling

cli/command_repository_connect.go, cli/command_repository_set_client.go, cli/command_repository_status.go, repo/local_config.go, repo/open.go, tests/end_to_end_test/repository_set_client_test.go
also added flags to override caching duration and disable completely
=> repo: limit the duration of kopia.repository caching to 15 minutes

cli/storage_rclone.go, repo/blob/rclone/rclone_options.go, repo/blob/rclone/rclone_storage.go
added --rclone-debug flag to enable better logging from rclone
=> rclone: wait for rclone transfers to finish when closing

snapshot/policy/retention_policy.go, snapshot/policy/retention_policy_test.go
=> Fix weekly retention labels not being assigned correctly

cli/command_snapshot_verify.go, internal/parallelwork/parallel_work_queue.go, internal/timetrack/estimator.go
=> cli: Fixed ETA estimation of 'snapshot verify'

Makefile, cli/auto_upgrade.go, cli/command_blob_list.go, cli/command_logs_session.go, cli/command_maintenance_run.go, cli/command_repository_create.go, internal/epoch/epoch_manager.go, internal/epoch/epoch_manager_test.go, internal/epoch/epoch_utils.go, repo/content/committed_content_index.go, repo/content/committed_read_manager.go, repo/content/index_blob_manager_v0.go, repo/content/index_blob_manager_v0_test.go, repo/content/index_blob_manager_v1.go, repo/content/internal_logger.go, repo/maintenance/maintenance_run.go, repo/maintenance/maintenance_run_test.go, tests/end_to_end_test/index_optimize_test.go, tests/end_to_end_test/maintenance_test.go, tests/testenv/cli_test_env.go
=> Maintenance improvements for epoch-based index structures

internal/logfile/logfile.go
otherwise it's hard to correlate logs
=> logging: switched file log timestamps to be UTC by default

.github/workflows/make.yml
Per https://github.com/golang/go/issues/48134#issuecomment-911431265
=> ci: delete golang installation on armhf before installing a new one

app/env.sh, app/package-lock.json, app/package.json, app/public/electron.js, htmlui/Makefile, htmlui/env.sh, htmlui/package-lock.json, htmlui/package.json, tools/node_env.sh
Reacted to minor breaking change in app.
=> ui: upgraded all NPM dependencies for htmlui/ and app/

htmlui/src/BeginRestore.js, htmlui/src/RepoStatus.js, htmlui/src/forms.js, snapshot/restore/restore.go
=> ui: Added UI options for shallow restore

htmlui/src/SnapshotsTable.js, htmlui/src/Table.js
=> ui: fix pagination after toggling 'show identical snapshots'

cli/app.go, go.mod
=> cli: fixed windows color output

htmlui/src/SnapshotsTable.js, htmlui/src/Table.js
Fixes #1149
This is a more universal fix for #1297
=> ui: fixed showing empty result pages

cli/cli_progress.go, cli/command_benchmark_splitters.go, cli/command_index_inspect.go, cli/command_logs_session.go, cli/command_logs_show.go, cli/command_policy_set_actions.go, cli/command_policy_set_files.go, cli/command_repository_set_parameters.go, cli/command_repository_sync.go, cli/command_show.go, cli/command_snapshot_list.go, cli/storage_providers.go, cli/update_check.go, repo/content/content_manager_lock_free.go, repo/content/content_manager_test.go, site/content/_index.html, site/content/docs/Advanced/Actions/_index.md, site/content/docs/Advanced/Architecture/_index.md, site/content/docs/Advanced/Caching/_index.md, site/content/docs/Advanced/Compatibility/_index.md, site/content/docs/Advanced/Logging/_index.md, site/content/docs/Advanced/Maintenance/_index.md, site/content/docs/Advanced/Synchronization/_index.md, site/content/docs/Features/_index.md, site/content/docs/Getting started/_index.md, site/content/docs/Installation/_index.md, site/content/docs/Reference/Command-Line/_index.md, site/content/docs/Repositories/_index.md, site/content/docs/Repository Server/_index.md, site/content/docs/Upgrade/_index.md
Fix some spelling and grammar mistakes.
=> minor spelling and grammar fixes

app/public/electron.js
Also disable annoying behavior where we open all repository windows on double click.
=> kopia-ui: always show default repository at the top of the list

app/Makefile
=> ci: build arm64 linux UI

site/content/docs/Advanced/Actions/_index.md
Please refer to issue #1456 for details.
=> Update Actions example of Windows VSS for self-elevation details. Fix issue #1456.

Makefile, app/Makefile, app/package.json
Also fixed embedded server paths for KopiaUI.
Fixes #1448
=> ci: also build armv7l version of KopiaUI

internal/server/server.go, repo/maintenance/maintenance_schedule.go, repo/maintenance/maintenance_schedule_test.go
Instead of attempting maintenance every 10 minutes we will do a longer
sleep until the predicted next maintenance time (or 4 hours, whichever
is shorter).
Related #1439
=> maintenance: improved scheduling

cli/command_server_start.go, internal/server/server.go
The issue in #1439 was caused by goroutine context being associated
with the HTTP request so it became canceled soon after the request was
over, thus the goroutine to run maintenance never ran.
Fixed by adding ctxutil.Detach()
Also fixed logging by passing top-level contexts to requests
and added --log-server-requests flag to `server start` which enables
request logging.
Fixes #1439
=> server: maintenance in newly-created repo

internal/server/api_estimate.go, internal/server/api_restore.go, internal/server/server.go
This is a slightly better fix for #1439
=> server: ensure all HTTP requests are processed in a detached context

snapshot/snapshotfs/upload.go, snapshot/snapshotfs/upload_test.go
Previously ignored entries were reported from the estimate goroutine and from the main upload goroutine doubling each ignored counter in the UI.
This was raised in https://kopia.discourse.group/t/v0-9-5-excluded-directories-bug/728
=> upload: avoid reporting ignored entries twice

repo/blob/throttling/throttling_storage.go, repo/blob/throttling/throttling_storage_test.go
Throttler is only mocked for unit test purposes and not implemented yet.
Related #1502
=> blob: added throttling wrapper

htmlui/src/SetupS3.js, htmlui/src/tests/SetupS3.test.js, repo/blob/s3/s3_storage_test.go
=> ui: fixed 'Do not validate TLS certificate' caused by typo

internal/server/api_sources_test.go, internal/server/server_test.go, internal/server/util_test.go, internal/serverapi/client_wrappers.go
=> ui: Added test to verify #1057

htmlui/src/App.css, htmlui/src/PolicyEditor.js, htmlui/src/deepstate.js, htmlui/src/forms.js, htmlui/src/tests/deepstate.test.js
See: https://imgur.com/a/ghCYXIz
=> ui: revamped policy editor + various UI cleanups.

htmlui/src/App.css, htmlui/src/DirectoryObject.js, htmlui/src/NewSnapshot.js, htmlui/src/PoliciesTable.js, htmlui/src/PolicyEditorPage.js, htmlui/src/RepoStatus.js, htmlui/src/SnapshotsTable.js, htmlui/src/SourcesTable.js, htmlui/src/uiutil.js, internal/server/api_cli.go, internal/server/api_cli_test.go, internal/server/server.go, internal/serverapi/serverapi.go
=> ui: add CLI equivalent button to most pages

repo/blob/s3/s3_storage.go
=> blob/s3: unconditionally compute and send the MD5 header

internal/scrubber/scrub_sensitive.go, repo/blob/filesystem/filesystem_options.go, repo/blob/filesystem/filesystem_storage.go, repo/blob/filesystem/filesystem_storage_test.go, repo/blob/filesystem/osinterface.go, repo/blob/filesystem/osinterface_mock_test.go, repo/blob/filesystem/osinterface_realos.go
=> test coverage improvements for filesystem provider

.codecov.yml, .golangci.yml, internal/blobtesting/eventually_consistent.go, internal/blobtesting/faulty.go, internal/epoch/epoch_manager_test.go, internal/fault/fault.go, internal/fault/fault_set.go, repo/blob/retrying/retrying_storage_test.go, repo/content/content_cache_test.go, repo/content/content_manager_test.go
=> blobtesting: refactored fault injection into fluent API

go.mod, repo/content/merged.go, repo/content/merged_test.go
=> content: added direct code coverage for mergedIndex

internal/scrubber/scrub_sensitive_test.go
=> scrubber: added unit tests

internal/cache/cache_metrics.go, internal/cache/cache_storage.go, internal/cache/cache_storage_test.go, internal/cache/persistent_lru_cache.go, internal/cache/persistent_lru_cache_test.go, internal/cache/storage_protection.go, internal/cache/storage_protection_test.go, internal/fault/fault_set.go, internal/impossible/impossible.go, internal/impossible/impossible_test.go, repo/content/content_cache_test.go
=> cache: improved test coverage

repo/content/blob_crypto_test.go, repo/content/encrypted_blob_mgr_test.go
=> content: additional tests form encryptedBlobMgr

repo/content/content_cache_data_test.go, repo/content/content_cache_metadata.go, repo/content/content_cache_metadata_test.go
=> content: additional data & metadata cache test cases

repo/blob/b2/b2_storage.go
Turns out B2 library will treat seekable readers in a special way
and will pass those directly to http.NewRequest() for upload. Other
readers are copied to a temporary buffer first.
The #1589 made the reader io.ReadSeeker so it was passed to http.NewRequest(),
which for payloads of length zero uses heuristics to determine if the
Content-Length should be passed as zero or not passed at all.
https://cs.opensource.google/go/go/+/refs/tags/go1.17.5:src/net/http/request.go;l=890;drc=e6dda19888180c5159460486d30c0412e4980748
Since reader was not one of the magic types, Content-Length was not
passed at all, causing B2 server to choke on zero-length files.
=> b2: fixed regression when uploading zero-length blobs introduced by #1589

internal/epoch/epoch_manager.go, internal/epoch/epoch_manager_test.go, repo/maintenance/maintenance_run.go
=> maintenance: moved costly epoch manager cleanup to maintenance

go.mod, go.sum
=> ui: added preliminary dark mode support (the choice is not persistent yet)

app/package-lock.json, app/package.json
=> app: fix macOS autoupdate regression

app/public/electron.js
Temporary workaround for #1630
=> feat(kopiaui): added menu option prompting users to manually upgrade when auto-update fails

tests/tools/kopiarunner/kopia_snapshotter.go
=> fix(testing): fixed robustness tests

site/content/docs/Installation/_index.md
=> docs(site): updated apt installation instructions

internal/clock/now.go, internal/clock/sleep.go, internal/clock/sleep_test.go, internal/server/server.go
=> fix(server): sleep 30m after failed maintenance

cli/command_repository_validate_provider.go, internal/blobtesting/verify.go, internal/providervalidation/providervalidation.go, repo/blob/gcs/gcs_storage.go, repo/blob/gcs/gcs_storage_test.go
do not merge - this tests PR execution againt `test/providers` branch
=> fix(providers): fixed DoNotRecreate and tests for gcs

go.mod, go.sum
=> build(deps): upgrade go-fuse to support /bin/fusermount3

go.mod, go.sum, internal/server/api_snapshots.go, internal/server/api_snapshots_test.go, internal/server/server.go, internal/server/util_test.go, internal/serverapi/serverapi.go
https://user-images.githubusercontent.com/249880/152661589-51aeaab3-4b14-4c87-84ec-519815b34a89.mp4
=> feat(ui): support for snapshot and source deletion

go.mod, go.sum
Implemented in https://github.com/kopia/htmlui/pull/34
Fixes #1735
=> fix(ui): fix parsing of times of day between 00:00 and 00:59

site/content/docs/Installation/_index.md
=> docs(general): update compilation from source for Go 1.17

go.mod, go.sum, repo/blob/azure/azure_storage.go
This helped remove ugly workaround we had in place due to upstream bug.
=> build(deps): update storage/azblob to v0.3.0

go.mod, go.sum
This was implemented in https://github.com/kopia/htmlui/pull/30
Thanks @arminus
=> feat(ui): support for defining snapshot and folder actions

.codecov.yml, .github/workflows/provider-tests.yml, cli/app.go, cli/storage_gdrive.go, internal/retry/retry.go, repo/blob/gdrive/file_id_cache.go, repo/blob/gdrive/gdrive_options.go, repo/blob/gdrive/gdrive_storage.go, repo/blob/gdrive/gdrive_storage_test.go
* feat(provider): Add Google Drive support.
Co-authored-by: xkxx <xkxiang@gmail.com>
Co-authored-by: Jarek Kowalski <jaak@jkowalski.net>
=> feat(providers): add Google Drive support (experimental, implemented in #1731)

cli/command_snapshot_verify.go, internal/workshare/workshare_waitgroup.go, snapshot/snapshotfs/snapshot_tree_walker.go, snapshot/snapshotfs/snapshot_tree_walker_test.go, snapshot/snapshotgc/gc.go
Also cleaned up the API and added unit tests.
=> refactor(snapshots): refactored TreeWalker to use workshare

Makefile, cli/command_policy_set_logging_test.go, cli/command_policy_show.go, cli/command_repository_create.go, cli/show_utils.go
This removed manual alignment of spaces in favor of computing this automatically.
=> feat(cli): improved formatting of 'policy show' outputs

app/public/electron.js
=> feat(kopiaui): provide feedback for 'Check For Updates Now'

app/public/electron.js
=> feat(kopiaui): support both left and right click to open tray menu

go.mod, go.sum
=> feat(ui): display snapshot description in snapshot list

internal/cache/persistent_lru_cache.go, repo/content/committed_read_manager.go, repo/content/content_cache.go, repo/content/content_cache_data.go, repo/content/content_cache_metadata.go, repo/content/content_cache_passthrough.go, repo/content/content_cache_test.go, repo/content/content_manager_lock_free.go, repo/content/content_manager_test.go, repo/content/encrypted_blob_mgr.go, repo/content/encrypted_blob_mgr_test.go, repo/content/index_blob_manager_v0_test.go
Also cleaned up internal content cache APIs.
=> refactor(repository): moved index blob cache to separate directory

cli/command_policy.go, cli/command_policy_edit.go, cli/command_policy_remove.go, cli/command_policy_set.go, cli/command_policy_show.go
=> fix(cli): fixed and unified help text for policy commands

internal/editor/editor.go
=> fix(cli): fixing ignoring lines starting with '#' in 'policy edit'

go.mod, go.sum, internal/cache/content_cache_concurrency_test.go, internal/cache/content_cache_data.go, internal/cache/content_cache_metadata.go, internal/cache/persistent_lru_cache.go, internal/cache/persistent_lru_cache_test.go
=> feat(repository): ensure we don't run parallel fetches for the same blob IDs

internal/server/source_manager.go
This fixes a regression introduced in #1837
=> fix(server): fixed server startup race condition

cli/command_benchmark.go, cli/command_benchmark_compression.go, cli/command_benchmark_crypto.go, cli/command_benchmark_encryption.go, cli/command_benchmark_hashing.go, cli/command_benchmark_splitters.go, cli/command_benchmark_test.go
* added --parallel flag
* added `kopia benchmark encryption`
* added `kopia benchmark hashing`
=> feat(cli): improved `kopia benchmark` commands

tests/robustness/robustness_test/main_test.go, tests/tools/kopiarunner/kopia_snapshotter.go, tests/tools/kopiarunner/kopia_snapshotter_exe_test.go, tests/tools/kopiarunner/kopia_snapshotter_upgrade_test.go
KopiaSnapshotter provides test methods to perform kopia operations. Adding a new method that performs upgrade on a given repository.
=> test(general): Add a test method to perform repository format version upgrade

snapshot/snapshotfs/checkpoint_registry.go, snapshot/snapshotfs/checkpoint_registry_test.go, snapshot/snapshotfs/dir_manifest_builder.go, snapshot/snapshotfs/dir_writer.go, snapshot/snapshotfs/upload.go
=> refactor(snapshots): made DirManifestBuilder public

repo/blob/gdrive/gdrive_storage.go
The current implementation of gdrive repository doesn't support [Shared drives](https://support.google.com/a/answer/7212025). The PR adds support for it
=> feat(repository): gdrive supports shared drives

site/content/docs/Advanced/Actions/_index.md
I am setting up a windows 10 host and I am using shadow copies, this is what I had to change to get things working. I published a short install guide over at https://git.sr.ht/~digital/kopia-win-shadow-copy.
Thank you for making kopia, it is exactly what I want. I'm providing backups for my family. Kopia is easy to set up, easy to use, can backup to my linux NAS and has a gui to make everyone feel comfortable ^-^
=> docs(site): Digital docs actions

repo/content/content_manager.go, repo/content/content_manager_test.go
In a very rare case, when content is created then deleted or forgotten
and immediately recreated in the same second, the newly recreated
content may be ignored due to how indices are merged.
This change ensures that on each {write,delete,forget} we always move
the time forward relative to latest index entry, even if the local clock
did not advance at all or moves backwards.
=> fix(repository): fix deletion immediately after creation

.github/workflows/code-coverage.yml, .github/workflows/compat-test.yml, .github/workflows/endurance-test.yml, .github/workflows/htmlui-tests.yml, .github/workflows/license-check.yml, .github/workflows/make.yml, .github/workflows/provider-tests.yml, .github/workflows/race-detector.yml, .github/workflows/stress-test.yml, .github/workflows/tests.yml
We were unintentionally doing that because ^1.17 was pulls 1.18.1
=> chore(ci): set golang version explicitly to 1.18

repo/maintenance/content_rewrite.go
When environment variable `KOPIA_IGNORE_MAINTENANCE_REWRITE_ERROR` is set, this will ignore rewrite problems for deleted contents because of mising blobs. In case of data corruption this should let maintenance complete and eventually completely drop unused content from the index.
This is not something that regular folks should ever use, except when recovering repository after a data loss after being instructed to do so by Kopia crew.
For #1946
=> feat(cli): added KOPIA_IGNORE_MAINTENANCE_REWRITE_ERROR

cli/command_snapshot_fix_test.go, cli/command_snapshot_list.go, cli/command_snapshot_list_test.go, cli/command_snapshot_pin_test.go, cli/command_snapshot_storage_stats_test.go, tests/end_to_end_test/snapshot_create_test.go, tests/end_to_end_test/snapshot_migrate_test.go
=> fix(cli): add retention to JSON output

site/content/docs/Advanced/Actions/_index.md
Updated documentation for enabling actions for KopiaUI.
=> docs(site): updated documentation for enabling actions for KopiaUI

go.mod, go.sum
Contributeds by @basldfalksjdf, thanks!
Also upgraded React tooling to the latest version.
=> feat(ui): added 'Ignore Identical Snapshots'

snapshot/snapshotfs/checkpoint_registry.go, snapshot/snapshotfs/checkpoint_registry_test.go, snapshot/snapshotfs/upload.go
This refactors a helper that will later be used for parallel uploading of a large files.
=> refactor(snapshots): refactored upload of files

go.mod, go.sum
* https://github.com/kopia/htmlui/pull/61 by @adowair
* https://github.com/kopia/htmlui/pull/62 by @gitname
* https://github.com/kopia/htmlui/pull/63 by @L1ghtmann
* https://github.com/kopia/htmlui/pull/64 by @gitname
* https://github.com/kopia/htmlui/pull/65 by @gitname
=> feat(ui): imported latest changes to HTMLUI

README.md, site/content/docs/Contribution guidelines/_index.md
- removed security notice
- removed disclaimer
- updated security notification address
=> chore(general): updated README.md

cli/command_benchmark_compression.go, go.mod, go.sum, internal/server/api_repo.go, internal/serverapi/serverapi.go, repo/compression/compressor.go, repo/compression/compressor_lz4.go, repo/compression/compressor_zstd.go
Some compression algorithms are not recommended because they
allocate disproportionate amounts of memory. They are still
possible to use, just marked as NOT RECOMMENDED in the UI.
=> feat(ui): support for deprecation of certain algorithms

site/content/docs/Features/_index.md
=> docs(site): Rewording features page

internal/server/source_manager.go
=> fix(ui): fixed scheduling of snapshots with Ignoring Identical Snapshots

go.mod, go.sum, internal/freepool/freepool.go
Reverted to regular sync.Pool
Fixes #2150
=> fix(snapshots): panic: unaligned 64-bit atomic operation

app/public/electron.js
=> fix(ui): fixed missing directory browser button in KopiaUI

Makefile, go.mod, go.sum, tests/end_to_end_test/server_start_test.go
* https://github.com/kopia/htmlui/pull/88
* https://github.com/kopia/htmlui/pull/90
* https://github.com/kopia/htmlui/pull/89
* https://github.com/kopia/htmlui/pull/84
* https://github.com/kopia/htmlui/pull/85
=> chore(ui): upgraded UI

internal/server/api_restore.go, internal/server/api_restore_test.go, internal/serverapi/client_wrappers.go, snapshot/restore/local_fs_output.go, snapshot/restore/restore.go
Added comprehensive test for restore API which was previously completely uncovered.
Fixes https://github.com/kopia/kopia/issues/2162
=> fix(ui): fixed filesysystem restores triggered from UI

internal/logfile/logfile.go, internal/logfile/logfile_test.go
Improved test logic which missed this.
=> fix(cli): removed unnecessary console log timestamps

README.md, site/config.toml, site/content/docs/FAQs/_index.md, site/content/docs/Features/_index.md, site/content/docs/Getting started/_index.md, site/content/docs/Installation/_index.md, site/content/docs/Reference/_index.md, site/content/docs/Release Notes/_index.md, site/content/docs/Repositories/_index.md, site/content/docs/Upgrade/_index.md, site/content/docs/_index.md
-Reworked repositories page
-Minor edits to Getting Started Guide
-Minor edits to Features page
-Minor edits to Docs homepage
-Minor edits to Github homepage
-Modified side/top navigations to make better use of both navigations
=> docs(site): Updating documentation

repo/blob/rclone/rclone_storage.go, repo/blob/rclone/rclone_storage_test.go
There are many solutions floating online intended to help speed up
`rclone` performance with high-latency backends, such as Google Drive or
OneDrive.
One of the often-suggested ones is `--vfs-cache-mode`, which creates
an on-disk cache and performs uploads in the background
(asynchronous write-back).
This is not necessarily wrong when a single client is used, but may
cause problems when multiple Kopia clients share repository and
some of the writes are reordered or never happen, in particular in
case of crashes.
Fixes #2216
=> fix(providers): disabled rclone write-back behavior

repo/blob/rclone/rclone_storage.go, repo/blob/rclone/rclone_storage_test.go
There are many solutions floating online intended to help speed up
`rclone` performance with high-latency backends, such as Google Drive or
OneDrive.
One of the often-suggested ones is `--vfs-cache-mode`, which creates
an on-disk cache and performs uploads in the background
(asynchronous write-back).
This is not necessarily wrong when a single client is used, but may
cause problems when multiple Kopia clients share repository and
some of the writes are reordered or never happen, in particular in
case of crashes.
Fixes #2216
=> fix(providers): disabled rclone write-back behavior (#2218)

site/content/docs/Installation/_index.md
Add FreeBSD port/package install instructions
=> docs(site): Add FreeBSD port/package installation instructions

.github/workflows/auto-merge.yml
=> Revert "build(deps): bump actions/checkout from 2 to 3"

tests/robustness/snapmeta/kopia_persister_light_test.go
=> fix(general): skip TestS3Connect() until we fix the S3 regression

tools/docker/Dockerfile
i guess compatible with docker-publish.sh
=> Dockerfile based on Ubuntu

tools/docker/Dockerfile
=> fix(general): install missing ca-certificates in Docker

internal/repotesting/repotesting.go, repo/maintenance/maintenance_schedule.go, repo/repository.go, repo/repository_test.go
See https://github.com/kopia/kopia/commit/23299c34512e640d50e1ddff888758a119a09cb8
=> fix(repository): fixed V1 key derivation bug from previous refactoring

repo/maintenance/maintenance_run.go
Unlike on other OSes it appears that on Windows time.Now() called twice
in quick succession can return the same value.
Switched logic using `time.After()` to `!time.Before()`
=> fix(ci): fixed TestFullMaintenance on Windows

cli/command_repository_create.go
Since the options will be visible by the UI, I think it makes sense to do the same in the CLI.
=> chore(cli): make ecc options visible but marked as experimental

go.mod, go.sum, internal/server/api_repo.go, internal/serverapi/serverapi.go, repo/format/content_format.go, repo/format/format_provider.go
This allows the GUI to show/configure ECC.
=> feat(server): Added ECC to server api

cli/command_repository_upgrade.go, cli/command_repository_upgrade_test.go
This adds a hidden flag to the upgrade CLI to allow tests to lock a repository without actually performing the upgrade draining mechanism and the index upgrade itself. The current mechanism to simulate a locked repo is by done by killing the CLI during draining but that approach is pretty flaky. This should help avoid failures like this:
https://github.com/kopia/kopia/runs/7920935223?check_suite_focus=true
=> feat(cli): flag to allow placing the upgrade lock without actually upgrading

cli/observability_flags.go
See https://github.com/kopia/kopia/issues/1903#issuecomment-1127172904
=> fix(cli): Fix `/debug/pprof/heap` returning 404

cli/command_snapshot_copy_move_history.go, cli/command_snapshot_create.go, cli/command_snapshot_delete.go, cli/command_snapshot_expire.go, cli/command_snapshot_fix.go, cli/command_snapshot_list.go, cli/command_snapshot_migrate.go, cli/command_snapshot_pin.go, cli/command_snapshot_verify.go, fs/entry.go, fs/utc_timestamp.go, fs/utc_timestamp_test.go, internal/repotesting/repotesting_test.go, internal/server/source_manager.go, internal/serverapi/serverapi.go, snapshot/manifest.go, snapshot/policy/retention_policy.go, snapshot/policy/retention_policy_test.go, snapshot/snapshotfs/checkpoint_registry_test.go, snapshot/snapshotfs/dir_manifest_builder.go, snapshot/snapshotfs/repofs.go, snapshot/snapshotfs/source_directories_test.go, snapshot/snapshotfs/upload.go
=> feat(repository): introduced fs.UTCTimestamp

repo/format/format_manager.go
=> fix(repository): fixed async write error

Makefile, go.mod, go.sum, tests/htmlui_e2e_test/htmlui_e2e_test.go
See https://github.com/kopia/htmlui/pull/110
=> fix(ci): fixed the root cause of the HTMLUI test flake

internal/server/server_test.go, repo/api_server_repository.go, repo/grpc_repository_client.go
Benchmarked from macOS client to a Linux server over Wifi connection: (2-5ms latency)
linux 5.14.8 (1.1 GB) to a clean repository:
Before: 240s After: 27s (90% faster)
Fixes #2372
=> feat(repository): improve performance when snapshotting to a repository server

internal/bigmap/bigmap_internal.go, internal/tempfile/tempfile.go, internal/tempfile/tempfile_linux.go, internal/tempfile/tempfile_test.go, internal/tempfile/tempfile_unix_fallback.go, internal/tempfile/tempfile_unix_nonlinux.go, internal/tempfile/tempfile_windows.go
=> feat(general): added tempfile package

app/package-lock.json, app/package.json
This reverts commit 5fce956853a60c8fa32bbdd3066b255d31128a9a.
The app built with 20.0.1 fails to start on at least darwin/arm64, needs to be investigated.
=> build(deps-dev): revert electron upgrade from 19.0.8 to 20.0.1 in /app

Makefile, app/Makefile, app/package-lock.json, app/package.json, app/public/electron.js, app/public/preload.js, app/tests/main.spec.js
```
$ make kopia-ui-test
```
This currently executes super minimal E2E test on pre-built KopiaUI using Playwright https://playwright.dev
=> test(ui): added minimal automated KopiaUI test

go.mod, go.sum
From https://github.com/kopia/htmlui/pull/112
=> feat(ui): fix labels when browsing snapshots

site/content/docs/Installation/_index.md
Please wait till example docker-compose-yml #2253 PR is merged.
=> Added Dockerfile based on ubuntu related info

internal/server/server_test.go, repo/api_server_repository.go, repo/grpc_repository_client.go, repo/open.go, repo/refcount_closer.go, repo/repository.go, repo/server_repository_params.go
This extracts common bits shared by HTTP and GRPC implementations into one.
=> refactor(repository): refactored server repository implementations

site/content/docs/Installation/_index.md
added 
brew install kopiaui
there is a new homebrew cask installation available:
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/kopiaui.rb
=> docs(site): add homebrew installation for kopiaui

README.md
'storages' isn't really a word.  It's like 'fetch' isn't an adjective.
=> docs(site): Update README.md

cli/command_repository_create.go, cli/command_repository_status.go, cli/command_repository_upgrade_test.go
This pull request collects a number of small changes to improve usability of the Kopia format upgrade (and related) commands. Description of each change is in the associated commit below.
=> docs(cli): minor improvements to upgrade CLI usage/documentation

site/content/docs/Repository Server/_index.md
- Added server control credentials to `kopia server start` example
- Reformatted `kopia server start` to avoid excessive horizontal scrolling
- Moved pre-v0.8 information to quoted notes to reduce confusion
=> docs(site): added control credentials to example

site/content/docs/Advanced/Actions/_index.md, site/content/docs/Advanced/Architecture/_index.md, site/content/docs/Advanced/Caching/_index.md, site/content/docs/Advanced/Compatibility/_index.md, site/content/docs/Advanced/Compression/_index.md, site/content/docs/Advanced/Consistency/_index.md, site/content/docs/Advanced/ECC/_index.md, site/content/docs/Advanced/Encryption/_index.md, site/content/docs/Advanced/Logging/_index.md, site/content/docs/Advanced/Maintenance/_index.md, site/content/docs/Advanced/Sharding/_index.md, site/content/docs/Advanced/Storage Tiers/_index.md, site/content/docs/Advanced/Synchronization/_index.md, site/content/docs/Advanced/_index.md, site/content/docs/Installation/_index.md
Hi all, 
this PR comes with the following changes:
- Unified the headings of the sub-sections within the "advanced" section
- Created an outline for the "advanced" section
- Changed the ordering of the advanced section to a more meaningful representation
- Fixed a typo within the installation guide
Cheers,
=> docs(site): unified headings - created an outline within the advanced section

internal/freepool/freepool_test.go
This PR adds unit tests for `freepool` (100% coverage)
=> test(general): added unit tests for freepool

internal/tlsutil/tlsutil_test.go
This PR adds some tests to tlsutil.
=> test(general): added tests for tlsutil

internal/diff/diff_test.go
This PR adds some basic unit tests for the diff package.
=> test(general): added unit tests for diff

internal/repotesting/repotesting.go, repo/repository.go, repo/repository_test.go
=> fix(repository): remove *metrics.Registry from repo.Repository

.github/workflows/make.yml
=> fix(ci): don't auto-submit HomeBrew pull requests for testing releases

internal/parallelwork/parallel_work_queue.go, internal/parallelwork/parallel_work_queue_test.go
This PR adds unit tests for parallelwork (100% coverage).
=> test(general): added tests for parallelwork

go.mod, go.sum, internal/server/server.go, tests/htmlui_e2e_test/htmlui_e2e_test.go
- theming support https://github.com/kopia/htmlui/pull/150
- actions fix https://github.com/kopia/htmlui/pull/163
Thanks @lupusA
=> feat(ui): UI updates (Theming support, action fix)

cli/observability_flags.go
Create directory in `.startMetrics` function
Store file name prefix for metrics instead of final name
=> refactor(cli): minor nits for observability flags

site/content/docs/Features/_index.md
=> docs: fix typo "maintence"

repo/manifest/manifest_manager_test.go
Use an options struct to make it more obvious when tests are running with read only storage.
Follow up based on comment in #3226
=> refactor(repository): Add options struct to test helper

go.mod, go.sum
* https://github.com/kopia/htmlui/pull/177
* https://github.com/kopia/htmlui/pull/141
=> feat(ui): imported latest UI changes

go.mod, go.sum
* https://github.com/kopia/htmlui/pull/186
* https://github.com/kopia/htmlui/pull/187
* https://github.com/kopia/htmlui/pull/188
=> chore(ci): upgraded UI

app/public/electron.js
This PR implements a workaround for the following issue: https://github.com/electron/electron/issues/10862
The idea is to:
- Get all displays and check whether all scale factors are the same
- If so, retain the window size and location, if not revert to the default
Feedback is welcomed. 
Cheers,
=> fix(kopiaui): Workaround for wrong window bounds in multi display environments

site/content/docs/Repositories/_index.md
Hi there!
This should fix some formatting and spelling issues on the "Repositories" Docs page!
=> docs(site): Improve "Repositories" formatting & spelling mistakes

tests/tools/kopiarunner/kopia_snapshotter.go
Fixup error output when server startup fails in robustness test
=> test(general): Fixup error output when server startup fails in robustness test 

repo/blob/azure/azure_storage.go
- rename variable
- clarify comment
=> chore(general): cleanup nits

tests/tools/kopiarunner/kopia_snapshotter.go
Fix typo as well
Followup to #3462
=> chore(general): simplify block

internal/metrics/metrics_distribution.go, internal/metrics/metrics_registry.go, internal/metrics/metrics_timeseries.go, internal/metrics/metrics_timeseries_counter.go, internal/metrics/metrics_timeseries_durations.go, internal/metrics/metrics_timeseries_sizes.go, internal/metrics/metrics_timeseries_test.go, internal/metrics/metrics_timeseries_timeres.go, internal/metrics/metrics_timeseries_timeres_test.go
This code is not used anywhere yet, will be used for reporting over repository metrics.
=> feat(repository): added metrics timeseries computation

.github/workflows/make.yml, Makefile, app/notarize.js
This should recent regression after Electron upgrade.
Fixes #3711
=> chore(ci): install apple notarization key before build

internal/epoch/epoch_utils.go
=> refactor(general): add clarification comment

cli/command_user_add_set.go, internal/auth/authn_repo.go, internal/auth/authn_repo_test.go, internal/crypto/key_derivation_nontest.go, internal/crypto/key_derivation_testing.go, internal/crypto/pbkdf.go, internal/crypto/scrypt.go, internal/user/user_profile.go, internal/user/user_profile_hash_v1.go, internal/user/user_profile_test.go, repo/open.go
Refer to https://github.com/kopia/kopia/pull/3670 for discussion
=> feat(general): Add alternate key derivation algorithms

internal/epoch/epoch_manager.go, internal/epoch/epoch_manager_test.go
Ref:
- Extracted from #3651
- #3638
=> refactor(general): add epoch.Manager.CleanupMarkers

repo/maintenance/maintenance_run.go
=> refactor(general): rename var to hasEpochManager for clarity

internal/epoch/epoch_manager_test.go
=> refactor(general): explicitly advance epoch in test

repo/blob/azure/azure_storage_test.go
Fixes test failure introduced in #3760
https://github.com/kopia/kopia/actions/runs/8518078600/job/23329613384
Successful run:
https://github.com/kopia/kopia/actions/runs/8518153907/job/23329824793?pr=3767
=> fix(providers): check for ContainerAlreadyExists in Azure test

repo/compression/compressor_gzip.go, repo/compression/compressor_lz4.go, repo/compression/compressor_pgzip.go, repo/compression/compressor_s2.go, repo/compression/compressor_zstd.go
This has huge performance benefits for `zstd`, `pgzip`  and `s2`.
BEFORE:
```
0. s2-parallel-4              35.1 MB      8.9 GB/s     688      4.6 GB
1. s2-parallel-8              35.1 MB      8.1 GB/s     688      4.6 GB
2. s2-default                 35.1 MB      8 GB/s       689      4.6 GB
3. s2-better                  33.7 MB      7.2 GB/s     689      4.6 GB
4. zstd-fastest               18.4 MB      6.3 GB/s     22281    1.2 GB
5. zstd-better-compression    16.4 MB      5.3 GB/s     17957    2 GB
6. zstd                       18.1 MB      4.8 GB/s     17711    2.1 GB
7. deflate-best-speed         20.6 MB      3.7 GB/s     4672     6.4 MB
8. deflate-best-compression   18.4 MB      3.5 GB/s     8352     6.5 MB
9. pgzip-best-speed           20.6 MB      3.5 GB/s     27871    679.1 MB …
```
=> feat(repository): big reduction in memory usage during decompression

go.mod, go.sum
Compare: https://github.com/kopia/htmlui/compare/c5ffeee0c77cc4bd850dd5fb3b805315c476089d...
*This PR description was [auto-generated](https://github.com/kopia/htmluibuild/blob/main/.github/workflows/after-push.yaml) at Thu Apr  4 21:37:37 PDT 2024*
=> feat(ui): upgraded htmlui to the latest version

internal/epoch/epoch_advance.go, internal/epoch/epoch_utils.go, repo/maintenance/maintenance_run.go, tests/end_to_end_test/shallowrestore_test.go, tests/robustness/snapmeta/kopia_connector.go
=> chore(general): fix function names in comment

internal/crypto/pbkdf.go
Use the value recommended by NIST
=> refactor(general): change default number of iterations for PBKDF2

repo/content/content_manager.go
=> refactor(general): remove unused receiver

internal/epoch/epoch_manager.go, internal/epoch/epoch_manager_test.go
Cleanup.
- Fixes: #3638
- #3639
=> refactor(general): remove ability to enable compaction on index load

repo/grpc_repository_client.go, repo/grpc_repository_client_test.go, repo/grpc_repository_client_unit_test.go
Decompose the logic for parsing base URL into the URI for client dial.
Add a unit test for the new helper.
=> test(server): Decompose base URL to URI to helper and add test

app/package-lock.json, app/package.json
Addresses https://github.com/advisories/GHSA-9jxc-qjr9-vjxq
=> build(deps): upgrade electron-updater to 6.3.0-alpha.6

.github/workflows/make.yml, tools/rpm-publish.sh
=> chore(ci): fix RPM publishing

cli/terminate_signal_test.go, internal/feature/feature.go
chore(test): leverage `testutil.ServerParameters` in server test
chore(general): remove unused `Behavior` type
=> chore(general): misc cleanups

site/content/docs/Installation/_index.md
Remove the mention of snapshot and 7.1.
=> Improve OpenBSD installation doc

site/content/docs/Installation/_index.md
=> docs(general): update supported Windows version

site/content/docs/Advanced/Ransomware Protection/_index.md
Docs PR for https://github.com/kopia/kopia/pull/4134
=> docs(site): Add Google ransomware protection section

repo/content/index/one_use_index_builder.go, repo/content/index/packindex_test.go
A following up PR of #4139 to address comment https://github.com/kopia/kopia/pull/4139#discussion_r1793663722 and https://github.com/kopia/kopia/pull/4139#discussion_r1793665281.
=> refactor(repository): Following up code adjustment for on-use-builder

repo/maintenance/maintenance_quick_test.go, repo/maintenance/maintenance_run.go
Tests included.
Known to be safe portion of the changes proposed in #3901
=> fix(general): run epoch maintenance for quick maintenance

site/content/docs/Advanced/Ransomware Protection/_index.md, site/content/docs/Repositories/_index.md
=> docs(site): list all required permissions for GCS

repo/content/content_manager_test.go
Remove unreachable code in `content_manager_test.go`
Found with [revive](https://github.com/mgechev/revive/)
=> fix(repository): remove unreachable code in content_manager_test.go

repo/content/index/packindex_test.go
Objective: make it easier to understand the tests
Changes:
- Introduce helpers to simplify the tests and increase clarity.
- Rename tests to better convey what they are testing.
Individual commits show the individual changes to facilitate reviews.
Ref:
- #4139
=> test(general): cleanup index builder tests

cli/command_logs_test.go, cli/command_maintenance_run.go
- Fixes: #2775
- Fixes: #3600
- #4185
=> fix(cli): allow running quick maintenance with epoch manager

internal/auth/authn_repo_test.go, internal/user/password_hashings.go, internal/user/user_profile.go, internal/user/user_profile_test.go
=> fix(server): handle unset password hash version in user profile

Makefile, app/kopia-ui.apparmor, app/package-lock.json, app/package.json, app/tests/main.spec.js
This should also fix broken CI which started failing since `ubuntu-latest` became 24.04
=> feat(kopiaui): support for AppArmor on Ubuntu 24.04

fs/ignorefs/ignorefs_test.go, fs/localfs/local_fs_test.go
=> test(general): cleanup symlink tests

repo/content/indexblob/index_blob_manager_v1.go
Changes the log level from `ERROR` to `DEBUG`.
Thanks to @plar
=> chore(general): reduce verbosity for noisy log message

go.mod, go.sum
Updates[`github.com/Azure/azure-sdk-for-go/sdk/storage/azblob`](https://github.com/Azure/azure-sdk-for-go) from 1.5.0 to 1.6.0
- [Release notes](https://github.com/Azure/azure-sdk-for-go/releases)
- [Changelog](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/release.md)
- [Commits](https://github.com/Azure/azure-sdk-for-go/compare/sdk/azcore/v1.5.0...sdk/azcore/v1.6.0)
---
dependency-name: github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
dependency-type: direct:production
update-type: version-update:semver-minor dependency-group: common-golang-dependencies
...
=> build(deps): github.com/Azure/azure-sdk-for-go/sdk/storage/azblob

cli/command_policy_export.go
=> fix(cli): add newline after policy export output

tools/tools.mk
- Fixes issue introduced in #4506
=> fix(build): correct command to get commit date

.golangci.yml, internal/metrics/metrics_distribution.go, internal/metrics/metrics_thresholds.go
=> chore(ci): enable exptostd linter

internal/logfile/logfile.go, internal/logfile/logfile_test.go
- Fixes #2822
- Initial PR: #3147
Thanks to @NickIAm for the initial PR.
=> fix(cli): create cache marker in log directories

cli/command_policy.go, cli/command_policy_edit.go, cli/command_policy_export.go, cli/command_policy_remove.go, cli/command_policy_set.go, site/content/docs/Getting started/_index.md
The docs are somewhat unclear regarding per-host and per-user policies. This PR hopefully clarifies their behavior a bit in the docs
See also #4341
=> docs(cli): clarify documentation regarding per-user and per-host

.golangci.yml, repo/blob/filesystem/filesystem_storage_test.go, tests/end_to_end_test/restore_test.go
fix unnecessaryDefer exclusion
=> fix(ci): remove `unnecessaryDefer` exclusion (gocritic)

.golangci.yml
=> chore(ci): remove unused linter exclusions

snapshot/upload/upload.go, snapshot/upload/upload_test.go
Credit:  @alexvbg  Aleksandr Samarin <alexvbg@users.noreply.github.com>
=> fix(general): avoid removing error cause

cli/app.go
Remove `repositoryAccessMode.mustBeConnected`
It is always `true`.
Rename `repositoryAccessMode.disableMaintenance` to `allowMaintenance`.
This explicitly conveys when maintenance is allowed to run. This is related to accessing a repository in 'read-only' mode.
=> refactor(cli): cleanup `cli.repositoryAccessMode`

internal/diff/diff_test.go
Helper to generate (direct) object ids.
=> test(cli): minor cleanups in diff tests

tools/tools.mk
Add convenience targets
- `install-gotestsum`
- `install-linter`
=> chore(general): convenience make targets to install tools

repo/content/content_manager.go, snapshot/upload/upload_test.go
- add assertion messages to help troubleshooting upload tests.
- fix typo
- fix debug log message
=> refactor(general): minor cleanups

.github/workflows/auto-merge.yml, .github/workflows/check-pr-title.yml, .github/workflows/dependency-review.yml
Addresses reported security vulnerabilities in Go's standard library.
=> chore(ci): pin actions

repo/encryption/encryption.go
=> fix(general): migrate remnant piece to `crypto/hkdf`

internal/logfile/logfile.go
This patch introduces a new CLI flag `--disable-file-logging` that allows users to prevent Kopia from writing any log files to disk.
When enabled, this flag disables all file-based logging mechanisms, including the creation of log files and directories.
This is particularly useful in containerized or ephemeral environments where persistent log files are undesirable.
=> feat(cli): add --disable-file-logging to suppress log file output

repo/blob/azure/azure_options.go
Adds missing `` `kopia:"sensitive"` `` tags
=> fix(providers): add tags in `azure.Options`

repo/content/sessions.go, repo/content/sessions_test.go
=> refactor(general): cleanup clock bounds check

cli/storage_azure.go, repo/blob/azure/azure_options.go, repo/blob/azure/azure_storage.go, repo/blob/azure/azure_storage_test.go
Add authentication support for Azure Federated Identity (AFI)
=> feat(providers): Azure Federated Identity support

internal/serverapi/serverapi.go
needed for https://github.com/kopia/htmlui/pull/378
=> feat(ui): added locale to UIPreferences

repo/blob/azure/azure_storage_test.go, repo/blob/azure/azure_ua_test.go
Test without a proxy environment variable
Authored by: @andrason
=> test(providers): fix `azure.TestUserAgent`

repo/content/content_manager_iterate.go
=> chore(general): set packID when creating the map entry

repo/maintenance/maintenance_schedule.go, tests/end_to_end_test/server_start_test.go
=> refactor(general): increase number of retained maintenance run info

cli/app.go, cli/observability_flags.go
=> refactor(general): cleanup observabilityFlags
