- cli/app.go
- cli/command_benchmark_crypto.go
- cli/command_benchmark_splitters.go
- cli/command_repository_create.go
- cli/command_repository_status.go
- go.mod
- go.sum
- internal/repotesting/repotesting.go
- repo/initialize.go
- repo/object/object_manager.go
- repo/object/object_manager_test.go
- repo/object/object_splitter.go
- repo/object/object_splitter_test.go
- repo/object/object_writer.go
- repo/object/splitter_buzhash32.go
- repo/object/splitter_fixed.go
- repo/object/splitter_rabinkarp64.go
- repo/open.go
- repo/repository_test.go
The splitter in question was depending on
github.com/silvasur/buzhash which is not licensed according to FOSSA bot
Switched to new faster implementation of buzhash, which is
unfortunately incompatible and will split the objects in different
places.
This change is be semi-breaking - old repositories can be read, but
when uploading large objects they will be re-uploaded where previously
they would be de-duped.
Also added 'benchmark splitters' subcommand and moved 'block cryptobenchmark'
subcommand to 'benchmark crypto'.
> Deprecated DYNAMIC splitter due to license issue

- cli/command_cache_info.go
- cli/command_cache_set.go
- cli/command_repository_connect.go
- cli/command_repository_status.go
- repo/connect.go
- repo/content/caching_options.go
- repo/content/content_cache.go
- repo/content/content_cache_test.go
- repo/content/content_manager.go
- repo/content/info.go
All blocks with a non-empty prefix land in that cache which has its own
size and expires independently from content cache.
> Added separate cache for metadata.

- cli/command_repository_connect_from_config.go
- cli/command_repository_status.go
- cli/password.go
- repo/token.go
- site/content/docs/Reference/Command-Line/_index.md
- tests/end_to_end_test/end_to_end_test.go
Repository.Token() generates a base64-encoded token that can
be stored in password manager that fully describes repository connection
information (blob.ConnectionInfo) and optionally a password.
Use `kopia repo status -t` to print the token.
Use `kopia repo status -t -s` to print the token that also includes
repository password.
Use `kopia repo connect from-config --token T` to reconnect using the
token.
> Added support for reconnect tokens

- repo/blob/sftp/sftp_storage.go
- repo/blob/sftp/sftp_storage_test.go
Tests are failing because pkg/sftp won't overwrite an existing file
(Rename function) and the test is actually doing that with
blobtesting.VerifyStorage.
The solution is to use pkg/sftp's PosixRename function:
"PosixRename renames a file using the posix-rename@openssh.com
extension which will replace newname if it already exists."
Additionally, the provider now creates the path on the server, if it
doesn't exist.
> Improve sftp provider logic

- Makefile
- tests/end_to_end_test/end_to_end_test.go
This allows overriding 'go test' command with a wrapper that provides coloring (https://stackoverflow.com/questions/27242652/colorizing-golang-test-run-output)
> minor testability tweaks

- cli/command_index_recover.go
- cli/command_repository_repair.go
- repo/content/content_index_recovery_test.go
- repo/content/content_manager.go
- repo/manifest/manifest_manager_test.go
This puts all content blocks with non-empty prefix into starting with
`q` instead of `p`. This neatly separates all data (p) from metadata
(q) at the storage level and allows different storage policies, since
most data is not going to be ever accessed ever, but metadata is going
to be read a lot..
We can more aggressively cache contents from `q`.
> Added support for separate packs for metadata

- cli/command_content_list.go
- cli/command_content_rewrite.go
- repo/content/builder.go
- repo/content/content_manager.go
- repo/content/merged.go
This uses callbacks avoids having to buffer
all content infos in memory and does not require holding a lock.
> added content.Manager Iterate()

- cli/command_content_gc.go
- cli/command_content_list.go
- cli/command_content_rewrite.go
- cli/command_content_stats.go
- cli/command_content_verify.go
- examples/upload_download/main.go
- repo/blob/storage.go
- repo/content/builder.go
- repo/content/content_manager.go
- repo/content/content_manager_test.go
- repo/manifest/manifest_manager.go
- repo/manifest/manifest_manager_test.go
- tests/repository_stress_test/repository_stress_test.go
This was previously forcing allocation of the slice for all contents in the repository (unbounded). Replaced with much more memory-efficient iteration.
Note that still in order to list packs we need to keep them in memory, but that can be further optimized when needed, for example by using sharding and repeated iteration of contents.
> removed content.Manager.ListContents*() API

- .gitignore
- .travis.yml
- Makefile
- tests/compat_test/gen-compat-repo.sh
This is triggered for tagged releases and will be used later for
long-term repository compatibility testing.
> travis: generate repository snapshot for long-term storage

- cli/password.go
- internal/logfile/logfile.go
- internal/retry/retry.go
- repo/blob/storage.go
- repo/blob/webdav/webdav_storage.go
- repo/blob/webdav/webdav_storage_test.go
- improved HTTP error handling
- added exponential back-off around gowebdav calls
- fixed blob.ListAllBlobsConsistent which was never finishing for WebDAV
Fixes #88 - 429 Too Many Requests - PROPFIND /n0a #88
Fixex #89 - Debug log clashes with interactive repo password request
> webdav: improved error handling

- site/content/docs/Architecture/_index.md
Removes stale docs as it looks like the `kopia/repo` project has been archived and moved in here.
> Remove stale reference to the repo project

- fs/localfs/local_fs.go
- parallelized os.Lstat() x 16 (dramatically improves speed)
- discarded unused portions of os.FileInfo (uses 60% less RAM on macOS)
BEFORE:
10:47:03.670 [kopia/localfs] listed 200000 entries in 43.871211686s using 79126528 bytes of heap
After:
10:49:12.439 [kopia/localfs] listed 200000 entries in 1.953018184s using 30515200 bytes of heap
> localfs: improved performance and memory usage when scanning large directories

- cli/app.go
- cli/memory_tracking.go
Usage `--track-memory-usage=1s` or another interval.
> cli: added -–track-memory-usage flag that periodically logs memory usage

- internal/logfile/logfile.go
Reduces multi-GB log files. Main culprits were:
- [upload.go:385] could not find cache entry for...
- [content_manager.go:790] WriteContent("...") - new
- [content_manager.go:396] adding ... length=... deleted=false
> Switch file log level to info

- repo/content/content_index_recovery.go
- repo/content/content_manager.go
- repo/content/content_manager_iterate.go
- repo/content/content_manager_lock_free.go
- repo/content/list_cache.go
- separated portions that don't require locking into separate struct
to make it easier to reason about state
- moved iteration-related content to separate file
> content: refactored content manager

- internal/blobtesting/faulty.go
- repo/content/content_manager.go
- repo/content/content_manager_test.go
- repo/repository.go
- tests/repository_stress_test/repository_stress_test.go
Previously, it was possible for Flush() to miss in-flight writes,
but only when using repository manually since Uploader guarantees
there are no in-flight writes when it completes.
With this change Flush() will guarantee that any pending writes
completed before Flush() has started are guaranteed to be committed
to the repository before Flush() returns.
This was actually a regression introduced in #105.
Added regression test to prevent it from reoccurring.
> content: fixed content.Manager.Flush() race

- cli/command_snapshot_gc.go
- cli/command_snapshot_verify.go
- internal/parallelwork/parallel_work_queue.go
- repo/manifest/manifest_manager.go
- repo/manifest/manifest_manager_test.go
- snapshot/snapshotfs/snapshot_tree_walker.go
- tests/end_to_end_test/end_to_end_test.go
`snapshot gc` marks contents not reachable from the root of any snapshot as soft-deleted
The algorithm is a mark-and-sweep with parallel iteration of objects.
Currently it stores content IDs and object IDs in a map, so won't scale
to huge repositories, but this can be fixed in the future.
This fixes #110 at least for reasonable repository sizes.
> cli: implemented 'snapshot gc' and moved `verify` to be `snapshot verify`

- repo/content/content_manager.go
- repo/content/content_manager_test.go
In order to guarantee that all index entries have corresponding
pack blobs, we must ensure that `content.Manager.Flush` will
not succeed unless all pending writes have completed.
Added test that simulates various patterns of PutBlock failures and
ensures that data remains durable despite those, assuming all calls
to `WriteContent()` and `Flush()` are retried.
> Fixed how blob storage PutBlob errors are handled in content.Manager

- .gitattributes
Removes git warnings about tabs in indentation for Go files.
> Add .gitattributes with settings for Go

- cli/command_snapshot_gc.go
- snapshot/gc/gc.go
- snapshot/snapshotfs/snapshot_tree_walker.go
This allows leveraging `TreeWalker` for other uses. Initially, it will be used to address #114.
This is only re-factoring, no functional changes.
The PR is split into self-contained commits to facilitate reviewing.
* 8c4754d is code movement only (to a new package)
* b1b29da allows specifying a function to a `TreeWalker` to extract an identifier from an `fs.Entry`
* Lastly, edf2cce changes the signature of `TreeWalker.Callback` to pass an `fs.Entry` instead of an  `object.ID`.
`TreeWalker` could be moved to the `kopia/fs` package, but it's not done in this PR.
> Allow passing an fs.Entry to TreeWalker.Callback

- fs/cachefs/cache.go
Motivation: An unlock is missing in the error path
> Ensure Mutex.Unlock() in cachefs.Cache.getEntries()

- fs/cachefs/cache.go
- Consistent locking/unlocking of `c.mu` in `Cache.getEntries`
- Fix CI failure
`Cache.getEntriesFromCache()` was releasing `c.mu` when returning an entry and not releasing it when returning nil. Previously, the caller (`Cache.getEntries`) was accordingly not releasing `c.mu` when `getEntriesFromCache()` was returning an entry, and unlocking `c.mu` otherwise.
`Cache.getEntries` is the only caller for `getEntriesFromCache`.
After this change c.mu is consistently locked and unlocked in `getEntries`
Also rename function to `Cache.c.getEntriesFromCacheLocked`
```
go test -count=1 -timeout 90s github.com/kopia/kopia/...
?   	github.com/kopia/kopia	[no test files]
?   	github.com/kopia/kopia/cli	[no test files]
?   	github.com/kopia/kopia/examples/upload_download	[no test files]
? …
```
> Fix double unlock in Cache.getEntries

- fs/cachefs/cache.go
- fs/cachefs/cache_test.go
See #130 and #132
```
go test -timeout 30s github.com/kopia/kopia/fs/cachefs -run ^(TestCacheGetEntriesLocking)$
ok  	github.com/kopia/kopia/fs/cachefs	0.006s
Success: Tests passed.
```
> Simple test for Cache.getEntries() locking/unlocking

- cli/command_policy_edit.go
- cli/command_policy_remove.go
- cli/command_policy_set.go
- cli/command_policy_show.go
- cli/command_server_start.go
- cli/command_snapshot_create.go
- cli/command_snapshot_estimate.go
- cli/command_snapshot_expire.go
- cli/command_snapshot_list.go
- cli/command_snapshot_migrate.go
- cli/command_snapshot_verify.go
- cli/snapshot_utils.go
- tests/end_to_end_test/end_to_end_test.go
- Add optional flags to override hostname and username
- Add the flags to `snapshot`, `policy` and `server start` commands
- Add a test case in the E2E tests to create and list snapshots with overridden hostname and username
- #124 
Added a case to the existing E2E test
```
=== RUN   TestEndToEnd
PASS
ok      github.com/kopia/kopia/tests/end_to_end_test    21.270s
```
> [#124] Add optional flags to override hostname and username

- .golangci.yml
- cli/command_benchmark_crypto.go
- cli/command_snapshot_estimate.go
- cli/memory_tracking.go
- internal/mockfs/mockfs.go
- repo/blob/s3/s3_options.go
- repo/content/content_manager_test.go
- repo/content/format.go
Flagged by `golangci` while testing version 1.21.0
There were other (noisy?) failures not addressed in this PR. Punting for now.
> Minor cleanups

- cli/app.go
- cli/command_diff.go
- cli/command_restore.go
- fs/localfs/copy.go
- go.mod
- go.sum
- internal/diff/diff.go
- internal/fshasher/fshasher.go
- internal/fshasher/fshasher_test.go
- snapshot/snapshotfs/restore.go
- tests/end_to_end_test/end_to_end_test.go
Behavior:
- Creates top directory on restore
- Fails when target directories or files already exist
- Allows restoring to local root directory
- Restores of file attributes => mod time, mode, owner info
- Only a directory can be specified as a parameter
Not implemented:
- Restoring attributes of the top folder
- Restoring symlinks
- Restoring a single file
End-to-end test included
#114
> [114] Restore command

- cli/command_snapshot_delete.go
- tests/end_to_end_test/end_to_end_test.go
Implemented snapshot delete command. Behaves similarly to manifest rm, but with extra verification steps. 
- Checks that the referenced manifest is of type "snapshot"
- Checks that the ID points to a snapshot, checks that the host name, user name, and path provided by flag or defaults match the source of the snapshot ID. Command will fail if they do not match, except if given --unsafe-ignore-source, which will bypass the associated safety requirement and delete anyway.
Added end to end tests for input combinations, restore in conjunction with delete, and trying to snapshot delete a manifest by ID of a non-snapshot manifest.
> Dedicated snapshot delete command to delete by snap ID

- cli/command_restore.go
- cli/command_snapshot_restore.go
- snapshot/manager.go
- snapshot/snapshotfs/restore.go
- tests/end_to_end_test/end_to_end_test.go
Snapshot restore will take a snapshot ID and restore the
associated snapshot to the target path.
- Looks up the manifest with the snapshot ID
- Gets the snapshot root entry
- Copies the snapshot from the root entry to the target path
Because it uses the parent manifest with the copied permissions,
the restored directory will have the permissions of the original
source directory.
> Snapshot restore command

- cli/command_snapshot_delete.go
- tests/end_to_end_test/end_to_end_test.go
Fix various errors flagged by the `goimports`, `wsl`, `funlen` linters
Not sure why these did not show up in the original PR.
```
make lint
kopia/tools/.tools/bin/golangci-lint --deadline 180s run | tee .linterr.txt
cli/command_snapshot_delete.go:5: File is not `goimports`-ed with -local github.com/kopia/kopia (goimports)
tests/end_to_end_test/end_to_end_test.go:303: Function 'TestSnapshotDelete' is too long (187 > 100) (funlen)
func TestSnapshotDelete(t *testing.T) {
tests/end_to_end_test/end_to_end_test.go:306:2: only one cuddle assignment allowed before range statement (wsl)
for _, tc := range []struct {
^
tests/end_to_end_test/end_to_end_test.go:517:4: only one cuddle assignment allowed before if statement (wsl)
if expectDeleteSucceeds {
^ …
```
> cleanup: fix linter errors

- htmlui/build.cmd
- install.cmd
- site/content/docs/Installation/_index.md
- tools/install.cmd
This orchestrates building HTMLUI and main binary, only uses built-in shell script and avoids having any dependencies on Unix tools. Latest go and npm are required.
> build: added simple Windows-based build script

- cli/command_snapshot_expire.go
- fs/localfs/local_fs.go
- repo/content/committed_content_index.go
- repo/content/content_manager_lock_free.go
- repo/manifest/manifest_manager.go
- snapshot/manager.go
- snapshot/policy/policy_manager.go
- tools/tools.mk
- Fixes and adds clarifying comments, or comments to exported symbols
- Constants for manifest type label key and snapshot manifest type 
See commit train for details.
> Refactor: misc cleanups

- cli/command_restore.go
- cli/command_snapshot_restore.go
- fs/localfs/copy.go
- snapshot/snapshotfs/restore.go
- tests/end_to_end_test/end_to_end_test.go
Addresses some of the feedback from #144
Allow copying to an existing directory
Remove special handling for the root directory, no longer needed.
Add copy options to control behavior
Allow overwriting an existing file (via options)
Expose copy options as flags
> Change default behavior for localfs.Copy

- fs/localfs/local_fs.go
- tests/end_to_end_test/snapshot_fail_test.go
- tests/testenv/cli_test_env.go
Adding test to probe snapshot failure. Tests snapshot of non-existent source directory, and then iterates through file permissions for files, directories, and issues snapshot to the source. Permission combinations are applied to a parent directory of the source, source itself, contents of source root when the source is a directory, and contents of a subdirectory in that source root.
Fixing kopia executable panic when a directory's contents can't be read. Previously the only Lstat error responded to was not-exist, letting other errors fall through and passing a nil `os.FileInfo` to the following function call, resulting in panic.
> Snapshot failure test and fix kopia panic for non-executable directories

- cli/app.go
- cli/command_server.go
- cli/command_server_start.go
- cli/command_server_tls.go
- cli/server_watchdog.go
- internal/server/server.go
- internal/serverapi/client.go
- tests/end_to_end_test/server_start_test.go
- tests/testenv/cli_test_env.go
Those will make it possible to securely host 'kopia server' embedded
in a desktop app that runs in the background and can access UI.
- added support for using and generating TLS certificates
- added /api/v1/shutdown API to remotely trigger server shutdown
- added support for automatically shutting down server if no requests
arrive in certain amount of time
- added support for generating and printing random password to STDERR
TLS supports 3 modes:
1. serve TLS using externally-provided cert/key PEM files
2. generate & write PEM files, then serve TLS using them
3. generate and use emphemeral cert/key (prints SHA256 fingerprint)
> cli: improvements for 'kopia server' and client

- tests/end_to_end_test/restore_fail_test.go
Add a test that will delete a kopia pack blob, expecting a subsequent restore issued from the snapshot that referenced that blob to fail.
> Add test to induce a failure during a restore using blob delete

- tests/tools/fio/config.go
- tests/tools/fio/fio.go
- tests/tools/fio/fio_test.go
- tests/tools/fio/job.go
- tests/tools/fio/main_test.go
- tests/tools/fio/options.go
- tests/tools/fio/workload.go
- tests/tools/fio/workload_test.go
Adding a helper library that wraps fio execution. This is the basic initial check-in that implements the runners, configs, and a single WriteFiles helper. It should be enough to unblock subsequent tasks that will use fio to generate data sets for kopia snapshot verification. More helper workloads can be added as needed.
In this implementation the tests will all skip from test main if the `FIO_EXE` env variable is not set. Adding fio to the CI environment will be addressed as a separate PR.
Tracking progress in issue https://github.com/kopia/kopia/issues/179
> [robustness testing] Adding library for file generation using 'fio'

- cli/storage_gcs.go
- repo/blob/gcs/gcs_options.go
- repo/blob/gcs/gcs_storage.go
- repo/blob/gcs/gcs_storage_test.go
This enables credentials file to be discarded and makes `kopia repo status -st` fully round-trippable even when the credentials file is gone.
> gcs: added --embed-credentials options which persists --credentials-file as part of Kopia configuration

- app/public/electron.js
- app/public/server.js
This automatically launches Kopia CLI with new flags:
`--tls-generate-cert` which generates in-memory TLS certs for the server
and prints its fingerprint to stderr.
`--random-password` which sets up random basic auth password
KopiaUI will then listen to the stderr messages and parse the cert
fingerprint and password and automatically provide them in the browser
it opens to show the UI.
This ensures that any local process (or script in a browser, etc.)
other than KopiaUI itself won't have access to the server API nor
UI because they won't know the ephemeral random password and won't
be able to intercept it due to TLS protection.
> kopia-ui: UI/API server security (TLS & basic auth)

- CODE_OF_CONDUCT.md
- GOVERNANCE.md
- README.md
This is a proposal for introducing a lightweight governance proposal and a
Code of Conduct for Kopia.
Original Sources of CoC and Governance:
- https://www.contributor-covenant.org/version/2/0/code_of_conduct.html
- http://oss-watch.ac.uk/resources/meritocraticgovernancemodel
No changes to the CoC have been made.
Modulo the source credit, changes specific to the Governance model have been made as a separate patch.
> CoC and Governance Proposal

- internal/serverapi/client.go
Removes the following warning:
```
WARN [runner/nolint] Found unknown linters in //nolint directives: hugeparam
```
> Update nolint directive

- cli/command_index_optimize.go
- repo/content/block_manager_compaction.go
- repo/content/content_manager_test.go
- repo/repository_test.go
- tests/repository_stress_test/repository_stress_test.go
Use `MaxSmallBlobs` instead, it makes it easier to understand the purpose of the parameter.
`MaxSmallBlobs` was not being really used. Replace uses of `MinSmallBlobs` with `MaxSmallBlobs` and remove `MinSmallBlobs`.
> Remove content.CompactOptions.MinSmallBlobs

- go.mod
- go.sum
- tests/testenv/cli_test_env.go
- tests/tools/fswalker/protofile/protofile.go
- tests/tools/fswalker/reporter/reporter.go
- tests/tools/fswalker/reporter/reporter_test.go
- tests/tools/fswalker/walker/walker.go
- tests/tools/fswalker/walker/walker_test.go
Adds a wrapper around `Walk` that takes a Policy (protobuf definition) and performs a walk using it as configuration. The resulting Walk struct pointer is returned. The only exported functionality is unfortunately to read the Policy as a protobuf text file, so the implementation creates a temporary policy file whose lifetime is the duration of the call.
Adds a wrapper around the the FSWalker reporter `Compare` functionality. Takes a config file and two Walk pointers and compares the walks, returning the pb-defined Report struct. Again, the only exported functionality for reading config information is to read it as a protobuf text file. Creates a temporary config file, whose lifetime is the duration of the call, to pass in to the fswalker function.
This PR pertains to #179
> [robustness testing] Adding low-level FSWalker walker/reporter functionality

- repo/content/block_manager_compaction.go
The slice of medium-sized blobs is used to obtain the count of such blobs from the length of the slice, but it is not used otherwise.
> Trivial: Simply count medium-sized index blobs

- Makefile
- tests/tools/fswalker/reporter/reporter.go
- tests/tools/fswalker/reporter/reporter_test.go
- tests/tools/fswalker/walker/walker.go
- tests/tools/fswalker/walker/walker_test.go
Temporary workaround for compile issues on MacOS and Windows due
to upstream fswalker bug. Only build the reporter and walker
packages as GOOS=linux for now.
> Place fswalker packages behind build flag

- .travis.yml
- Makefile
- internal/blobtesting/verify.go
- repo/blob/sharded/sharded.go
- repo/content/committed_content_index_disk_cache.go
- repo/content/content_cache_test.go
- snapshot/snapshot_test.go
fixed some issues that prevented go test from passing on Windows:
- webdav client used \ instead of /
- need retries around mmap.Open()
- paths are prefixed with C:\ on windows
- time.Now() does not always move forward on Windows
> travis: added bare-bones Windows build that does go test

- cli/command_policy_set.go
- cli/command_policy_set_test.go
- cli/command_policy_show.go
- cli/command_snapshot_migrate.go
- snapshot/policy/error_handling_policy.go
- snapshot/policy/error_handling_policy_test.go
- snapshot/policy/policy.go
- snapshot/snapshotfs/upload.go
- snapshot/snapshotfs/upload_test.go
- tests/end_to_end_test/snapshot_fail_test.go
- tests/testenv/cli_test_env.go
Added an error handling policy section. Can independently control error handling for directory and file read errors, toggle-able from the `policy set` command to either "true", "false", or "inherit". If any read error is hit, the error handling will check the effective policy on whether to ignore it or not. Currently there is no differentiation between read error types, though in the future we may want to add the `errors.Is(err, os.ErrPermission)` conditional.
Fix was implemented such that the policy ignores read errors ONLY on child entries of the source. So a snapshot will still fail if the source root directory itself can't be read, but you can ignore the error if a file or a subdirectory in the snapshot source root can't be read. I did this to address some otherwise strange behavior …
> Ignore read errors based on policy settings

- cli/command_policy_show.go
- snapshot/policy/error_handling_policy.go
- snapshot/policy/error_handling_policy_test.go
- snapshot/snapshotfs/upload.go
Fixes print for error handling policy. Previously was printing
pointer address, now dereference pointer to print boolean itself.
Nil check in case the caller passes a policy with nil. In that
case print "false" which is the behavior in uploader for nil
pointer.
Issue was introduced when changing bool pair implementation
to bool pointer from PR suggestions in #207 and uncaught
at the time the swap was made.
before:
```
Error handling policy:
Ignore file read errors:       0xc005f4dbfc       (default)
Ignore directory read errors:  0xc005f4dbfd       (default)
```
after:
```
Error handling policy:
Ignore file read errors:        true       (defined for this target)
Ignore directory read errors:  false       (default)
```
> [minor] Fix error handling policy print

- tests/robustness/checker/comparer.go
- tests/tools/fswalker/fswalker.go
- tests/tools/fswalker/fswalker_test.go
- tests/tools/fswalker/walker/walker.go
Add comparer interface which gathers data on a path and
compares that data to a new path, returning error if the path
differs in any way from the input data. The details of what
constitutes a difference is left to the implementation.
FSWalker implementation uses Walk and Report to do the data
gathering and comparison. Filters are applied to sort out any
modifications that might be expected (e.g. ctime, atime, mtime,
rename of root directory after restore) from the report.
> Add comparer interface and fswalker implementation

- tests/tools/fswalker/walker/walker.go
- tests/tools/fswalker/walker/walker_test.go
Add the walk policy flag WalkCrossDevice to the fswalker Walk calls. This will avoid potential issues when running in a docker container where a FS tree is made of many overlays. Without the flag set, the Walk operation skips over files on devices that do not match the device at the base path.
> Add WalkCrossDevice option to walk policy

- tests/end_to_end_test/main_test.go
- tests/testenv/cli_test_env.go
Reduces name lengths by ~ 1/2.
Motivation: address failures observed in e2e tests in Windows.
> Generate shorter file names, and thus paths, in E2E tests

- tools/tools.mk
Verified with:
make website PATH="/tmp/With Space:$PATH"
> makefile: fixed support for PATH that includes directories with spaces

- .travis.yml
Removes warnings in Travis v2 config validation:
> root: duplicate key: addons
deploy: deprecated key skip_cleanup (not supported in dpl v2, use cleanup)
deploy: deprecated key skip_cleanup (not supported in dpl v2, use cleanup)
addons.snaps: unknown key confinement (classic)
deploy: key github_token is an alias for token, using token
deploy: key api_key is an alias for token, using token
Changes:
- remove duplicate `addons` key
- replace `github_token` with `token` in `deploy.provider:"pages"`
- replace api_key with `token` in `deploy.provider:"release"`
- replace `skip_cleanup:true` with `cleanup:false` in `deploy.provider.*`
Ref:
- https://docs.travis-ci.com/user/deployment-v2/providers/pages/
- https://docs.travis-ci.com/user/deployment-v2/providers/releases/
- …
> Cleanup Travis config

- Makefile
Fixing a typo in the Makefile target upload-coverage. Without fix, the target it is not found if Travis is running against a PR.
> Fix typo in makefile so CI can pass (upload-coverage target)

- tests/testenv/cli_test_env.go
Error variable `err` was being shared between `c.Output` and `ioutil.ReadAll` in separate goroutines. The two could race to set `err`, and if `Output` finishes first with an error, `ReadAll` could overwrite it with nil. Fix is to delegate an independent error for the pipe read, and fail the test if it is non-nil.
Should fix the flake mentioned in #284. Test performance improvements will be added separately.
> [flake] Fix error clobbering race condition in kopia cli test runner

- cli/command_benchmark_crypto.go
- cli/command_repository_create.go
- go.mod
- go.sum
- internal/server/api_repo.go
- repo/content/content_formatter_test.go
- repo/encryption/aead_helpers.go
- repo/encryption/aes256_gcm_hmac_sha256_encryptor.go
- repo/encryption/chacha20_poly1305_hmac_sha256_encryptor.go
- repo/encryption/deprecated_ctr_encryptor.go
- repo/encryption/deprecated_salsa_encryptor.go
- repo/encryption/encryption.go
- repo/encryption/encryption_test.go
- repo/encryption/null_encryptor.go
New ciphers are using authenticated encryption with associated data
(AEAD) and per-content key derived using HMAC-SHA256:
* `AES256-GCM-HMAC-SHA256`
* `CHACHA20-POLY1305-HMAC-SHA256`
They support content IDs of arbitrary length and are quite fast:
On my 2019 MBP:
```
- BLAKE2B-256 + AES256-GCM-HMAC-SHA256 - 648.7 MiB / second
- BLAKE2B-256 + CHACHA20-POLY1305-HMAC-SHA256 - 597.1 MiB / second
- HMAC-SHA256 + AES256-GCM-HMAC-SHA256 351 MiB / second
- HMAC-SHA256 + CHACHA20-POLY1305-HMAC-SHA256 316.2 MiB / second
```
Previous ciphers had several subtle issues:
* `SALSA20` encryption, used weak nonce (64 bit prefix of content ID),
which means that for any two contents, whose IDs that have the same
64-bit prefix, their plaintext can be decoded from the ciphertext
alone.
* …
> crypto: deprecated crypto algorithms and replaced with better alternatives

- tests/testenv/cli_test_env.go
Give a `*bytes.Buffer` to the Command and let `package exec` read from the pipe into the buffer for us.
The current use of the `StderrPipe()` method is problematic; the documentation for os/exec states:
> Wait will close the pipe after seeing the command exit, so most callers need not close the pipe themselves. It is thus incorrect to call Wait before all reads from the pipe have completed. For the same reason, it is incorrect to use Run when using StderrPipe.
This should solve flake behavior seen in end to end testing, even following #285, which exposed the above problem.
> Use bytes buffer to capture stderr instead of reading pipe

- Makefile
- tests/tools/fio/fio.go
- tests/tools/fio/fio_test.go
- tests/tools/fio/main_test.go
- tests/tools/fio/options.go
- tests/tools/fio/workload.go
- tests/tools/fio/workload_test.go
- tests/tools/fio_docker/Dockerfile
Update the fio runner to use a docker image if the appropriate environment variable is set. Docker image is built via a makefile target and used in the robustness tool tests. The image uses `fio` as an entrypoint, so from the standpoint of the fio runner package implementation, it behaves similarly to a local executable fio.
This is a replacement implementation for #208, which I will close shortly.
> Use docker to execute fio in robustness tool

- cli/cli_progress.go
- cli/command_repository_connect.go
- cli/command_snapshot_migrate.go
- tests/end_to_end_test/snapshot_migrate_test.go
- cleaned up migration progress output
- fixed migration idempotency
- added migration of policies
- renamed --parallelism to --parallel
- improved e2e test
- do not prompt for password to source repository if persisted
> cli: 'snapshot migrate' improvements to help with data migration

- Makefile
- internal/faketime/faketime.go
- internal/faketime/faketime_test.go
- internal/repotesting/repotesting_test.go
- repo/blob/azure/azure_storage.go
- repo/blob/filesystem/filesystem_storage.go
- repo/blob/gcs/gcs_storage.go
- repo/content/block_manager_compaction.go
- repo/content/committed_content_index_disk_cache.go
- repo/content/content_cache.go
- repo/content/content_manager.go
- repo/content/content_manager_test.go
- repo/content/list_cache.go
- repo/manifest/manifest_manager.go
- repo/manifest/manifest_manager_test.go
- repo/open.go
- repo/repository.go
- snapshot/gc/gc.go
- snapshot/policy/retention_policy.go
- snapshot/snapshotfs/all_sources.go
- snapshot/snapshotfs/source_directories.go
- snapshot/snapshotfs/source_snapshots.go
- snapshot/snapshotfs/upload.go
- tests/stress_test/stress_test.go
Motivation: Allow time injection for (unit) tests, to more easily test and verify time-dependent invariants.
Add time injection support for:
- `repo.Manager`
- `manifest.Manager`
- `snapshot.Uploader`
Then, wire up to these components. The `content.Manager` already had support for time injection, but was not wired up from the time function passed to repo creation.
Add an `internal/faketime` package for testing. Mainly code movement from testing code in the `repo/content` package. Motivation: make it available to other packages outside content
Also, add simple tests for `faketime` functions.
> Inject time in Kopia components

- tests/robustness/snap/snap.go
- tests/tools/kopiarunner/kopia_snapshotter.go
- tests/tools/kopiarunner/kopiarun.go
- tests/tools/kopiarunner/kopiarun_test.go
Snapshotter interface describes an entity that can create,
restore, and delete snapshots, as well as manage a repository.
Add kopia implementation of the snapshotter interface.
> Add snapshotter interface and kopia implementation

- Makefile
- cli/command_blob_show.go
- cli/command_show.go
- cli/command_snapshot_verify.go
- cli/show_utils.go
- internal/diff/diff.go
- internal/fshasher/fshasher.go
- internal/iocopy/copy.go
- internal/server/htmlui_fallback.go
- repo/blob/azure/azure_storage.go
- repo/blob/gcs/gcs_storage.go
- repo/compression/compressor_gzip.go
- repo/compression/compressor_pgzip.go
- repo/compression/compressor_s2.go
- repo/compression/compressor_zstd.go
- tests/testenv/cli_test_env.go
this pools copy buffers so they can be reused instead of throwing away after each io.Copy()
> performance: added wrapper around io.Copy()

- cli/command_snapshot_create.go
- repo/content/content_manager.go
- repo/content/content_manager_lock_free.go
- repo/content/stats.go
- snapshot/snapshotfs/upload.go
Ensures that the stats are read and reset using atomic primitives as well
> Refactor content stats

- cli/command_blob_gc.go
- cli/command_content_list.go
- cli/command_snapshot_gc.go
- internal/stats/countsum.go
- snapshot/gc/gc.go
- snapshot/gc/stats.go
No functional changes.
Add helpers to improve code readability in the CLI commands that collect stats, and leverage those in the `blob gc`, `content list` and `snapshot gc` commands.
Also, minor refactoring in the snapshot/gc.Run function to improve readability. No functional changes.
> Refactor CLI stats

- cli/command_benchmark_crypto.go
non-optimized (0.5.0)
0. BLAKE2B-256-128      AES256-GCM-HMAC-SHA256 644.9 MiB / second
before this change:
0. BLAKE2B-256-128      AES256-GCM-HMAC-SHA256 655.9 MiB / second
after (this change):
0. BLAKE2B-256-128      AES256-GCM-HMAC-SHA256 781.5 MiB / second
> cli: pre-allocated buffers for crypto benchmark

- cli/command_benchmark_compression.go
- repo/compression/compressor.go
- repo/compression/compressor_gzip.go
- repo/compression/compressor_pgzip.go
- repo/compression/compressor_s2.go
- repo/compression/compressor_test.go
- repo/compression/compressor_zstd.go
- repo/object/object_manager.go
- repo/object/object_writer.go
- repo/splitter/splitter.go
- repo/splitter/splitter_buzhash32.go
- repo/splitter/splitter_fixed.go
- repo/splitter/splitter_pool.go
- repo/splitter/splitter_rabinkarp64.go
- added pooled splitters and ability to reset them without having to recreate
- added support for caller-provided compressor output to be able to pool it
- added pooling of compressor instances, since those are costly
> performance: improvements to object manager

- repo/content/content_manager_lock_free.go
- tests/end_to_end_test/all_formats_test.go
Quick fix for the issue found in 0.5.0 where hash algorithms that are not 128-bits cause corrupted index blobs (`n`) and repository will fail to open:
```
$ export KOPIA_PASSWORD=foo
$ rm -rf /tmp/kopia-repo
$ mkdir /tmp/kopia-repo
$ kopia-0.5.0 repo create filesystem --path /tmp/kopia-repo --block-hash=HMAC-SHA256
$ kopia-0.5.0 snapshot create ~/Projects/Kopia/repo
$ kopia-0.5.0 policy list
$ kopia-0.5.0 snapshot list
$ kopia-0.5.0 repo disconnect
$ kopia-0.5.0 repo connect filesystem --path /tmp/kopia-repo
```
1. Remove all `n` blobs from the storage. For example in case of the filesystem use `$ rm -rf /tmp/kopia-repo/n*`
2. The repository will connect now, we need to recover all indexes from pack blobs:
```
$ kopia-0.5.1 repo connect filesystem --path /tmp/kopia-repo
$ kopia-0.5.1 …
```
> Kopia 0.5.1 hotfix release

- tests/robustness/snapmeta/kopia_meta.go
- tests/robustness/snapmeta/simple.go
- tests/robustness/snapmeta/snapmeta.go
Add an implementation of the metadata store using Kopia snapshots and restores to manage persistence of walk metadata. Metadata are stored to and retrieved from the store, and a mechanism for persisting the store is implemented using Kopia snapshots.
> [robustness testing] Implement metadata store for test metadata using kopia

- repo/content/content_index_recovery_test.go
- repo/content/content_manager_test.go
Note this uses new golang 1.14 feature t.Cleanup(), so the tests won't work with 1.13 anymore.
> testing: ensure cleanup of content managers, fixes #356

- repo/content/content_manager.go
after finishing flushing, fixes timeouts on Travis
This started randomly failing on Travis after we switched to golang 1.14. Could it be that because of pre-emption changes we uncovered the bug that was previously being masked?
> content: added missing condition variable broadcast

- Makefile
- internal/buf/pool.go
- internal/buf/pool_metrics.go
- internal/buf/pool_test.go
- repo/content/content_manager.go
- repo/content/content_manager_lock_free.go
- repo/object/object_manager.go
- repo/object/object_writer.go
- repo/repository.go
- tests/stress_test/stress_test.go
content manager:
Previously we would store special field Payload for contents
that were added but never flushed to the store and it was not
encrypted. This required special handling different for pending
vs flushed contents.
This change maintains pending pack buffer ready to be flushed
and appends encrypted contents to it, which avoids data copying.
The buffers are pooled to avoid allocations.
This change also introduces 'buf.Pool', which allows efficient management of ephemeral in-memory buffer using multiple buffers.
```
10 GB: 10 dirs x 10 files x 100 mb each:
before: time=50.152      cpu=372.200      memory=824.699     vmem=5841.207
after:  time=45.133      cpu=200.400      memory=725.645     vmem=5659.527
10 GB: 10 dirs x 10000 files x 100 kb each:
before: time=43.130 …
```
> performance: introduced buf.Pool which helps reuse memory buffers

- cli/storage_s3.go
- repo/blob/s3/s3_options.go
- repo/blob/s3/s3_storage.go
- repo/blob/s3/s3_storage_test.go
Introduce a new CLI option for the kopia command. 
"kopia repistory connect s3 --bucket=`<bucket name>` --disable-tls-verification". 
This new option disables tls verification. 
Testing:
1. Manual tests for connecting to an s3 bucket worked. Snapshot creates, snapshot list, snapshot content commands worked.
2. Updated unit tests.
```
% kopia repository connect s3 --bucket=onkar-kopia-s3-bucket --disable-tls-verification
Enter password to open repository: 
Connected to repository.
NOTICE: Kopia will check for updates on GitHub every 7 days, starting 24 hours after first use.
To disable this behavior, set environment variable KOPIA_CHECK_FOR_UPDATES=false
Alternatively you can remove the file "/Users/onkarbhat/Library/Application Support/kopia/repository.config.update-info.json".
```
```
% …
```
> Add CLI option for disabling tls verification while connecting to s3

- cli/command_snapshot_create.go
- tests/end_to_end_test/snapshot_create_test.go
This PR introduces two new arguments `--start-time` and `--end-time` to the `kopia snapshot create' command` to override the start time and end the end time that the snapshot is created.
If the start time is specified but no end time is, then the end time will be set to the start time so it doesn't look like a backup ran for (potentially) years and vice-versa for end time specified without a start time.
Fixes #354
> cli: allow override of snapshot start time and end time

- repo/connect.go
- repo/open.go
this allows config directory to be (partially) portable
Improves #368
> repo: persist relative path to cache if possible

- cli/command_policy_set.go
Fix panic in #385. Only one error type is currently being checked, `policy.ErrPolicyNotFound`. Other errors are allowing execution to continue with the policy set to nil. Instead the error should be returned.
> Policy set: fix nil pointer dereference #385

- internal/repotesting/repotesting.go
- snapshot/policy/policy_manager.go
- snapshot/policy/policy_manager_test.go
> policy: deduplicate multiple policies for the same source

- Makefile
- cli/command_repository_repair.go
- internal/blobtesting/concurrent.go
- internal/blobtesting/faulty.go
- internal/blobtesting/map.go
- internal/blobtesting/verify.go
- internal/gather/gather_bytes.go
- internal/gather/gather_bytes_test.go
- internal/gather/gather_write_buffer.go
- internal/gather/gather_write_buffer_chunk.go
- internal/gather/gather_write_buffer_chunk_test.go
- internal/gather/gather_write_buffer_test.go
- repo/blob/azure/azure_storage.go
- repo/blob/filesystem/filesystem_storage.go
- repo/blob/filesystem/filesystem_storage_test.go
- repo/blob/gcs/gcs_storage.go
- repo/blob/logging/logging_storage.go
- repo/blob/s3/s3_storage.go
- repo/blob/sftp/sftp_storage.go
- repo/blob/sharded/sharded.go
- repo/blob/storage.go
- repo/blob/storage_test.go
- repo/blob/webdav/webdav_storage.go
- repo/content/content_cache.go
- repo/content/content_cache_test.go
- repo/content/content_index_recovery.go
- repo/content/content_manager.go
- repo/content/content_manager_lock_free.go
- repo/format_block.go
- repo/format_block_test.go
This amortizes memory allocations when assembling content packs.
This PR only optimizes code paths critical to snapshot creations.
> Support for gather writes, where blob.Storage.PutBlob gets a list of slices and writes them sequentially

- tools/tools.mk
Instead of taking timestamp + TRAVIS_BUILD_NUMBER at build time,
we take the time of the commit, to be deterministic. This requires
a little bit of makefile magic to strip leading zeroes to make the
version number that's semver compliant.
This only affects post-submit non-tag builds.
This will allow coordinating the build between different CI tools,
so that Windows can be built on AppVeyor and macOS/Linux on Travis CI.
> Makefile: changed how build number is calculated

- repo/content/content_cache.go
- repo/content/content_cache_test.go
- repo/content/content_manager.go
- repo/content/content_manager_lock_free.go
With large cache sizes it takes several seconds to perform the initial
sweep. This change only checks that the cache is functional without
full sweep.
Also cleaned up contentCache by introducing interface and having
two implementations - one which does caching, and one that does not.
> content: asynchronous cache sweep

- repo/object/object_manager_test.go
- repo/object/object_writer.go
When prefix is not specified on ObjectWriter, we force
'x' content prefix on intermediate contents, so object IDs
will look like:
Ix{hash}
This ensures the index contents will be stored in `q` blobs,
making `snapshot gc` easier.
> object: ensure that all I objects have a content prefix

- repo/blob/filesystem/filesystem_storage.go
- repo/blob/filesystem/filesystem_storage_test.go
Ran TestFileStorageConcurrency 1000 times and it passed on macOS.
Fixes #299
> filesystem: added retry which addresses the macOS race condition

- cli/command_cache_sync.go
- repo/content/content_cache.go
- repo/content/content_cache_base.go
- repo/content/content_cache_data.go
- repo/content/content_cache_metadata.go
- repo/content/content_cache_passthrough.go
- repo/content/content_cache_test.go
- repo/content/content_manager.go
- repo/content/content_manager_lock_free.go
Unlike regular cache, which caches segments of blobs on a per-content
basis, metadata cache will fetch and store the entire metadata blob (q)
when any of the contents in it is accessed.
Given that there are relatively few metadata blobs compared to data (p)
blobs, this will reduce the traffic to the underlying store and improve
performance of Snapshot GC which only relies on metadata contents.
> content: added blob-level metadata cache

- app/public/config.js
- app/public/electron.js
- create default config in portable mode
- override userData to make sure cached data is written outside of %APPDATA%
Fixes #428
> app: portability fixes

- internal/blobtesting/eventually_consistent.go
- repo/blob/storage.go
- tests/stress_test/stress_test.go
This is done by introducing N unsynchronized caches, which simulate
what frontend of a cloud storage system might do, what causes eventual
consistency behavior.
Testing for #326
> testing: added blob.Storage wrapper that simulates eventual consistency

- cli/command_snapshot_delete.go
- snapshot/manager.go
- tests/end_to_end_test/snapshot_delete_test.go
- tests/tools/kopiarunner/kopia_snapshotter.go
New usage:
```
kopia snapshot delete manifestID... [--delete]
kopia snapshot delete rootObjectID... [--delete]
```
Fixes #435
> cli: improved 'snapshot delete' usage

- go.mod
- go.sum
Change log:
https://github.com/klauspost/compress/releases
Upgrade github.com/klauspost/pgzip to 1.2.4 from 1.2.1
Change log:
https://github.com/klauspost/pgzip/releases
> deps: Upgrade compress package to 1.10.5

- go.mod
- go.sum
From version 1.28.13 to 1.31.1
Change log:
https://github.com/aws/aws-sdk-go/releases
Also upgrade github.com/stretchr/testify to 1.5.1 from 1.4.0
https://github.com/stretchr/testify/releases
> Upgrade AWS SDK to 1.31.1

- tests/robustness/checker/checker.go
Connect the snapshotter, the storer, and the comparer. Invoke
the snapshotter to take/restore/delete snapshots on the repo,
the comparer to gather metadata before the snapshot and
after the restore, and the storer to save metadata for later
lookup when verifying restores.
Added a design write-up to the umbrella issue #179. Will add
updates there as each component is staged for merge.
> [robustness testing] Wire up snapshot-store-compare behavior

- repo/content/content_index_recovery_test.go
- repo/content/content_manager_test.go
Reverts 06fbaba
Re-applies "testing: ensure cleanup of content managers" commit
> Fix #360: Leverage Go 1.14 testing.T.Cleanup()

- repo/content/content_index_recovery_test.go
- repo/content/content_manager_test.go
Pulled the trigger too soon.
Reverts kopia/kopia#455
> Revert "Fix #360: Leverage Go 1.14 testing.T.Cleanup()"

- cli/app.go
- cli/cli_progress.go
- run maintenance even if the command is about to return an error
(otherwise if folks have persistent error causing snapshots to fail
they will never run maintenance)
- disable progress output after snapshotting so that
'kopia snapshot --all' output is clean
> cosmetic changes to maintenance behavior

- internal/server/server.go
- repo/api_server_repository.go
- tests/end_to_end_test/api_server_repository_test.go
Added test that verifies that when client performs Flush (which happens
at the end of each snapshot and when repository is closed), the
server writes new blobs to the storage.
Fixes #464
> server: implemented 'flush' and 'refresh' API

- tests/robustness/snapmeta/snapmeta.go
- tests/robustness/test_engine/engine.go
- tests/robustness/test_engine/engine_test.go
Test engine manages the test and metadata repositories, snapshot
checker, metadata storage persistence, and file writer. It is
the high level helper that will be invoked in the snapshot
verification testing suite.
- modify data directory file structure
- issue snapshot/restore/delete to the data directory
- accumulate metadata over the course of the test suite
- flush accumulated metadata to the metadata repository
- load historical metadata from the repository on initialization
- perform automatic data integrity verification on snap restore
This change corresponds to the robustness execution engine component from the design documentation (https://github.com/kopia/kopia/issues/179).
> [Robustness] Add test engine to manage snapshot verification testing

- tests/robustness/main_test.go
- tests/robustness/robustness_test.go
- tests/tools/fswalker/fswalker.go
- tests/tools/fswalker/fswalker_test.go
Add two tests:
- TestManySmallFiles: writes 100k files size 4k to a directory. Snapshots the data tree, restores and validates data.
- TestModifyWorkload: Loops over a simple randomized workload. Performs a series of random file writes to some random sub-directories, then takes a snapshot of the data tree. All snapshots taken during this test are restore-verified at the end.
A global test engine is instantiated in main_test.go, to be used in the robustness test suite across tests (saves time loading/saving metadata once per run instead of per test).
Updated https://github.com/kopia/kopia/issues/179 - simple test cases
> [Robustness] Add first robustness tests

- app/Makefile
- app/env.sh
- app/package-lock.json
- app/package.json
- tools/tools.mk
KOPIA_VERSION will now always be v-prefixed and we will strip the
prefix before embedding it in KopiaUI manifest.
Also upgraded Node and app NPM dependencies to latest versions.
> switched back to using v-prefixed tag names

- .travis.yml
- Makefile
- internal/faketime/faketime.go
- internal/stats/countsum_mutex.go
- repo/content/content_cache_base.go
- repo/content/content_manager.go
- repo/content/content_manager_lock_free.go
- repo/object/object_manager_test.go
- snapshot/snapshotfs/upload.go
- tests/end_to_end_test/server_start_test.go
- tests/robustness/main_test.go
- tests/robustness/robustness_test.go
- tests/robustness/test_engine/engine.go
- tests/robustness/test_engine/engine_test.go
- tests/tools/fswalker/fswalker.go
- tests/tools/fswalker/fswalker_test.go
- tests/tools/fswalker/reporter/reporter.go
- tests/tools/fswalker/reporter/reporter_test.go
- tests/tools/fswalker/walker/walker.go
- tests/tools/fswalker/walker/walker_test.go
- tools/tools.mk
Fixed atomic alignment problems on ARMv7 mentioned in #505 
Now it's possible to build and run tests on both `armv7` and `armv8` a.k.a. `arm64` a.k.a. `aarch64`. The following are working:
```
$ make
$ make install-noui
$ make install
$ make test
$ make lint
$ make integration-test
$ make travis-setup
$ make travis-release
```
Building `site` does not work due to lack of appropriate Hugo build for ARM.
Determining whether it makes sense to build `kopia-ui` on ARM is TBD, but will certainly be interesting when new arm macbooks arrive.
Tested on 2 machines:
Raspberry PI 4 with 4 GB RAM on Ubuntu 20.04 LTS in 64-bit mode (aarch64)
Raspberry PI 4 with 2 GB RAM on Raspbian GNU/Linux 10 (buster) with 2GB RAM in 32-bit mode (armv7l)
> Fixed arm and arm64 build.

- cli/auto_upgrade.go
- cli/command_repository_create.go
- cli/command_server_start.go
- cli/command_snapshot_create.go
- repo/maintenance/maintenance_params.go
On first 'kopia snapshot' or 'kopia server' use where the 'maintenance' manifest cannot be found, we create a default one and display usage note.
> cli: auto-upgrade the repository to 0.6.0

- snapshot/restore/local_fs_output.go
Proposed fix for #516: Do not attempt to call `os.Chown` on Windows. The
command is unsupported on windows and will always return
`syscall.EWINDOWS`.
Handling for user ID and group ID on Windows already hardcodes
both values to zero. If a snapshot is restored with non-zero UID/GID
values (for instance if the snapshot was created on a different OS),
filesystem entries will be restored without changing UID/GID, resulting
in a state similar to how they would look if the snapshot was
taken on Windows in the first place.
> Fix #516 - Chown not suported on Windows

- cli/command_policy_remove.go
- go.mod
- snapshot/policy/policy_manager.go
- snapshot/policy/policy_manager_test.go
- snapshot/policy/policy_tree_test.go
> Fix for policy manager not setting labels in some cases

- site/content/docs/Features/_index.md
This makes the link render correctly.
It looks like this on the site presently, at https://kopia.io/docs/features/:
> <img width="667" alt="image" src="https://user-images.githubusercontent.com/19393950/89705076-fcaa2500-d90e-11ea-8c8d-9244d5e3f97b.png">
> fix typo in url

- cli/command_repository_sync.go
- cli/storage_providers.go
- go.sum
- internal/blobtesting/eventually_consistent.go
- internal/blobtesting/faulty.go
- internal/blobtesting/map.go
- repo/blob/azure/azure_storage.go
- repo/blob/b2/b2_storage.go
- repo/blob/filesystem/filesystem_storage.go
- repo/blob/gcs/gcs_storage.go
- repo/blob/logging/logging_storage.go
- repo/blob/s3/s3_storage.go
- repo/blob/sftp/sftp_storage.go
- repo/blob/storage.go
- repo/blob/webdav/webdav_storage.go
- tests/end_to_end_test/repository_sync_test.go
- tests/end_to_end_test/snapshot_create_test.go
This implements incremental sync from current repository to another repository location. Transfers missing and outdated blobs atomically leveraging existing blob storage provider.
Usage demo: https://asciinema.org/a/352299
Fixes #509
> Support for repository sync

- repo/open.go
- snapshot/snapshotfs/upload.go
- tests/end_to_end_test/snapshot_create_test.go
This creates a marker file ".kopia-cache" in the directory that's the root of cache. When uploader sees the file it will treat the entire directory as empty.
This allows entire home directory or root to be backed up more easily.
> upload: auto-ignore kopia cache directories when creating snapshots

- tests/tools/fswalker/fswalker.go
Fix fswalker to ignore hostname to allow reporting on walks done across different hosts. Also prevent Before and After walk data from printing to reduce log size.
> [Robustness] Fswalker should ignore host name

- cli/app.go
- cli/command_index_inspect.go
- cli/command_repository_connect.go
- cli/command_repository_status.go
- repo/api_server_repository.go
- repo/blob/readonly/readonly_storage.go
- repo/connect.go
- repo/content/content_manager_indexes.go
- repo/local_config.go
- repo/open.go
- repo/repository.go
- Option to connect to repository in a read-only mode which prevents any mutations.
- Option to dump contents of a particular index blob.
> Tools to help investigate repository structures safely

- site/content/docs/Repositories/_index.md
Fix command line: "create" instead of "connect"
> Doc: fix create B2 repository cmd

- repo/initialize.go
I noticed that the `buildVersion` field of the formatBlob is actually left empty.
From a test repo created with the official `v0.6.3` github binary of kopia:
```
{
"tool": "https://github.com/kopia/kopia",
"buildVersion": "",
"buildInfo": "c142598351399336b82bdbe64c687e63d2775788",
"uniqueID": "fIaHmFEp4HZEJgu1w1aKVTAwpZnFn574uBwuy5uBE4A=",
"keyAlgo": "scrypt-65536-8-1",
"version": "1",
"encryption": "AES256_GCM",
"encryptedBlockFormat": "..."
}
```
Looks like `BuildVersion` was missing during repo initialization, which I guess was not on purpose.
> Set BuildVersion during repo initialization.

- tools/apt-publish.sh
Ubuntu on amd64 is sometimes confused and tries downloading i386 anyway
> apt-publish: publish dummy i386 release

- repo/content/content_manager_indexes.go
- repo/content/content_manager_test.go
- repo/content/index.go
The problem was that while dropping deleted entries from the index
we were looking at index-local and not merged result.
Say index1 has content1 created at t0.
Say index2 has content1 deleted at t1 > t0.
And we're compacting and dropping index entries deleted before t2,
such that t2 > t1.
Because create and delete records are in separate index files, the
compacted file would preserve "created t0" which is wrong.
This fix changes index compaction to always look at resolved content
status.
Fixes #483 (hopefully)
> content: fixed index compaction that would resurrect content entry during full maintenance

- cli/command_server.go
> cli: plumbed through missing --server-cert-fingerprint option

- repo/splitter/splitter_buzhash32.go
- repo/splitter/splitter_rabinkarp64.go
- repo/splitter/splitter_test.go
We did not properly reset the splitter state for buzhash32 and
rabinkarp64, so object writer did not achieve perfect deduplication.
Fixes #595
> object: fixed splitter reset on reuse

- cli/command_benchmark_splitters.go
- repo/object/object_writer.go
- repo/splitter/splitter.go
- repo/splitter/splitter_buzhash32.go
- repo/splitter/splitter_fixed.go
- repo/splitter/splitter_rabinkarp64.go
- repo/splitter/splitter_test.go
Refactored inner loop inside object writer that performs splitting to feed the splitter the slice of bytes instead of byte-by-byte. 
Splitter now implements `NextSplitPoint(b)` which determines the location of the next split point in the given slice and returns value `n` between `1..len(b)` if the split point happens AFTER byte n. If there is no split point, the splitter returns -1. This allows the splitter to perform internal optimizations which are pretty significant.
Using `kopia benchmark splitter`
`BUZHASH` went from ~3.4s to ~2.4s (~40% throughput improvement)
`RABINKARP` went from ~8.2s to ~7s (~20% throughput improvement)
`FIXED` become free now
```
0. FIXED-2M                    1390 ms count:256 min:2097152 10th:2097152 25th:2097152 50th:2097152 75th:2097152 90th:2097152 …
```
> Splitter throughput improvements

- repo/object/object_manager.go
- repo/object/object_manager_test.go
- repo/object/object_writer.go
This is primarily to facilitate efficient parallel uploads of very large files (>1GB). Due to bottleneck of splitting which is inherently sequential, we can only one use CPU core for each Writer, which limits throughput.
> object: implemented fast concatenation of objects

- site/content/_index.html
- site/content/docs/Installation/_index.md
Emphasized the use of package managers to download and keep Kopia up-to-date.
Added instructions for using Scoop on Windows.
> site: edited installation page and switched Download link to point at it

- cli/app.go
- cli/command_blob_delete.go
- cli/command_blob_gc.go
- cli/command_content_rewrite.go
- cli/command_content_rm.go
- cli/command_index_optimize.go
- cli/command_index_recover.go
- cli/command_manifest_rm.go
- cli/command_snapshot_gc.go
- tests/testenv/cli_test_env.go
This prints an error when a dangerous command is used without
first setting KOPIA_ADVANCED_COMMANDS=enabled environment variable.
> cli: ensure advanced commands are not accidentally used

- .gitignore
- Makefile
- tests/perf_benchmark/perf-benchmark-setup.sh
- tests/perf_benchmark/perf-benchmark.sh
- tests/perf_benchmark/process_results.go
The benchmarks creates 20 GB of files in different configurations
* 10 x 2 GB files
* 100 x 200 MB files
* 1000 x 20 MB files
and backs them up to a local filesystem repository measuring latency, CPU and RAM usage plus repository size.
The script also creates both compressed (s2-default) and uncompressed repositories.
The benchmarking script uses GCP instance (n1-standard-8) with fast NVME
flash to eliminate local filesystem latency.
Current performance numbers show major improvement in latency in
0.7.0-rc1 due to splitter throughput optimization (#606).
See current numbers in https://docs.google.com/spreadsheets/d/1ExNZuYiXgz7CSR65M8Uk6ELk78NsOv6uusuqzW1lS-Q/edit#gid=0
> testing: added performance benchmark

- internal/logfile/logfile.go
- repo/content/committed_content_index.go
- repo/content/content_manager.go
- repo/content/content_manager_indexes.go
- repo/content/content_manager_lock_free.go
- repo/content/content_manager_own_writes.go
- repo/content/index_blob_manager.go
- repo/content/list_cache.go
- tests/testenv/cli_test_env.go
Logs from the content manager (except reads) are sent to separate log
file that is always free from personally-identifiable information
(e.g. no file names, just content IDs and blob IDs).
Also moved CLI logs to a subdirectory (`cli-logs`) and put content logs
in a parallel directory (`content-logs`) with separate retention rules.
Also, the log file name will now include the type of the command that
was invoked:
kopia-20200913-134157-16110-snapshot-create.log
Fixes #588
> logging: revamped logs from content manager to be machine parseable

- cli/cli_progress.go
- htmlui/src/SourcesTable.js
- snapshot/snapshotfs/upload.go
- snapshot/snapshotfs/upload_progress.go
- snapshot/snapshotfs/upload_scan.go
- snapshot/snapshotfs/upload_test.go
This allows better progress indicator in the CLI and UI.
The percentage completed is not displayed until estimate is available.
Quick demo: https://asciinema.org/a/O7ktcWSgaGUPfJwhzc65mMWM1
Fixes #514
> upload: scan the directory to be uploaded in parallel to estimate the amount of data to be uploaded

- tests/tools/kopiarunner/kopia_snapshotter.go
- tests/tools/kopiarunner/kopia_snapshotter_exe_test.go
- tests/tools/kopiarunner/kopia_snapshotter_test.go
Add flags for:
- no-progress
- parallel
- cache sizes
- no update check
Add an integration test to validate snapshotter expected output
against a kopia executable.
Add GC command, and sanity checks on finding snapshot ID from lists.
> [Robustness] Add command line parameters for kopia snapshotter

- repo/blob/rclone/rclone_storage_test.go
- repo/blob/webdav/webdav_storage.go
The race is described in https://github.com/studio-b12/gowebdav/issues/36
We need this workaround until the fix is merged upstream, to avoid maintaining a webdav client fork.
Fixes #624
> webdav: work around client race condition

- .gitattributes
Add .gitattributes entry for Makefiles
Update .gitattributes for Go files:
- Mark go source files as text, with LF line ending.
- Set git diff language mode for `*.go` files to `golang`
- Add attributes for `go.sum`
> Trivial: update git attributes for Makefile

- go.mod
- go.sum
- repo/hashing/blake3_hashes.go
Hash info at https://github.com/BLAKE3-team/BLAKE3
Uses https://github.com/zeebo/blake3 optimized implementation
Micro benchmarks show ~2X speedup for hashing+encryption.
- Caveat: not fully controlled environment, etc.
```
Hash                 Encryption           Throughput
-----------------------------------------------------------------
0. BLAKE3-256           AES256-GCM-HMAC-SHA256 1.3 GiB / second
1. BLAKE3-256-128       AES256-GCM-HMAC-SHA256 1.3 GiB / second
2. BLAKE3-256-128       CHACHA20-POLY1305-HMAC-SHA256 1 GiB / second
3. BLAKE3-256           CHACHA20-POLY1305-HMAC-SHA256 1 GiB / second
4. BLAKE2B-256-128      AES256-GCM-HMAC-SHA256 641.5 MiB / second
5. BLAKE2B-256          AES256-GCM-HMAC-SHA256 621.7 MiB / second
6. BLAKE2B-256-128      CHACHA20-POLY1305-HMAC-SHA256 …
```
> Add support for Blake3 hashing

- internal/server/api_sources.go
- internal/server/source_manager.go
- tests/end_to_end_test/server_start_test.go
- tests/testenv/cli_test_env.go
As reported on the forum:
https://kopia.discourse.group/t/kopia-0-7-0-not-backing-up-any-files-repro-needed/136
The root cause was that source manager was inheriting HTTP call context of the 'connect' API call and holding onto it.
This context was closed after the 'connect' RPC returned thus silently killing all uploads.
> Repro and fix for zero-sized snapshot bug

- cli/command_ls.go
- cli/command_snapshot_list.go
- fs/entry.go
- fs/localfs/local_fs.go
- internal/mockfs/mockfs.go
- snapshot/snapshotfs/all_sources.go
- snapshot/snapshotfs/repofs.go
- snapshot/snapshotfs/source_directories.go
- snapshot/snapshotfs/source_snapshots.go
Can be disabled with `--no-error-summary`.
Quick demo: https://asciinema.org/a/2rma0sx2mD6HoIPy6VL0QEFeP
Also refactored fs.Directory to provide Summary optionally.
Fixes #642
> cli: When listing directory that had errors, print error summary at the end.

- internal/buf/pool_test.go
- repo/object/object_manager_test.go
- repo/object/object_writer.go
- snapshot/snapshotfs/checkpoint_registry.go
- snapshot/snapshotfs/checkpoint_registry_test.go
- snapshot/snapshotfs/upload.go
This was observed by 2 users and reported on Slack.
Fixes #648 
Also added protection to ensure we never save empty object ID in a checkpoint.
> Fixed empty object IDs in checkpoints

- Makefile
- repo/crypto_key_derivation nontest.go
- repo/crypto_key_derivation.go
- repo/crypto_key_derivation_testing.go
- tests/end_to_end_test/all_formats_test.go
- tests/end_to_end_test/snapshot_gc_test.go
- tests/testenv/cli_test_env.go
* Because we're invoking kopia executable repeatedly it makes sense to use cheaper password hashing in tests.
* also optimized TestAllFormatsSmokeTest
This reduced test time by ~4 minutes, still pretty flaky.
> Speed up integration tests

- Makefile
- internal/server/source_manager.go
When a snapshot is due and we fail to create it (for example because the server is unavailable), we immediately retry it. This change delays the retry by 5 minutes. At the same time we keep polling for status update (every 15s or so), which if the repository comes back online will restart the snapshot sooner.
Fixes #657
> Eliminated busy loop after snapshot failure

- Makefile
- internal/fshasher/fshasher.go
context: https://travis-ci.community/t/weird-filesystem-timestamps-behavior-on-linux-arm64-workers/10053
> fshasher: truncate timestamps to full seconds to accommodate filesystems that lose precision

- internal/logfile/logfile.go
By default Kopia will emit colored output if the output is a non-dumb
terminal. You can use --force-color (or set environment
variable to KOPIA_FORCE_COLOR=true) to override it and emit ANSI color
sequences, which is useful for example when piping through 'less'.
Conversely --disable-color (or KOPIA_DISABLE_COLOR=true)
will prevent color output.
> cli: added --force-color and --disable-color flags

- tests/end_to_end_test/server_start_test.go
turns out 4096-bit RSA key generation uses a lot of CPU and takes >30s on ARM. 2048 bit is much faster.
> testing: use shorter RSA keys to speed up server tests

- cli/cli_progress.go
- cli/command_snapshot_create.go
This allows 'kopia snap create --all --log-level=warning --no-progress'
to produce no console output unless an error is encountered.
> cli: 'snapshot create' switched all stderr output to use logger

- cli/command_restore.go
- fs/entry.go
- fs/localfs/local_fs.go
- snapshot/restore/local_fs_output.go
- snapshot/restore/local_fs_output_linux.go
- snapshot/restore/local_fs_output_windows.go
- snapshot/snapshotfs/upload.go
- tests/end_to_end_test/restore_test.go
On macOS (unlike Linux and Windows) symbolic links can have separate owners and attributes and to set them on restore we need to use different APIs, otherwise we'd be trying to modify the properties of target and not the link itself and if the link points to a non-existing file/dir we would fail with not found.
Fixes #672
> Fixed symlink restore behavior on macOS

- .gitignore
- cli/command_policy_edit.go
- cli/command_policy_set.go
- cli/command_policy_show.go
- fs/entry.go
- fs/ignorefs/ignorefs.go
- fs/ignorefs/ignorefs_test.go
- fs/localfs/local_fs.go
- fs/localfs/local_fs_32bit.go
- fs/localfs/local_fs_64bit.go
- fs/localfs/local_fs_nonwindows.go
- fs/localfs/local_fs_windows.go
- htmlui/src/PolicyEditor.js
- internal/diff/diff.go
- internal/mockfs/mockfs.go
- snapshot/policy/files_policy.go
- snapshot/snapshotfs/all_sources.go
- snapshot/snapshotfs/repofs.go
- snapshot/snapshotfs/source_directories.go
- snapshot/snapshotfs/source_snapshots.go
So this is my very first Go development ever.. :) And as this change appeared to span more files than I originally expected, I suggest actually reading if I've done something silly there. Or possibly proposing another way of doing this if a better one exists.
I tested a couple scenarios, seemed to work as expected! Sadly I didn't find a test system for ignore scenarios, soo I didn't add any automatic tests for this. Also I did not test the HTML ui, I only blindly did the change that seemed like the same thing with another boolean policy.
The new files policy `oneFileSystem` ignores files that are mounted to other filesystems similarly to `tar`'s `--one-file-system` switch. For example, if this is enabled, backing up / should now automatically ignore `/dev`, `/proc`, etc, so the directory …
> Added support for scanning only one filesystem via files policy

- cli/command_mount.go
- go.mod
- go.sum
- internal/mount/mount.go
- internal/mount/mount_fuse.go
- internal/mount/mount_net_use.go
- internal/server/api_mount.go
Adds:
- --fuse-allow-other
- --fuse-allow-non-empty-mount
options to the ./kopia mount commands. 
The motivation for this change is to integrate kopia history (all backups) into list of exposed content from QNAP NAS
(e.g. by SMB). Without this change (--fuse-allow-other), the mount-point can be accessed only by user that executed the command (admin@).
> FUSE: Passthrough options to allow other-users access mount point

- Makefile
- tests/robustness/checker/checker.go
- tests/robustness/engine/action.go
- tests/robustness/engine/engine.go
- tests/robustness/engine/engine_test.go
- tests/robustness/engine/log.go
- tests/robustness/engine/metadata.go
- tests/robustness/engine/stats.go
- tests/robustness/engine/sys.go
- tests/robustness/robustness_test/main_test.go
- tests/robustness/robustness_test/robustness_test.go
- tests/robustness/snap/snap.go
- tests/robustness/snapmeta/index.go
- tests/robustness/snapmeta/index_test.go
- tests/robustness/snapmeta/kopia_meta.go
- tests/robustness/snapmeta/simple.go
- tests/robustness/snapmeta/simple_test.go
- tests/robustness/snapmeta/snapmeta.go
- tests/tools/fswalker/fswalker.go
- Add actions to robustness engine
- Actions wrap other functional behavior and serve as a common interface for collecting stats
- Add stats for the engine, both per run and cumulative over time
- Add a log for actions that the engine has executed
- Add recovery logic to re-sync snapshot metadata after a possible failed engine run (e.g. if metadata wasn't properly persisted).
Current built-in actions:
- snapshot root directory
- restore random snapshot ID into a target restore path
- delete a random snapshot ID
- run GC
- write random files to the local data directory
- delete a random subdirectory under the local data directory
- delete files in a directory
- restore a snapshot ID into the local data directory
Actions are executed according to a set of options, which dictate the relative …
> Robustness engine actions with stats and log

- Makefile
- cli/app.go
- cli/command_content_range_flags.go
- cli/command_repository_connect.go
- cli/command_repository_connect_from_config.go
- cli/command_restore.go
- cli/command_snapshot_copy.go
- cli/command_snapshot_copy_move_history.go
- cli/fscache.go
- cli/show_utils.go
- cli/storage_azure.go
- cli/storage_b2.go
- cli/storage_filesystem.go
- cli/storage_gcs.go
- cli/storage_providers.go
- cli/storage_rclone.go
- cli/storage_s3.go
- cli/storage_sftp.go
- cli/storage_webdav.go
- go.mod
- go.sum
- internal/logfile/logfile.go
- main.go
- site/cli2md/cli2md.go
- snapshot/manager.go
- tests/end_to_end_test/snapshot_copy_move_history_test.go
- tests/end_to_end_test/snapshot_copy_test.go
Both source and destination can be specified using `user@host`, `@host` or `user@host:/path` where destination values override the corresponding parts of the source, so both targeted and mass copying is supported.
Supported combinations are:
```
Source:             Destination         Behavior
---------------------------------------------------
@host1              @host2              copy snapshots from all users of host1
user1@host1         @host2              copy all snapshots to user1@host2
user1@host1         user2@host2         copy all snapshots to user2@host2
user1@host1:/path1  @host2              copy to user1@host2:/path1
user1@host1:/path1  user2@host2         copy to user2@host2:/path1
user1@host1:/path1  user2@host2:/path2  copy snapshots from single path
```
When `--move` …
> cli: added support for copying (or moving) snapshot history

- htmlui/package-lock.json
Similar to the one for `/app`. Dependabot generates separate PRs for each upgrade.
Bumps [ini](https://github.com/isaacs/ini) from 1.3.5 to 1.3.8.
- [Release notes](https://github.com/isaacs/ini/releases)
- [Commits](https://github.com/isaacs/ini/compare/v1.3.5...v1.3.8)
Signed-off-by: dependabot[bot] <support@github.com>
> build(deps): bump ini from 1.3.5 to 1.3.8 in /htmlui

- tests/robustness/engine/engine.go
- tests/robustness/robustness_test/main_test.go
- tests/tools/fio/fio.go
- tests/tools/kopiarunner/kopiarun.go
- tests/tools/kopiarunner/setpdeath.go
- tests/tools/kopiarunner/setpdeath_linux.go
Remove unnecessary intermediate variables
Send `SIGTERM` instead of `SIGKILL` to terminate child kopia server process
Set Pdeathsig on Linux for child kopia server process
Trivial: reduce scope of `hostFioDataPathStr` variable
Trivial: rename local variable
Trivial: Use log.Fatalln instead of log + exit(1)
Improve error message in robustness test to tell apart failure cause
> robustness: various minor cleanups

- cli/command_repository_connect.go
- cli/command_snapshot_create.go
- repo/local_config.go
- snapshot/snapshotfs/upload.go
- snapshot/snapshotfs/upload_actions.go
- tests/end_to_end_test/snapshot_actions_test.go
This can be specified at `repo create` or `repo connect` to enable
actions. By default actions are disabled to avoid security risks
associated with executing code.
Alternatively during `snapshot create` one can specify
`--force-enable-actions` or `--force-disable-actions`
> actions: Added --enable-actions flag

- cli/command_content_verify.go
- cli/command_snapshot_verify.go
- tests/end_to_end_test/snapshot_gc_test.go
- tests/end_to_end_test/snapshot_verify_test.go
* When running against direct repository, it will verify that all backing blobs exist based on results of listing.
* Deprecated annoying `--all-sources` flag which is now default if no sources are provided.
* Added e2e test.
> cli: improvements to 'snapshot verify'

- repo/maintenance/maintenance_schedule.go
- repo/object/object_manager.go
- repo/open.go
This is for #746 (there is likely a deeper issue here)
> fixed cases where nil was passed to errors.Wrap() causing nil to be returned

- cli/password.go
- tests/end_to_end_test/api_server_repository_test.go
- tests/testenv/cli_test_env.go
This also fixed a test bug where the test was incorrectly passing password via environment variable and it was (incorrectly) expected to be ignored.
Password is determined in the following order:
- flag/environment variable (highest priority)
- persistent storage
- asking user (lowest priority)
Fixes #741
> cli: only fetch the persisted password from keychain/keyring if one was not provided on the command line

- internal/logfile/logfile.go
More detail in https://github.com/kopia/kopia/issues/715
> Fix bug that empty log directories are created on any command with --help argument

- internal/mount/mount_net_use.go
- site/content/docs/Getting started/_index.md
- site/content/docs/Mounting/_index.md
Before this change, error message looks like:
```
error: mount error: unable to mount webdav server as drive letter: unable to run 'net use' (): error running 'net use': exit status 2, try --help
```
After this change, when error code 2:
```
error: mount error: unable to mount webdav server as drive letter: this error is often caused by but not limited to the 'WebClient' service being unable to start: exit status 2, try --help
```
When error code other than 2:
```
error: mount error: unable to mount webdav server as drive letter: error running 'net use': exit status 123, try --help
```
This change fixes the duplicate short message about 'net use'. It removes the empty `()`, because output is empty in case of error. It adds potential cause for error code 2. Otherwise, the error message is …
> Add potential cause of specific mount command error on Windows

- repo/content/committed_content_index.go
- repo/content/index.go
- repo/content/merged.go
In a typical repository there will be many small indexes and few large
ones. If the number gets above ~100 or so, things get very slow.
It helps to pre-merge very small indexes in memory to reduce the number
of binary searches and mmaped IO to perform. In some extreme cases
where we have many uncompacted index segments (each with just 1-2
entries), the savings are as quite dramatic.
In one case with >100 index segments the time to run
`kopia snapshot verify` went from 10m to 0.5m after this change.
In another well-maintained repository with 1.2M contents and
about 25 segments, the time to run `kopia snapshot verify` went from
48s to 35s.
> performance: improve performance of fragmented index lookups

- repo/content/caching_options.go
- repo/content/content_formatter_test.go
- repo/content/content_index_recovery.go
- repo/content/content_manager.go
- repo/content/content_manager_lock_free.go
- repo/content/content_manager_test.go
- repo/content/content_read_manager.go
- repo/manifest/manifest_manager_test.go
- repo/open.go
- tests/stress_test/stress_test.go
CommittedReadManager supports reading of committed contents only
(note commits are not necessarily pretty but should be easy to review)
> mechanical refactoring of content manager to extract CommittedReadManager

- fs/ignorefs/ignorefs_test.go
- tests/end_to_end_test/snapshot_create_test.go
- tests/testenv/cli_test_env.go
This is related to #571 and #773, but provided as a separate PR to include tests that did not work before PR #773.
> Created end-to-end tests verifying .kopiaignore behavior.

- cli/app.go
- cli/command_blob_gc.go
- cli/command_session_list.go
- internal/blobtesting/faulty.go
- repo/blob/filesystem/filesystem_storage.go
- repo/content/blob_crypto.go
- repo/content/content_formatter_test.go
- repo/content/content_manager.go
- repo/content/content_manager_indexes.go
- repo/content/content_manager_test.go
- repo/content/index_blob_manager.go
- repo/content/index_blob_manager_test.go
- repo/content/sessions.go
- repo/content/sessions_test.go
- repo/maintenance/blob_gc.go
- repo/maintenance/blob_gc_test.go
- repo/maintenance/maintenance_run.go
- repo/open.go
- repo/repository.go
- tests/end_to_end_test/restore_fail_test.go
Sessions allow blob GC to ignore `p` and `q` blobs that are in the process of being written but don't have a corresponding index `n` blob yet.
Content manager will write `s<hash>-<session-id>` blob first before writing any `p`, `q` or `n` blobs (which will all share the same random session id). Only after successfully writing `n` blob, we will delete the `s` blob.
The reader (blob GC) will ignore `p` and `q` blobs if there's a corresponding `s` blob with the same session ID.
This is somewhat functional now, but there's no real way to control for session lifetime (it's implicit from first content write to a subsequent Flush()) so if two logical sessions share the same content manager they will be entangled (such as in `kopia server`)
Future PRs will allow creation of much longer session …
> Preliminary support for sessions

- cli/command_repository_status.go
- internal/server/api_repo.go
- repo/content/content_index_recovery.go
- repo/content/content_manager.go
- repo/content/content_manager_indexes.go
- repo/content/content_manager_iterate.go
- repo/content/content_manager_lock_free.go
- repo/content/content_manager_test.go
- repo/content/content_read_manager.go
- repo/content/sessions.go
- repo/maintenance/content_rewrite.go
- repo/maintenance/maintenance_run.go
- repo/open.go
- repo/repository.go
- tests/stress_test/stress_test.go
- renamed content.Manager to content.WriteManager
- merged lockFreeManager and CommittedReadManager into SharedManager
- also reassigned some methods to SharedManager (no code move)
> content: refactoring of content.Manager

- cli/auto_upgrade.go
- cli/command_server_start.go
- internal/auth/authn.go
- internal/auth/authn_test.go
- internal/auth/authz.go
- internal/auth/authz_test.go
- internal/server/api_content.go
- internal/server/api_error.go
- internal/server/api_manifest.go
- internal/server/server.go
- internal/serverapi/serverapi.go
Previously authentication was done as an wrapper handler and
authorization was inlined. This change moves authn/authz handlers
inside the server and implements separate authorization module that's
individually tested.
Also fixed an issue where server users were not able to see global
or host-level policies.
> server: reworked authn/authz

- cli/command_restore.go
- snapshot/restore/local_fs_output.go
- tests/end_to_end_test/restore_test.go
Add symlink overwrite behavior to fix "file exists" error when restoring a symlink that already exists
Before creating the restored symlink, check `os.Lstat`:
- If it returns an error indicating the file does not exist, proceed to symlink creation
- If it returns any other error, propagate the error up to the caller
- If the fileInfo indicates the entry is a symlink AND `--no-overwrite-symlinks` was set in the restore command, propagate an error to the caller
- If `--no-overwrite-symlinks` was NOT set, remove the existing symlink before proceeding to symlink creation
- Else the file exists but it is not of type symlink. Halt the operation and propagate an error indicating we tried to restore a symlink over a file system entry that already existed but was not a symlink.
Added case to …
> Overwrite symlinks with optional flag - fix for #689

- tests/robustness/checker/checker.go
- tests/robustness/comparer.go
- tests/robustness/engine/engine.go
- tests/robustness/persister.go
- tests/robustness/snapmeta/kopia_meta.go
- tests/robustness/snapmeta/simple.go
- tests/robustness/snapshotter.go
- tests/tools/fswalker/fswalker.go
- tests/tools/kopiarunner/kopia_snapshotter.go
> All robustness test engine interface definitions moved into the test root directory

- repo/blob/azure/azure_storage.go
- repo/blob/azure/azure_storage_test.go
- repo/blob/b2/b2_storage.go
- repo/blob/b2/b2_storage_test.go
- repo/blob/filesystem/filesystem_storage.go
- repo/blob/gcs/gcs_storage.go
- repo/blob/retrying/retrying_storage.go
- repo/blob/retrying/retrying_storage_test.go
- repo/blob/s3/s3_storage.go
- repo/blob/s3/s3_storage_test.go
- repo/blob/sftp/sftp_storage.go
- repo/blob/storage.go
- repo/blob/webdav/webdav_storage.go
- snapshot/policy/retention_policy.go
Previously we were trying to guess which errors are retriable
(often poorly, since things like DNS or HTTP errors were not retried)
This change makes it so the provider does not need built-in retry logic
and instead retrying wrapper is added which retries on all errors other
than
`blob.ErrNotFound`, `blob.ErrInvalidRange` and `blob.ErrSetTimeUnsupported`.
This required thorough testing of negative conditions that would trigger
blob.ErrInvalidLength (we already had those). Verified that tests pass
against Azure, B2, S3, GCS, Rclone, WebDAV, SFTP.
> blob: rewrote blob storage providers retry logic

- cli/command_restore.go
- snapshot/restore/local_fs_output.go
- snapshot/restore/restore.go
- snapshot/restore/tar_output.go
- snapshot/restore/zip_output.go
- tests/end_to_end_test/restore_fail_test.go
- tests/end_to_end_test/restore_test.go
Created this as a hotfix for one of the users on Slack. We were trying to restore ~TB of data where a blob went missing in B2 storage (suspect pre-0.7.3 repository which did not have correct retry logic). 
This adds:
* `--incremental` - which will not attempt to download files already present in the output as long as the size and mod time are correct
* `--ignore-errors` in case a file can't be restored for any reason, print the error to output but continue copying
> restore: added support for incremental restore and ignoring copy errors

- Makefile
- cli/command_server_start.go
- cli/command_server_tls.go
- repo/blob/sftp/sftp_storage_test.go
- tests/end_to_end_test/server_start_test.go
This is a breaking change for development scenarios to prevent people
from unknowingly launching insecure servers.
Attempt to start a server without either TLS or password protection
results in an error now (unless --insecure is also passed).
KopiaUI already launches server with TLS and random password, so it
does not require it.
> cli: added '--insecure' flag to 'kopia server start'

- cli/app.go
- cli/command_server_start.go
- cli/command_user_add_set.go
- cli/command_user_delete.go
- cli/command_user_info.go
- cli/command_user_list.go
- internal/auth/authn.go
- internal/auth/authn_repo.go
- internal/auth/authn_repo_test.go
- internal/user/user_manager.go
- internal/user/user_manager_test.go
- internal/user/user_profile.go
- internal/user/user_profile_hash_v1.go
- internal/user/user_profile_test.go
- repo/maintenance/maintenance_params.go
- repo/manifest/manifest_entry.go
- repo/manifest/manifest_entry_test.go
- snapshot/policy/policy_manager.go
- tests/end_to_end_test/api_server_repository_test.go
This is an alternative to htpasswd-based authentication. Users can be added and manipulated using CLI and are stored in a repository as manifests of type `user`.
> Added support for user authentication using user profiles stored in the repository

- cli/command_restore.go
For snapshot restore, the number of arguments to `log(ctx).Infof()` in the progress output is greater than the number of format placeholders, resulting in messy logs:
```
Processed 12140 (27.4 MB) of 79255 (614.3 MB).%!(EXTRA string= 219.2 Mbit/s (4.5%) remaining 21s)
```
Add a placeholder for the last argument, so log outputs as expected:
```
Processed 12877 (43.9 MB) of 79255 (614.3 MB) 351.5 Mbit/s (7.2%) remaining 12s.
```
> Fix progress output string format for snapshot restore

- cli/command_policy_edit.go
- cli/command_policy_set_scheduling.go
- cli/command_policy_set_test.go
- cli/command_policy_show.go
- cli/command_snapshot_create.go
- htmlui/src/PolicyEditor.js
- snapshot/policy/policy.go
- snapshot/policy/policy_manager.go
- snapshot/policy/scheduling_policy.go
- tests/end_to_end_test/snapshot_create_test.go
Added a new manual field in the scheduling policy.
While gathering all the existing sources during creation of snapshot using `--all` flag, we check the effective policy on each source and skip it if the `manual` value is set to true.
This mechanism can be used for virtual sources (`stdin`) where we don't have the respective directory/file on the local filesystem.
> Support for ignoring sources when using `snapshot create --all`

- cli/command_server_start.go
- internal/apiclient/apiclient.go
- internal/repotesting/repotesting.go
- internal/server/grpc_session.go
- internal/server/server_test.go
- repo/api_server_repository.go
- repo/content/committed_content_index.go
- repo/content/content_manager.go
- repo/grpc_repository_client.go
- repo/manifest/committed_manifest_manager.go
- repo/manifest/manifest_manager.go
- repo/manifest/manifest_manager_test.go
- repo/repository.go
This does 4 things as separate commits, but clumping them together since they depend on each other:
1. removed the need for manifest manager refresh. Instead content manager is exposing revision counter that changes on every mutation and every time new index blob is added - manifest manager will refresh itself when the underlying content manager revision has changed.
2. refactored server initialization - needed for test below.
3. added unit tests for the repository server API (both REST and GRPC). This actually uncovered the problem requiring manifest refresh fix. 
4. once the tests were in place, added optimization to avoid sending content payload to the server if the server already has the content with a given ID.
> Removed manifest manager refresh + server improvements

- cli/app.go
- cli/cli_progress.go
- cli/command_ls.go
- cli/command_snapshot_create.go
- cli/command_snapshot_list.go
- cli/command_snapshot_migrate.go
- fs/entry.go
- internal/server/source_manager.go
- snapshot/snapshotfs/upload.go
- snapshot/snapshotfs/upload_progress.go
- snapshot/snapshotfs/upload_test.go
- snapshot/stats.go
- tests/end_to_end_test/restore_fail_test.go
- tests/end_to_end_test/snapshot_fail_test.go
- tests/testenv/cli_test_env.go
Fixes #690
This is a breaking change for folks who are expecting snapshots to fail
quickly without writing a snapshot manifest in case of an error.
Before this change, any source read failure would cause the entire
snapshot to fail (and not write a snapshot manifest as a result),
unless `ignoreFileErrors` or `ignoreDirectoryErrors` was set.
The new behavior is to continue snapshotting remaining files and
directories (this can be disabled by passing `--fail-fast` flag or
setting `KOPIA_SNAPSHOT_FAIL_FAST=1` environment variable) and defer
returning an error until the very end.
After snapshotting we will always attempt to write the snapshot manifest
(except when the root of the snapshot itself cannot be opened). In case
of a fail-fast error, the manifest will be marked as 'partial' and
the …
> snapshot: reworked error handling and added fail-fast option

- .github/workflows/kopia-ui-pr-test.yml
- .github/workflows/make.yml
- go.mod
* Use Go 1.16 in GHA workflows
> Upgrade to Go 1.16

- cli/command_mount.go
- internal/mount/mount.go
- internal/mount/mount_fuse.go
- internal/mount/mount_posix_webdav_helper.go
- internal/mount/mount_posix_webdav_helper_darwin.go
- internal/mount/mount_posix_webdav_helper_linux.go
Work around upstream issues with MacFuse and bazil.org/fuse on Apple
Silicon Macs by using WebDav on darwin arm64. Provides an (at least
temporary) fix for #811.
> Working kopia mount on Apple Silicon

- .golangci.yml
- Makefile
- internal/clock/now_prod.go
- internal/clock/now_testing.go
- internal/editor/editor.go
- internal/faketime/faketime.go
- repo/blob/retrying/retrying_storage_test.go
- repo/blob/s3/s3_storage_test.go
- repo/blob/sftp/sftp_storage_test.go
- repo/maintenance/blob_gc.go
- repo/maintenance/blob_gc_test.go
- tests/end_to_end_test/api_server_repository_test.go
- tests/end_to_end_test/snapshot_actions_test.go
- tests/robustness/checker/checker.go
- tests/robustness/engine/action.go
- tests/robustness/engine/engine.go
- tests/robustness/engine/engine_test.go
- tests/robustness/engine/log.go
- tests/robustness/engine/metadata.go
- tests/robustness/engine/stats.go
- tests/robustness/robustness_test/robustness_test.go
added `faketime.NewClockTimeWithOffset` and used that to fix flaky
`TestDeleteUnreferencedBlobs` test.
> lint: fixed vet-time-inject and replaced with forbidigo linter

- cli/command_policy_set_error_handling.go
- cli/command_policy_show.go
- fs/entry.go
- fs/localfs/local_fs.go
- htmlui/src/PolicyEditor.js
- htmlui/src/uiutil.js
- internal/mockfs/mockfs.go
- snapshot/policy/error_handling_policy.go
- snapshot/snapshotfs/repofs.go
- snapshot/snapshotfs/source_snapshots.go
- snapshot/snapshotfs/upload.go
- snapshot/snapshotfs/upload_test.go
This is used for things like fifos, sockets, block and character devices, etc.
Each `ErrorEntry` will propagate as snapshot error in the `Uploader` instead of being semi-silently ignored in the `localfs`.
Both localfs and repofs are expected to have ErrorEntries. The latter in case of cross-version compatibility where old version of kopia is attempting to restore directories created using new version.
The user now has a new choice whether to treat unknown filesystem errors as fatal or ignored errors during upload. The default is to ignore them - the user will see the failure in the manifest but it won't cause the entire snapshot command to fail.
> Added first-class support for fs.ErrorEntry for directory entries that could not be read or are unknown/unsupported

- cli/command_server_start.go
- go.mod
- internal/apiclient/apiclient.go
- internal/server/server.go
Tokens encode the authenticated user, last for 1 minute and are signed
with HMAC-SHA-256. This improves HTTP server performance by a lot:
BEFORE: 168383 files (6.4 GB) - 3m38s
AFTER: 168383 files (6.4 GB) - 1m37s
> server: avoid password hashing by using short-lived JWT tokens

- tests/robustness/pathlock/path_lock.go
- tests/robustness/pathlock/path_lock_test.go
Add a utility to ensure path-based synchronization between goroutines. If a path is locked, a subsequent Lock will block if the requested path is the same, or a child/parent (recursive), of the locked path.
This assists with coordination between asynchronous robustness engine actions that may rely on the underlying data directory remaining unchanged. For example:
- between gathering a filesystem fingerprint and taking a snapshot.
- when one WriteFilesAtDepth command has traversed into a directory that another goroutine has picked for deletion.
> Path lock utility for coordination between robustness engine actions

- tests/robustness/checker/checker.go
- tests/robustness/engine/engine.go
- tests/robustness/engine/engine_test.go
- tests/robustness/engine/metadata.go
- tests/robustness/errors.go
- tests/robustness/persister.go
- tests/robustness/snapmeta/index.go
- tests/robustness/snapmeta/simple.go
- tests/robustness/snapmeta/simple_test.go
Add metadata R/W locking for asynchronous accesses to robustness engine metadata.
Remove the index from the Store interface and maintain it only in Checker, where it's used.
> Metadata protection for asynchronous robustness transactions

- cli/command_snapshot_create.go
- fs/entry.go
- fs/virtualfs/virtualfs.go
- fs/virtualfs/virtualfs_test.go
- snapshot/snapshotfs/upload.go
- snapshot/snapshotfs/upload_scan.go
- snapshot/snapshotfs/upload_test.go
- tests/end_to_end_test/snapshot_create_test.go
- tests/testenv/cli_test_env.go
- `fs.StreamingFile` interface with a `GetReader` method to return an `io.Reader`
- `virtualfs` package to implement an in-memory static version of `fs.Directory` and `fs.StreamingFile`
- `snapshot create <rootdir> --stdin-file <file name>` creates a static directory (rootdir) with a single streaming file entry (file name) and uploads it
```
$ cat ./kopia | ./kopia snapshot create kopiadir --stdin-file=kopia
* 0 hashing, 1 hashed (32.3 MB), 0 cached (0 B), uploaded 32.3 MB, estimating...
Created snapshot with root k299834b5c887776879bf7e680eed6542 and ID 38e21994c4625dd128a463db0d6c0226 in 0s
```
```
$ ./kopia snapshot list
k10admin@mac:kopiadir
2021-03-03 16:17:09 PST k299834b5c887776879bf7e680eed6542 32.3 MB drwxrwxrwx files:1 dirs:1 …
```
> Support for stdin streams

- cli/command_cache_clear.go
- cli/command_cache_info.go
- cli/command_cache_set.go
- cli/command_repository_connect.go
- cli/command_repository_connect_from_config.go
- htmlui/src/RepoStatus.js
- internal/server/api_repo.go
- internal/server/grpc_session.go
- internal/serverapi/serverapi.go
- internal/tlsutil/tlsutil.go
- repo/api_server_repository.go
- repo/caching.go
- repo/connect.go
- repo/grpc_repository_client.go
- repo/local_config.go
- repo/local_config_test.go
- repo/open.go
- repo/repository.go
I was manually testing the robustness of the user experience of connecting to kopia repository server. I tried emulating mistakes users might make along the way and verifying that the UX makes sense.
* The biggest issue I've noticed that we were not properly setting up cache when `kopia repository connect server` was used.
* Another notable change is that `kopia cache` commands will be allowed for server-based repositories.
* ~~Also tightened validation of usernames to enforce that they must be lowercase and matching some sane regex.~~ (moved to #873)
* `KOPIA_CACHE_DIRECTORY` environment variable can now be used to globally override the cache path for kopia (both for create/connect and when opening the repository)
* Also made some errors when connecting to the server more descriptive and …
> Improvements and cleanups for connecting to kopia server

- cli/command_server_start.go
- internal/apiclient/apiclient.go
- internal/auth/authn.go
- internal/auth/authn_test.go
- internal/server/api_content.go
- internal/server/api_manifest.go
- internal/server/api_object_get.go
- internal/server/server.go
- internal/server/server_authz_checks.go
- internal/server/server_test.go
- internal/serverapi/client_wrappers.go
- tests/end_to_end_test/api_server_repository_test.go
This formalizes the concept of a 'UI user' which is a local user that can call APIs the same way that UI does it.
The server will now allow access to:
- UI user (identified using `--server-username` with password specified
using `--server-password` or `--random-password`)
- remote users with usersnames/passwords specified in `--htpasswd-file`
- remote users defined in the repository using `kopia users add`
when `--allow-repository-users` is passed.
The UI user only has access to methods specifically designated as such
(normally APIs used by the UI + few special ones such as 'shutdown').
Remote users (identified via `user@host`) don't get access to UI APIs.
There are some APIs that can be accessed by any authenticated
caller (UI or remote):
- /api/v1/flush
- /api/v1/repo/status
- …
> server: refactored authentication and authorization

- cli/auto_upgrade.go
- cli/command_repository_create.go
- cli/update_check.go
- repo/maintenance/maintenance_params.go
- site/content/docs/Release Notes/v0.8.md
Tweaked default message to print on repository creation.
> maintenance: enable full maintenance by default with 24h interval

- cli/command_server_start.go
- internal/server/server.go
This is for a scenario where a user provides valid username/password
but such that the username is not authorized to access the UI.
Previously we'd make it look like they got access (because they can
see the UI at leaast partially), but all API calls would fail.
With this change we're failing early with HTTP 403 and pointing the
users at a GH issue explaining what to do.
Fixes #880.
> server: ensure we reject access to the UI static files for users other than the UI user

- go.mod
- go.sum
Note this is not an obvious performance win - see #887
Fixes #887.
> compress: upgrade klauspost/compress to v1.11.12

- go.mod
- go.sum
This reverts commit e81b163a1211a0538b704ce0e664f05bf5119f28.
Looks like it may be causing OOMs on ARMHF.
> Revert "compress: upgrade klauspost/compress to v1.11.12 (#888)"

- tests/robustness/checker/checker.go
- tests/robustness/engine/action.go
- tests/robustness/engine/engine.go
- tests/robustness/engine/engine_test.go
- tests/robustness/filewriter.go
- tests/robustness/fiofilewriter/fio_filewriter.go
- tests/robustness/robustness_test/main_test.go
- tests/robustness/robustness_test/robustness_test.go
- tests/robustness/snapmeta/kopia_snapshotter.go
- tests/robustness/snapshotter.go
- tests/tools/fswalker/fswalker_test.go
- tests/tools/fswalker/reporter/reporter_test.go
- tests/tools/fswalker/walker/walker_test.go
Add context to all interface methods, exposed through engine actions to the test writer/engine user.
> Add context to robustness engine interfaces

- .github/workflows/make.yml
- Makefile
- app/Makefile
- app/package.json
- stop publishing to github directly from goreleaser and electron builder
- upload dist/ as artifact at the end of each build
- stage release in a separate directory, generated checksum, GPG sign and publish
- removed spaces from Windows setup exe
> ci/cd: refactored how GH releases are published

- repo/blob/s3/s3_storage.go
While not the case in the current implementation, when the blob metadata is not fully consumed from the channel, then the channel is never closed and the sending go routine never terminates.
Also, removes an unused member field => `s3storage.ctx`
> cleanup: cancel context when listing blobs in S3 provider

- repo/blob/s3/s3_storage.go
- repo/blob/s3/s3_storage_test.go
Fixes #711
Send content MD5 when object locking retention is enabled.
From the S3 documentation:
>
> If you configure a default retention period on a bucket, requests to upload objects in such a bucket must include the Content-MD5 header.
>
> The Content-MD5 header is required for any request to upload an object with a retention period configured using Amazon S3 Object Lock.
>
Ref:
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-overview.html#object-lock-bucket-config
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html
> blob: fix puts for object-lock-enabled S3 stores

- cli/app.go
- cli/command_blob_gc.go
- cli/command_content_rewrite.go
- cli/command_maintenance_run.go
- cli/command_snapshot_gc.go
- internal/server/server.go
- repo/content/committed_read_manager.go
- repo/content/content_manager_indexes.go
- repo/content/index_blob_manager.go
- repo/content/index_blob_manager_test.go
- repo/maintenance/blob_gc.go
- repo/maintenance/blob_gc_test.go
- repo/maintenance/content_rewrite.go
- repo/maintenance/drop_deleted_contents.go
- repo/maintenance/index_compaction.go
- repo/maintenance/maintenance_params.go
- repo/maintenance/maintenance_run.go
- repo/maintenance/maintenance_run_test.go
- repo/maintenance/maintenance_safety.go
- snapshot/snapshotgc/gc.go
- snapshot/snapshotmaintenance/snapshotmaintenance.go
- snapshot/snapshotmaintenance/snapshotmaintenance_test.go
- tests/end_to_end_test/maintenance_test.go
- tests/end_to_end_test/snapshot_delete_test.go
- tests/end_to_end_test/snapshot_gc_test.go
- tests/testenv/cli_test_env.go
This allows selection between safe, high-latency maintenance parameters
which allow concurrent access (`full`) or low-latency which may be
unsafe in certain situations when concurrent Kopia processes are
running.
This is a breaking change for advanced CLI commands, where it removes
timing parameters and replaces them with single `--safety` option.
* 'blob gc'
* 'content rewrite'
* 'snapshot gc'
Improves #800
> cli: added --safety=full|none flag to maintenance commands

- repo/blob/webdav/webdav_storage.go
- repo/blob/webdav/webdav_storage_test.go
Some WebDAV implementations respond with 403 Forbidden when a missing directory is encountered.
To handle this situation, any time an error is encountered while writing a blob, we first try to create requisite directories and if that fails, we return the error.
Additionally, the original failed write call is immediately tried again (rather than using the retry logic).
Fixes #551.
> Handle forbidden responses for missing directories

- repo/maintenance/maintenance_run.go
- repo/maintenance/maintenance_run_test.go
- repo/maintenance/maintenance_safety.go
- repo/maintenance/maintenance_safety_test.go
- repo/maintenance/maintenance_schedule.go
- snapshot/snapshotgc/gc.go
* DeleteUnreferencedBlobs will run if `now() > time(last-content-rewrite) + 1h`
(this ensures other kopia clients will have time refresh their indexes to the rewritten blobs before we delete them)
* RewriteContents runs only if `time(last-blob-deletion) > time(last-content-rewrite)`
(this makes sure we don’t starve blob deletions if somebody runs maintenance too frequently)
With those two rules in place each maintenance cycle will effectively do either `RewriteContents` or `DeleteUnreferencedBlobs` but not both (except when `--safety=none`).
> improved maintenance safety

- cli/cli_progress.go
- cli/command_benchmark_compression.go
- cli/command_benchmark_crypto.go
- cli/command_benchmark_splitters.go
- cli/command_index_optimize.go
- cli/command_repository_sync.go
- cli/command_restore.go
- cli/command_snapshot_verify.go
- internal/logfile/logfile.go
- internal/timetrack/estimator.go
- internal/timetrack/throttle.go
This is what's causing flakes in endurance test where the time sometimes moves way too fast.
> switched progress tracking and ETA computation to time.Now() as it causes fake clock time to run too fast

- snapshot/snapshotfs/upload_progress.go
In the Kopia UI "Processed Files" has a "KB" label on the value, which seems incorrect.
> Remove "KB" label from processed files count

- Makefile
This allows to do `gmake install` on OpenBSD and not fail on `make html-ui` (GNU make is not BSD make)
> Be consistent in $(MAKE) usage

- tools/tools.mk
Node official binary is not released for OpenBSD. User must install it manually from OpenBSD ports or from packages with `pkg_add node`. This patches `tools/tools.mk` to check this in case we run on OpenBSD.
This is the last diff to get a working `make install` on OpenBSD (CLI and embedded UI)
_kopia-ui_ application won't be available anytime soon as it is an Electron app.
> User must install npm manually on OpenBSD

- internal/server/api_estimate.go
Fixes #1001 
The username/hostname were read from the wrong option, and were always empty strings. Verified manually that policies can be found now.
> ui: fixed Estimate not honoring the defined policies

- htmlui/src/BeginRestore.js
- htmlui/src/NewSnapshot.js
- htmlui/src/PolicyEditor.js
- htmlui/src/SourcesTable.js
- htmlui/src/uiutil.js
- snapshot/policy/policy.go
- snapshot/policy/policy_manager.go
- snapshot/policy/policy_manager_test.go
Ensure we don't allow policies on paths with trailing slash or backslash (except root). 
Unified error alerts.
Fixes #1003
Related to #1004
> Policy path validation

- internal/server/server.go
- repo/maintenance/maintenance_params.go
- repo/maintenance/maintenance_run.go
This is to avoid producing useless errors in the `Tasks` tab
Reported at https://kopia.discourse.group/t/periodic-maintenance-failed-for-client/394
> ui: do not attempt running maintenance if the current user is not the maintenance owner

- site/content/docs/Repository Server/_index.md
Hello
This PR adds some documentation for how to configure nginx as reverse proxy with kopia server. 
Might not be perfect, but it's a start. :smile: 
Everything I tested works with this setup: Connect repository, backup, restore, browse, ...
> Add documentation for nginx reverse proxy

- cli/command_benchmark_crypto.go
This PR removes a '=' in the output message when running a benchmark. 
Example without this patch:
```shell
Fastest option for this machine is: --block-hash==BLAKE3-256-128 --encryption=CHACHA20-POLY1305-HMAC-SHA256
```
With the patch, you can copy the output directly and append it to create a new repository:
```shell
kopia repository create filesystem --path /tmp/kopia --block-hash=BLAKE3-256-128 --encryption=CHACHA20-POLY1305-HMAC-SHA256
```
> Benchmark: Remove superfluous = in printout

- tests/robustness/multiclient_test/README.md
- tests/robustness/multiclient_test/framework/harness.go
- tests/robustness/multiclient_test/framework/snapshotter.go
- tests/robustness/multiclient_test/multiclient_test.go
Update multi-client robustness test harness to use the parallel `Run` functionality included in the `testing` package.
This fixes an issue where the robustness test could get stuck waiting for a failed test to complete.
> robustness: use testing.T for parallel robustness tests

- cli/command_index_recover.go
- repo/content/committed_read_manager.go
- repo/content/content_index_recovery.go
- repo/content/content_index_recovery_test.go
- repo/content/content_manager.go
- repo/content/content_manager_test.go
- repo/content/index_blob_manager.go
- repo/content/index_blob_manager_test.go
We used this while investigating and recovering repository for #1087
> cli: optimized 'kopia index recover' by leveraging partial read and parallelism

- cli/command_restore.go
- snapshot/restore/restore.go
- snapshot/restore/shallow_fs_output.go
- tests/end_to_end_test/shallowrestore_test.go
- tests/testdirtree/testdirtree.go
When doing a shallow restore, small files might take up less size than
storing the DirectoryEntry metadata. Add a minimum file size flag that
where files below that size will be written directly instead being
represented with shallow placeholders. This improves on #710.
> Add a flag to not shallowrestore small files

- internal/wcmatch/wcmatch.go
- internal/wcmatch/wcmatch_test.go
Integrated some additional test cases to cover this bug.
Fixes #961
> Fixed bug in .kopiaignore pattern matching for patterns containing a star.

- repo/content/committed_content_index.go
- repo/content/committed_content_index_disk_cache.go
- repo/content/content_manager.go
- repo/content/content_manager_indexes.go
This fixes race condition between index compaction and index refresh
which was causing recent test flakes. This is not likely to happen in
real world as compaction is super rare but test was triggering it very
frequentl.
I was able to reliably repro this with a nearly complete rewrite
of a stress test (coming in separate PR). Without the fix it would fail
in 1-3 attempts, with the fix it succeeded 100 attempts of the new
stress test.
Also improved logging and fixed old terminology leftovers.
> content: re-added missing lock accidentally removed by #1138

- cli/command_restore.go
- tests/end_to_end_test/shallowrestore_test.go
Fixes a usability problem noted in #710: `kopia restore a.kopiaentry b.kopiaentry` will now expand both placeholders.
> Multiplaces

- tests/robustness/checker/checker.go
- tests/robustness/engine/engine.go
- tests/robustness/engine/engine_test.go
- tests/robustness/engine/metadata.go
- tests/robustness/multiclient_test/framework/harness.go
- tests/robustness/multiclient_test/multiclient_test.go
- tests/robustness/persister.go
- tests/robustness/robustness_test/main_test.go
- tests/robustness/robustness_test/robustness_test.go
- tests/robustness/snapmeta/kopia_persister_light.go
- tests/robustness/snapmeta/kopia_persister_light_test.go
- tests/robustness/snapmeta/simple.go
- tests/robustness/snapmeta/simple_test.go
- tests/tools/kopiaclient/kopiaclient.go
This change introduces a new `robustness.Persister` implementation with the goal of reducing the memory consumption of the test as the collection of snapshot metadata grows over time.
The existing persister pulls all snapshot metadata from object storage at the time the test engine is initialized and loads the data into memory. It then pushes all metadata when the engine is cleaned up.
The new persister pulls and pushes metadata for individual snapshots as needed throughout the test. This way, as the size of metadata for all snapshots grows over time, an individual test run will only keep metadata in memory as needed for the snapshots under test.
> robustness: reduce memory consumption

- go.mod
- go.sum
The updated version of [github.com/studio-b12/gowebdav](https://github.com/studio-b12/gowebdav) includes the fix for #1142.
> Bump github.com/studio-b12/gowebdav

- internal/server/server_test.go
- repo/grpc_repository_client.go
- repo/recently_read.go
When re-uploading previously snapshotted directory we fetch directory
content `k<hash>` and very frequently end up writing the exact same
content. By caching last N content IDs we can avoid costly round-trip
to the server since we know that content ID was present in the session.
Also added small number of asynchronous writes, which also helps with
upload performance. Background writes are awaited before Flush().
Performance when snapshotting lots of small files (source code):
31.9 GB files:471205 dirs:75817, warm cache
Before: 260s
After: 55s (4-5x faster)
> repo: big performance improvement for WriteContent with repo server

- tests/robustness/multiclient_test/framework/snapshotter.go
The robustness tests have been failing intermittently with client authentication errors. I believe this is caused by trying to authorize several clients in parallel.
At a high level, the steps for client authorization include running server user add and server refresh. I think we are running into issues by having multiple clients adding users and refreshing the server in parallel.
This PR serializes client authorization to avoid this potential issue.
> robustness: serialize client authorization (#232)

- cli/command_repository.go
- cli/command_repository_change_password.go
- cli/command_repository_change_password_test.go
- cli/command_repository_create.go
- cli/command_repository_repair.go
- cli/command_repository_status.go
- cli/password.go
- internal/repotesting/repotesting.go
- internal/repotesting/repotesting_test.go
- repo/change_password.go
- repo/content/content_formatting_options.go
- repo/crypto_key_derivation_nontest.go
- repo/crypto_key_derivation_testing.go
- repo/initialize.go
- repo/open.go
- repo/parameters.go
- repo/repository.go
- repo/repository_test.go
- tests/end_to_end_test/repository_repair_test.go
- tests/testenv/cli_inproc_runner.go
This will only work for new repositories, since there's now a repository-wide flag that disables replication of `kopia.repository` contents in all packs.
> Repository password change support

- cli/app.go
- cli/command_repository.go
- cli/command_repository_create.go
- cli/command_repository_validate_provider.go
- internal/blobtesting/verify.go
- internal/providervalidation/providervalidation.go
- internal/providervalidation/providervalidation_test.go
- internal/retry/retry.go
- repo/blob/azure/azure_storage_test.go
- repo/blob/b2/b2_storage_test.go
- repo/blob/filesystem/filesystem_storage_test.go
- repo/blob/gcs/gcs_storage_test.go
- repo/blob/rclone/rclone_storage.go
- repo/blob/s3/s3_storage_test.go
- repo/blob/sftp/sftp_storage_test.go
- repo/blob/webdav/webdav_storage.go
- repo/blob/webdav/webdav_storage_test.go
This implements a provider tests which exercises subtle behaviors which are not always correctly implemented by providers claiming compatibility with S3, for example.
The test checks:
- not found behavior
- prefix scans
- timestamps
- write atomicity
> Added 'kopia repository validate-provider`

- cli/storage_rclone.go
- cli/storage_webdav.go
- repo/blob/rclone/rclone_options.go
- repo/blob/rclone/rclone_storage.go
- repo/blob/rclone/rclone_storage_test.go
- repo/blob/webdav/webdav_options.go
- repo/blob/webdav/webdav_storage.go
Added two flags called `--atomic-writes`:
* for `webdav` - defaults to false
* for `rclone` - defaults to true (most rclone backends support atomic writes according to the author)
This allows the `rclone` provider to be much more efficient.
> WebDAV and Rclone atomic writes

- cli/command_snapshot_create.go
- snapshot/snapshotfs/upload.go
I was passing `--force-hash=0.1` for a while before I realized that this is actually parsed as `0` and the rest is silently discarded.
This could of course be turned into an error but personally I believe that fractional percentages are useful here, especially if you create snapshots very frequently.
I run hourly snapshots and `--force-hash=0.1` if I did my math right this should result in a ~0.5% chance that a given file is not hashed within a month, which feels good enough for my regular background snapshots and keeps the load down quite a bit.
> force-hash: Allow fractional percentages

- cli/command_server_start.go
- go.mod
- go.sum
Includes manual change to fix linter deprecation warning.
Bumps [github.com/prometheus/client_golang](https://github.com/prometheus/client_golang) from 1.10.0 to 1.11.0.
- [Release notes](https://github.com/prometheus/client_golang/releases)
- [Changelog](https://github.com/prometheus/client_golang/blob/master/CHANGELOG.md)
- [Commits](https://github.com/prometheus/client_golang/compare/v1.10.0...v1.11.0)
---
- dependency-name: github.com/prometheus/client_golang
dependency-type: direct:production
update-type: version-update:semver-minor
...
Signed-off-by: dependabot[bot] <support@github.com>
> build(deps): bump github.com/prometheus/client_golang

- repo/content/builder.go
- repo/content/content_manager.go
- repo/content/merged.go
- repo/content/merged_test.go
This was reported by Stephan Budach on Slack (thanks!) who provided
the log where two separate write sessions created identical content
at exactly the same time.
```
2021-07-11T06:49:30.056211Z DEBUG [writer-4:Source Manager Uploader] write-content e5a857d1505308e94a4d495833a278da new
2021-07-11T06:49:30.222525Z DEBUG [writer-4:Source Manager Uploader] add-to-pack pe5873427a445f07f92f66837bfbb5752-sfa2a7c24c8d31100106 e5a857d1505308e94a4d495833a278da p:pe5873427a445f07f92f66837bfbb5752-sfa2a7c24c8d31100106 3461377 d:false
2021-07-11T06:49:30.857310Z DEBUG [writer-2:Source Manager Uploader] write-content e5a857d1505308e94a4d495833a278da new
2021-07-11T06:49:31.982930Z DEBUG [writer-2:Source Manager Uploader] add-to-pack p24b9a682047d63b19614827b653e54eb-s583f9f99a3312721106 …
```
> content: ensure that we always consistently pick content.Info amongst entries with identical time and deleted flag

- repo/content/committed_read_manager.go
- repo/content/content_manager.go
- repo/content/content_manager_indexes.go
- repo/content/content_manager_iterate.go
- repo/content/content_manager_test.go
- repo/maintenance/maintenance_run.go
- repo/open.go
- repo/repository.go
also force refresh indexes before running maintenance
Fixes #1242
> content: automatically refresh indexes on read instead of relying on RefreshPeriodically() loop

- repo/splitter/splitter_buzhash32.go
- repo/splitter/splitter_rabinkarp64.go
1) a property of the rolling hashes is that its content only depends on the last [window size] bytes, thus there is no point hashing if we are way below minimum size.
2) inline shouldSplitNoMax: Go currently cannot inline more than one level, so having shouldSplitNoMax means Go cannot inline Roll
3) simplify shouldSplitWithMaxCheck: either we've already split due to finding a splitting point or we're at the max size and we should immediately split, no point having a loop here (note: the call to Roll was moved to shouldSplitNoMax path)
Before
```
DYNAMIC                     2564 ms count:107 min:9467 10th:2277562 25th:2971794 50th:4747177 75th:7603998 90th:8388608 max:8388608
DYNAMIC-1M-BUZHASH          2873 ms count:428 min:9467 10th:612999 25th:766808 50th:1158068 75th:1744194 …
```
> splitter: optimize performance

- .github/workflows/code-coverage.yml
- .github/workflows/license-check.yml
- .github/workflows/race-detector.yml
This happens when opening a PR from the same repo as the PR's target repo.
> ci: avoid double workflow executions on PRs

- cli/app.go
- cli/config.go
When --`config-file` is passed as a filename without any directory
(absolute or relative) it is resolved in OS-specific
config path.
For example on macOS:
`--config-file foo.config`
resolves to:
`~/Library/Application Support/kopia/foo.config`
> cli: added support for passing bare filename for --config-file parameter

- internal/cache/persistent_lru_cache.go
- internal/cache/persistent_lru_cache_test.go
Previously when cache validation failed, we would leave output buffer in the non-empty state, which caused invalid reads.
It's unclear exactly why cache validation failed in the case described in #1294 (could be bit flips or some credentials problem) but this should fix it.
Fixes #1294
> cache: when cache validation fails, properly reset output buffer

- cli/command_blob.go
- cli/command_blob_shards.go
- cli/command_blob_shards_modify.go
- cli/command_blob_shards_modify_test.go
- repo/blob/filesystem/filesystem_storage.go
- repo/blob/sftp/sftp_storage.go
- repo/blob/sharded/sharded.go
- repo/blob/sharded/sharded_parameters.go
- repo/blob/sharded/sharded_test.go
- repo/blob/webdav/webdav_storage.go
This is experimental.
The .shards file can reside in the root of any blob storage that uses
sharding (filesystem/sftp/webdav) and can specify rules for sharding.
```
{
"default": [3,2,1],
"overrides": [
{ "prefix": "p", "shards": [2,2] },
{ "prefix": "x", "shards": [1,1,1] }
],
"maxNonshardedLength": 2
}
```
With this in place we'll be later able to do resharding of the
repository to optimize get/put/list performance for both repositories
and caches.
> blob: support for custom blob store sharding

- cli/command_repository_connect_from_config.go
Avoid panic when the config file is connected to the repository server.
Fixes: #1303
> cli: fixed error message when trying 'repo sync-to from-config' 

- app/package.json
- app/public/electron.js
- app/public/preload.js
- htmlui/src/DirectoryObject.js
- htmlui/src/preload.js
- htmlui/src/uiutil.js
This fixes a regression after upgrading to more recent Electron.
This change implements clean `window.kopiaUI` API that can be used
to detect whether we're running inside KopiaUI shell vs in a browser
and follows latest security recommendation from Electron. All
browser-to-electron bridge code is now in `preload.js`.
Fixes #1309
> ui: fixed directory selector and browse buttons

- internal/gather/gather_bytes.go
- internal/gather/gather_write_buffer.go
- internal/gather/gather_write_buffer_test.go
- internal/repotesting/reconnectable_storage.go
- internal/repotesting/repotesting.go
- internal/repotesting/repotesting_test.go
- internal/server/api_content.go
- internal/server/grpc_session.go
- repo/api_server_repository.go
- repo/content/content_formatter_test.go
- repo/content/content_manager.go
- repo/content/content_manager_test.go
- repo/grpc_repository_client.go
- repo/manifest/committed_manifest_manager.go
- repo/manifest/manifest_manager.go
- repo/object/object_manager.go
- repo/object/object_manager_test.go
- repo/object/object_writer.go
- repo/repo_benchmarks_test.go
- tests/repository_stress_test/repository_stress_test.go
- tests/stress_test/stress_test.go
This reduces memory consumption and speeds up backups.
1. Backing up kopia repository (3.5 GB files:133102 dirs:20074):
before: 25s, 490 MB
after: 21s, 445 MB
2. Large files (14.8 GB, 76 files)
before: 30s, 597 MB
after: 28s, 495 MB
All tests repeated 5 times for clean local filesystem repo.
> repo: allow reusing of object writer buffers

- cli/password_linux.go
On Linux, Keyring is disabled by default and `--use-keyring` must be specified on every command-line invocation, which gets quite annoying.
This PR allows enabling keyring from environment variable instead.
Example
```
$ ./kopia snapshot list
Enter password to open repository:
$ export KOPIA_USE_KEYRING=1
$ ./kopia snapshot list
[list of snapshots]
```
P.S. It would be great if you can add a `hacktoberfest-accepted` label so this PR can count for Hacktoberfest. This works even if the main repo doesn't have a `hacktoberfest` topic.
> cli: linux: read KOPIA_USE_KEYRING env

- internal/gather/gather_bytes.go
- internal/gather/gather_write_buffer.go
- internal/gather/gather_write_buffer_chunk.go
- internal/gather/gather_write_buffer_chunk_test.go
- internal/gather/gather_write_buffer_test.go
- repo/content/content_index_recovery.go
- repo/encryption/aead_helpers.go
- repo/encryption/encryption_test.go
- repo/grpc_repository_client.go
- snapshot/snapshotfs/upload.go
Test cases:
Large source code directory:
Before: average 26s, 481 MB RAM
After: average 24.25s, 377 MB RAM (22% less)
Large directory (11 GB ISOs, movies, large photos):
Before: average 14.75s, 520 MB RAM
After: average 12.25s, 408 MB RAM (22% less)
> upload: memory usage and speed improvements

- fs/cachefs/cache.go
- fs/cachefs/cache_test.go
- fs/cachefs/cachefs.go
Move the wrapping of fs.Entry before caching rather than doing it every time we try to read from the cache.
Fixes #1135
> cachefs: make cache read O(1) instead of O(n)

- fs/localfs/local_fs.go
We read first 100 entries to determine if the directory is short
before forking to goroutines.
> localfs: reduce memory usage when scanning short directories

- app/Makefile
hello!
i noticed in activity monitor that KopiaUI was running under the Intel architecture, which struck me as odd so i did some investigating. it seems that even though the embedded app is universal, the main app is x86_64 only, which causes it to call the intel version of the embedded library.
```
/Applications/KopiaUI.app/Contents
❯ file MacOS/KopiaUI
MacOS/KopiaUI: Mach-O 64-bit executable x86_64
/Applications/KopiaUI.app/Contents
❯ file Resources/server/kopia
Resources/server/kopia: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
Resources/server/kopia (for architecture x86_64):       Mach-O 64-bit executable x86_64
Resources/server/kopia (for architecture arm64):        Mach-O 64-bit executable arm64
```
i added a couple new lines to …
> add conditional to KopiaUI makefile to build macos arm64 and x64 versions

- Makefile
- tools/scoop-kopia.json.template
A few months ago, I opened https://github.com/kopia/scoop-bucket/issues/1. Didn't seem to gain any traction, so here's my attempt to address the issue.
The issue is that Kopia is the only app I've seen that after the Scoop installation, still has version number towards its binary. For example, if my Scoop app is at C:\Scoop, kopia.exe is set at C:\Scoop\apps\kopia\current\kopia-0.9.0-rc3-windows-x64\kopia.exe. Most other apps would have C:\Scoop\apps\kopia\current\kopia.exe instead. The extra subdirectory is unnecessary.
The problem of this version-based subdirectory is that user can no longer have a stable path to the executable after updates. The stable path is the reason why we have the "current" junction point in Scoop. One may argue that since we already have shim, why still care …
> Remove unnecessary subdirectory from Windows archive

- htmlui/src/Table.js
another small PR for #1320, it's nothing pretty but it does work :)
i also merged the individual page bar into the area between the arrows to keep things a bit neater.
before (taken from KopiaUI):
after:
new bar + selector:
options:
resized page:
example of what it looks like when there are more than 20 pages (had to tweak page size for a demo):
> add simple selector for #1320

- internal/blobtesting/eventually_consistent.go
- internal/blobtesting/faulty.go
- internal/blobtesting/map.go
- repo/blob/azure/azure_storage.go
- repo/blob/b2/b2_storage.go
- repo/blob/filesystem/filesystem_storage.go
- repo/blob/gcs/gcs_storage.go
- repo/blob/logging/logging_storage.go
- repo/blob/readonly/readonly_storage.go
- repo/blob/retrying/retrying_storage.go
- repo/blob/s3/s3_pit.go
- repo/blob/s3/s3_storage.go
- repo/blob/sftp/sftp_storage.go
- repo/blob/sharded/sharded.go
- repo/blob/storage.go
- repo/blob/webdav/webdav_storage.go
Exported blob.Storage interface can't be implemented as GetBlob() is using internal gather.WriteBuffer as an output argument type.
My use case is to intercept all Kopia calls to blob.Storage so I can recreate new underlying blob.Storage on the fly if AWS session expires in the middle of a long operation like creating the snapshot.
I am also using this blob.Storage wrapper to log and keep statistics of all calls to blob.Storage.
Proposed changes change the GetBlob() argument type to blob.OutputBuffer.
make command ran all tests successfully
Forum discussion reference:
https://kopia.discourse.group/t/implementing-repo-blob-reader-interface/706/4
> Use blob.OutputBuffer in blob.Reader interface instead of internal gather.WriteBuffer

- cli/config.go
- internal/epoch/epoch_manager_test.go
- internal/logfile/logfile.go
- internal/testlogging/ctx.go
- internal/uitask/uitask.go
- repo/blob/logging/logging_storage.go
- repo/blob/logging/logging_storage_test.go
- repo/blob/rclone/rclone_storage_test.go
- repo/content/committed_content_index_cache_test.go
- repo/content/content_manager_test.go
- repo/content/index_blob_manager_v0_test.go
- repo/content/internal_logger.go
- repo/logging/broadcast.go
- repo/logging/logging.go
- repo/logging/logging_test.go
- repo/logging/null_logger.go
- repo/logging/prefix.go
- repo/logging/printf_logger.go
- repo/maintenance/maintenance_safety_test.go
- repo/open.go
- tests/repository_stress_test/repository_stress_test.go
Added `logging.Logger.Debugw(message, key1, value1, ..., keyN, valueN)` which leverages ZAP to output proper JSON.
As an exercise, rewrote logging storage wrapper to use `Debugw()`:
Output example:
```
DEBUG [STORAGE] PutBlob {"blobID": "sba00357ed756a7e0e399fc850920f4c0-s38f97bfaba0a10eb109", "length": 197, "error": null, "duration": "110.108677ms"}
DEBUG [STORAGE] PutBlob {"blobID": "q8046259c49b1e5bb5ab8eb21631832e3-s38f97bfaba0a10eb109", "length": 4282, "error": null, "duration": "59.107429ms"}
DEBUG [STORAGE] PutBlob {"blobID": "n0667cd85ff5a2116d994e5835c06b509-s38f97bfaba0a10eb109", "length": 127, "error": null, "duration": "64.601015ms"}
DEBUG [STORAGE] GetMetadata {"blobID": "n0667cd85ff5a2116d994e5835c06b509-s38f97bfaba0a10eb109", "result": …
```
> introduced structural debug logging and optional JSON output

- .golangci.yml
- cli/command_cache_info.go
- cli/command_repository_status.go
- fs/localfs/local_fs.go
- internal/logfile/logfile.go
- internal/testutil/tmpdir.go
- repo/blob/filesystem/filesystem_storage.go
- repo/content/committed_content_index_disk_cache.go
- tests/end_to_end_test/snapshot_delete_test.go
- tests/perf_benchmark/process_results.go
- tests/tools/fio/fio.go
- tests/tools/fio/workload.go
- tests/tools/fio/workload_test.go
This PR is an addition to #1360 (see https://github.com/kopia/kopia/pull/1360#discussion_r723279310).
Things to note:
1. `os.ReadDir` is not a direct replacement for `ioutil.ReadDir`, unlike all other functions in `io/ioutil`
2. `os.ReadDir` returns a slice of [os.DirEntry](https://golang.org/pkg/os/#DirEntry), while `ioutil.ReadDir` returns a slice of [fs.FileInfo](https://golang.org/pkg/io/fs/#FileInfo). The biggest difference is the lack of `Size()`, `ModTime()`, and `Sys()` method in the `os.DirEntry` interface.
3. To get the `Size()`, `ModTime()`, or `Sys()` of a file or folder from `os.DirEntry`, we need to call `Info()` first and do an additional error handling.
The `os.ReadDir` was proposed in https://github.com/golang/go/issues/41467. According to the [documentation for …
> refactor: move from ioutil.ReadDir to os.ReadDir

- cli/command_repository_status.go
- internal/logfile/logfile.go
- repo/blob/filesystem/filesystem_storage.go
- repo/content/committed_content_index_disk_cache.go
This was introduced by a refactoring in #1361 - unlike
ioutil.ReadDir() which internally handles list/delete race and always
returns os.FileInfo, Info() on os.DirEntry can fail if a file
is deleted right after listing it.
Fixes #1486
> fixed directory read race condition

- repo/blob/rclone/rclone_storage_test.go
Rclone test would leave behind more and more empty directories leading
to test timeouts.
We will use `rclone` directly to do the cleanup now instead of blob
storage API.
Fixes #1487
> testing: fixed rclone test cleanup

- go.mod
- go.sum
- repo/blob/webdav/webdav_storage.go
This improves the performance of partial data reads, such as the ones
during restore by avoiding reading the full blob only to discard most
of it.
The impact on restore time is dramatic:
Restoring 5.6 GB files:132921 dirs:18980 from rclone based on local
directory:
before: >2h
after: 49.45s
> performance: optimized restore performance for webdav/rclone

- site/content/docs/Installation/_index.md
Since OpenBSD has added kopia as a port/package, add instructions for it also.
> Add OpenBSD instructions

- cli/command_repository_sync.go
- cli/command_restore.go
- internal/units/units.go
Almost all numbers with units in Kopia uses byte (either base-2 or base-10) as the data unit. However, there are two cases use bit, which feels unnecessary and inconsistent. For example, a typical `kopia repository sync-to rclone` output looks like this:
```
Synchronizing repositories:
Source:      Filesystem: <redacted>
Destination: RClone <redacted>
Looking for BLOBs to synchronize...
Found 241 BLOBs in the destination repository (2.4 GB)
Found 244 BLOBs (2.5 GB) in the source repository, 3 (67.8 MB) to copy
Found 0 BLOBs to delete (0 B), 241 in sync (2.4 GB)
Copying...
Copied 2 blobs (45.2 MB), Speed: 14.9 Mbit/s, ETA: 3s (2021-11-17 22:20:38 PST)
```
The data sizes are all byte-based, but speed is suddenly changed to bit-based. Feels inconsistent. And most users aren't used to bits. …
> Change Mbit/s units to MB/s (base-10)

- site/cli2md/cli2md.go
As issue #1440 states, I can see several problems of the generated doc pages:
1. The top-level [Common Commands](https://kopia.io/docs/reference/command-line/common/) is very cluttered. This is because `cli2md` puts all the command's help string to the page, not accounting for how long the string could be (some such as `restore` are very long). This PR proposes to only put the summary of each help string, e.g. the first line, to the page.
2. The sidebar currently only shows [the first 50 pages in that doc level](https://github.com/kopia/kopia/blob/2394b420b02eaf301b3eb4e0f0626cd124f60469/site/themes/docsy/layouts/partials/sidebar-tree.html#L32). But there are more than 50 CLI commands. The inconsistency between the summary page content and sidebar confuses users. Since the summary page …
> Cleanup cli2md to fix issue #1440

- cli/command_snapshot.go
- cli/command_snapshot_create.go
- cli/command_snapshot_list.go
- cli/command_snapshot_pin.go
- cli/command_snapshot_pin_test.go
- snapshot/manager.go
- snapshot/manifest.go
- snapshot/policy/expire.go
- snapshot/snapshot_test.go
This allows pinning and unpinning of snapshots, which will protect
them from deletion. Any number of pins can be put on a manifest
to indicate reasons why the snapshot is being pinned.
This is similar to retention labels, but is manually managed.
Usage:
```
$ kopia snapshot create path --pin pin1 --pin pin2
$ kopia snapshot pin <manifest-id> --add pin3
$ kopia snapshot pin <manifest-id> --remove pin2
```
Instead of `<manifest-id>` you can also specify directory object ID.
Fixes #1518
> cli: added 'snapshot pin' command

- cli/command_snapshot_list.go
- tests/end_to_end_test/snapshot_create_test.go
> cli: fixed 'snapshot list --json --max-results'

- site/content/docs/Repositories/_index.md
Google Cloud Storage repository creation and connection should use "gcs" instead of "google" in cli examples.
> Replace google with gcs in examples

- site/content/docs/Advanced/Amazon S3/_index.md
- site/content/docs/Advanced/Sharding/_index.md
Also, I wonder if it's good idea to only do `[3, 3]` sharding for local file system repos, i.e. `repository create s3` would always do `[]`?
> Add doc for sharding

- cli/command_policy_show.go
- cli/command_repository_create.go
- cli/command_snapshot_list.go
- internal/server/api_snapshots.go
- internal/server/source_manager.go
- snapshot/policy/actions_policy.go
- snapshot/policy/compression_policy.go
- snapshot/policy/error_handling_policy.go
- snapshot/policy/error_handling_policy_test.go
- snapshot/policy/expire.go
- snapshot/policy/files_policy.go
- snapshot/policy/log_detail.go
- snapshot/policy/logging_policy.go
- snapshot/policy/optional.go
- snapshot/policy/policy.go
- snapshot/policy/policy_manager.go
- snapshot/policy/policy_manager_test.go
- snapshot/policy/policy_merge.go
- snapshot/policy/policy_merge_test.go
- snapshot/policy/policy_tree.go
- snapshot/policy/retention_policy.go
- snapshot/policy/scheduling_policy.go
Added policy.Definition which allows us to precisely report where
each piece of policy came from.
Fixed a one-off bug with "noParent", which prevented merging of parent
policies one level too soon.
Added a whole bunch of merging helpers and generic reflection-based
test that ensures every single merge is tested.
> policy: revamped policy merge mechanism

- cli/command_cache_info.go
- cli/command_cache_set.go
- cli/command_repository_connect.go
- internal/cache/persistent_lru_cache.go
- internal/cache/persistent_lru_cache_test.go
- repo/caching.go
- repo/content/caching_options.go
- repo/content/committed_content_index.go
- repo/content/committed_content_index_cache_test.go
- repo/content/committed_content_index_disk_cache.go
- repo/content/committed_read_manager.go
- repo/content/content_cache_data.go
- repo/content/content_cache_metadata.go
- repo/content/content_cache_test.go
- repo/open.go
This is done by protecting newly added cache items from being swept for
X amount of time where X defaults to:
* `metadata` - 24 hours (new)
* `data` - 10 min (new)
* `indexes` - 1 hours (same as today)
Fixes #1540
> cache: prevent metadata cache thrashing if working set exceeds max defined size

- cli/app.go
- internal/logfile/logfile.go
- internal/logfile/logfile_test.go
With this change logs will be rotated every 50 MB, which prevents
accumulation of giant files while server is running.
This change will also guarantee that log sweep completes at least once
before each invocation of Kopia finishes. Previously it was a goroutine
that was not monitored for completion.
Flags can be used to override default behaviors:
* `--max-log-file-segment-size`
* `--no-wait-for-log-sweep` - disables waiting for full log sweep
Fixes #1561
> logging: added log rotation and improved predictability of log sweep

- cli/command_snapshot_list.go
- htmlui/src/SnapshotsTable.js
- internal/server/api_policies.go
- internal/server/api_snapshots.go
- internal/serverapi/client_wrappers.go
- internal/serverapi/serverapi.go
- snapshot/policy/retention_policy.go
- snapshot/policy/retention_policy_test.go
- tests/end_to_end_test/server_start_test.go
Kopia will now merge retention tags over identical snapshots and show the range instead of a single tag:
```
2021-11-21 23:46:13 PST kd8198056ac88f8c638cb2b170a1e8ec4 860.4 KB drwxr-xr-x files:178 dirs:26 (weekly-3)
2021-11-28 22:40:00 PST k04684e8a4b152adbb5716e84ea617f98 860.4 KB drwxr-xr-x files:178 dirs:26 (daily-6..7,weekly-2)
+ 1 identical snapshots until 2021-11-29 20:40:03 PST
2021-11-30 22:50:00 PST k50d56093831023a1cb22e805e8238f93 860.7 KB drwxr-xr-x files:178 dirs:26 (daily-5,monthly-2)
2021-12-01 21:30:01 PST k8eee61e10b2cdd8a680f90692bc9a224 860.4 KB drwxr-xr-x files:178 dirs:26 (daily-3..4)
+ 1 identical snapshots until 2021-12-02 20:40:15 PST
2021-12-03 12:20:01 PST k54c67ba7964d7424b2c391c5813af9a5 860.4 KB drwxr-xr-x files:178 dirs:26 (latest-8..10)
+ 2 identical …
```
> Merge retention tags in snapshot lists

- fs/localfs/local_fs_32bit.go
- fs/localfs/local_fs_64bit.go
Encountered while trying to update kopia to 0.8.4 in Void Linux, see https://github.com/void-linux/void-packages/pull/30146.
```
fs/localfs/local_fs_nonwindows.go:26:41: cannot use stat.Dev (type uint64) as type int32 in argument to platformSpecificWidenDev
fs/localfs/local_fs_nonwindows.go:27:42: cannot use stat.Rdev (type uint64) as type int32 in argument to platformSpecificWidenDev
```
~Should I also add goarch 386 to `.goreleaser.yml`?~
> localfs: adjust build flags to support more archs

- cli/command_policy_edit.go
The field is called ignoreDotFiles in JSON, but the documentation says
dotIgnoreFiles. Fix the docs to refer to the correct field name.
> Fix typo in policy help documentation

- repo/blob/s3/s3_storage_test.go
Refactors retention tests to coalesce a couple of tests. It has the following effects:
- serializes the tests;
- reuses the bucket and reduces bucket creation calls.
Also, checks whether a bucket exists before attempting to create it to reduce the number of bucket creation calls.
> s3/test: refactor retention tests

- repo/blob/logging/logging_storage.go
- repo/blob/throttling/throttling_storage_test.go
Trying to understand if we're doing something wrong for #1560
> logging: log maximum concurrency level when talking to backend storage

- tools/apt-publish.sh
Fixes #1657
`stable` and `testing` repos have been updated, merging this will fix `unstable` too.
> fix(ci): fix regression when publishing APT repository

- site/content/docs/Installation/_index.md
Use gpg to install signing key. `apt-key` is deprecated and will be removed after Ubuntu 22.04.
> Use gpg instead of apt-key

- internal/dirutil/mksubdirall.go
- internal/dirutil/mssubdirall_test.go
- repo/blob/filesystem/filesystem_storage.go
- repo/blob/filesystem/osinterface.go
- repo/blob/filesystem/osinterface_mock_test.go
- repo/blob/filesystem/osinterface_realos.go
- repo/blob/sftp/sftp_storage.go
When a sharded directory is missing do not attempt to create all
its parents, but only children of the repository root.
This way when a top-level directory is unmounted, we won't recreate
it unnecessarily.
This is implemented for filesystem and SFTP providers.
> feat(providers): improved sharded directory creation

- cli/command_repository_validate_provider.go
- internal/blobtesting/map.go
- internal/blobtesting/verify.go
- internal/providervalidation/providervalidation.go
- repo/blob/azure/azure_storage.go
- repo/blob/filesystem/filesystem_storage.go
- repo/blob/gcs/gcs_storage.go
- repo/blob/gcs/gcs_storage_test.go
- repo/blob/retrying/retrying_storage.go
- repo/blob/s3/s3_storage.go
- repo/blob/sftp/sftp_storage.go
- repo/blob/sharded/sharded.go
- repo/blob/storage.go
- repo/blob/webdav/webdav_storage.go
Today, executing a PutBlob operation will always overwrite a blob if it exists. It would be helpful for some customer workflows to be able to write blobs only if they don't exist (i.e. don't overwrite/recreate blobs). This PR expands the PutBlob API with an additional option `DoNotRecreate`, which toggles this feature. Note that not all backends support idempotent creates, so this PR also implements error logic to rejects such PutBlobs if they can't be executed.
> feat(providers): expand PutBlob API to allow for idempotent puts

- .github/workflows/provider-tests.yml
- repo/blob/b2/b2_storage.go
- repo/blob/retrying/retrying_storage.go
There was a small regression in #1654 - only in negative tests.
Also removed unnecessary retries on ErrUnsupportedPutBlobOption
+ switched provider test to run once per day, instead of 12 times/day.
> fix(providers): fixed b2 provider failure

- cli/command_repository_validate_provider.go
- internal/blobtesting/verify.go
- internal/providervalidation/providervalidation.go
- repo/blob/gcs/gcs_storage.go
- repo/blob/gcs/gcs_storage_test.go
Also simplified the validation test suite, which will check whether the provider supports `DoNotRecreate` or properly rejects it without external configuration.
@julio-lopez There were a number of suble issues there all stacked up behind "empty conditions" failure. They could only have been caught by running the test against actual GCS and were not easy to spot in the code review. 
We need to figure out how to run provider tests (which require credentials) as part of pull requests to catch those kinds of things early. There's an obvious security issue for untrusted PRs, but perhaps there's a way we can trigger these tests with access to secrets as one-off after eyeballing that PR can be trusted?
@adowair FYI
> fix(providers): fixed DoNotRecreate and tests for gcs

- BUILD.md
- app/public/electron.js
- app/public/server.js
- cli/app.go
- cli/command_server_start.go
- go.mod
- go.sum
- internal/cache/persistent_lru_cache.go
- internal/server/api_repo.go
- internal/server/server.go
- internal/serverapi/serverapi.go
- internal/uitask/uitask.go
- internal/uitask/uitask_manager.go
- tests/end_to_end_test/server_start_test.go
This allows KopiaUI server to start when the repository directory is not mounted or otherwise unavailable. Connection attempts will be retried indefinitely and user will see new `Initializing` page.
This also exposes `Open` and `Connect` as tasks allowing the user to see logs directly in the UI and cancel the operation.
Fixes #1643
> feat(kopiaui): connect to repository asynchronously on startup

- cli/app.go
- cli/command_repository_connect.go
- cli/command_repository_connect_from_config.go
- cli/command_repository_create.go
- cli/command_repository_repair.go
- cli/command_repository_set_parameters_test.go
- cli/command_repository_sync.go
- cli/storage_azure.go
- cli/storage_b2.go
- cli/storage_filesystem.go
- cli/storage_gcs.go
- cli/storage_inmemory.go
- cli/storage_inmemory_test.go
- cli/storage_providers.go
- cli/storage_rclone.go
- cli/storage_s3.go
- cli/storage_sftp.go
- cli/storage_webdav.go
- internal/repotesting/reconnectable_storage.go
- internal/repotesting/repotesting.go
This PR extends the cli App services interface to allow customizing the tests environments to append a custom storage provider at runtime. This will allow appending an in-memory storage provider for CLI tests that otherwise depend upon the local filesystem access. The PR also adds a reconnect-able storage provider which tests can use to connect to using the CLI:
```sh
kopia repo connect in-memory --UUID=XYZ
```
The UUID of the storage can be accessed using the reconnect able-storage ConnectionInfo() api. This refactor allows us to do these things:
- allows us to use more complex storage mocks like versioned / object locking maps to test retention settings for example
- potentially speed up CLI tests
- avoid filesystem leaving cruft from previous test crashes
> refactor(cli): An in-memory storage mock setup for CLI tests

- repo/blob/azure/azure_storage_test.go
- repo/blob/b2/b2_storage_test.go
- repo/blob/filesystem/filesystem_storage_test.go
- repo/blob/gcs/gcs_storage_test.go
- repo/blob/rclone/rclone_storage.go
- repo/blob/rclone/rclone_storage_test.go
- repo/blob/s3/s3_storage_test.go
- repo/blob/sftp/sftp_storage_test.go
- repo/blob/webdav/webdav_storage_test.go
v0.10.3 introduced a regression where RClone connections did not
work in KopiaUI but were ok in the CLI.
The root cause was #1691 which caused storage context to be closed
after opening the repository.
Added test that verifies that storage does not rely on the context
remaining open.
> fix(providers): fixed rclone connection in KopiaUI

- cli/command_repository_set_parameters.go
- cli/command_repository_set_parameters_test.go
- cli/command_repository_status.go
- repo/blobcfg_blob.go
- repo/change_password.go
- repo/content/content_formatting_options.go
- repo/format_block.go
- repo/initialize.go
- repo/maintenance/blob_gc_test.go
- repo/open.go
- repo/parameters.go
- repo/repository.go
- repo/repository_test.go
- tests/testenv/cli_inproc_runner.go
- tests/testenv/storage_inmemory.go
This PR enabled the CLI to set the rendition parameters after the repository has been initialized.
```sh
$ kopia repository set-parameters --password 12345678 --config-file /tmp/kopia/repository.config --retention-mode GOVERNANCE --retention-period 24h
- setting storage backend blob retention period to 24h0m0s.
- setting storage backend blob retention mode to GOVERNANCE.
NOTE: Repository parameters updated, you must disconnect and re-connect all other Kopia clients.
```
With unsupported backends:
```sh
$ kopia repository set-parameters --password 12345678 --config-file /tmp/kopia/repository.config --retention-mode GOVERNANCE --retention-period 24h
- setting storage backend blob retention period to 24h0m0s.
- setting storage backend blob retention mode to GOVERNANCE.
ERROR error setting …
```
> feat(cli): allow changing retention parameters from cli

- .chglog/config.yml
- .github/workflows/check-pr-title.yml
- cli/command_policy_set.go
- cli/command_policy_set_retention.go
- cli/command_policy_show.go
- snapshot/policy/optional.go
- snapshot/policy/policy.go
- snapshot/policy/policy_manager_test.go
- snapshot/policy/policy_merge.go
- snapshot/policy/policy_merge_test.go
- snapshot/policy/policy_tree.go
- snapshot/policy/retention_policy.go
- snapshot/policy/retention_policy_test.go
- tests/end_to_end_test/server_start_test.go
This is a safety measure which addresses P0 improvement for #1732.
Given that retention policies that retain nothing make no sense, this is not considered a breaking change.
> fix(snapshots): treat empty retention policy as retaining ALL, not NONE

- repo/content/content_upgrade_lock.go
- repo/content/content_upgrade_lock_test.go
Upgrade lock intent will eventually be added to the Kopia format blob on the repository. This will be watched by all the Kopia clients for communicating the upgrade proposal. The Lock intent definition described In this PR sets the various upgrade parameters (drain timeouts, polling interval etc) which will allow the upgrade owner to start executing the readers/writers draining protocol.
Design REF: https://docs.google.com/document/d/1zIghQc4i4vJSANjSDBOvjzMiqnZSEp1cCasxSUkltSk/edit#heading=h.khston2oxmxy
POC PR: https://github.com/kopia/kopia/pull/1622
> feat(general): Upgrade Lock intent definitions

- site/content/docs/Installation/_index.md
Since we now have official kopia formula in the `homebrew-core` repo,
dedicated `kopia` TAP is no longer needed (we will keep publishing to
it for a while so it's available as a fallback).
Fixes #1728
> docs(site): update homebrew installation instructions

- go.mod
- go.sum
- internal/server/api_snapshots.go
- internal/server/api_snapshots_test.go
- internal/server/server.go
- internal/serverapi/serverapi.go
https://user-images.githubusercontent.com/249880/152926565-2d3186d2-7989-4482-bcbc-9b20659745dd.mp4
> feat(ui): support for editing pins and description

- .codecov.yml
- .github/workflows/provider-tests.yml
- cli/app.go
- cli/storage_gdrive.go
- go.sum
- internal/retry/retry.go
- repo/blob/gdrive/file_id_cache.go
- repo/blob/gdrive/gdrive_options.go
- repo/blob/gdrive/gdrive_storage.go
- repo/blob/gdrive/gdrive_storage_test.go
Hi @jkowalski,
I'm requesting early review for this feature before I finish up with tests and documentation. This PR implements https://github.com/kopia/kopia/issues/90 and passes `validate-provider`.
The implementation strategy is the one we discussed in https://github.com/kopia/kopia/issues/90#issuecomment-1025507405:
* FileIdCache: A BlobId -> FileId map is put in place to speed up file look ups.
* GetBlob / GetBlobMetadata: Use exact name match with aggressive retrying (100ms x 3 times). 
* ListBlobs: Use name prefix search with a cap of 26 characters (Drive limitation). Additionally, we search through FileIdCache for any local matches in case the Drive-side index is not stable yet.
I would like your input on:
* The general implementation strategy - is it sensible? Don't worry about …
> feat(providers): Add Google Drive support.

- internal/workshare/workshare_pool.go
- internal/workshare/workshare_test.go
- internal/workshare/workshare_waitgroup.go
- snapshot/snapshotfs/upload.go
Previously directories were walked strictly sequentially which means
we could never be uploading data from multiple directories in parallel,
even if they had just a few files each.
This change switches to using the new `workshare` utility which improves
parallelism. It also reduces memory allocations, goroutine creations
and overall memory usage when taking large snapshots, while increasing
CPU utilization.
Tests on realistic directory structures show huge speed-ups during cold
snapshots (without any metadata caching:)
Photo library - 160GB, files:41717 dirs:1350
Before: 3m11s
After: 1m50s
Total time reduction: 43%
Working code directory - 30.7 GB files:194560 dirs:42455
Before: 55s
After: 25s
Total time reduction: 55%
> feat(snapshots): big upload performance improvements by parallelizing directory traversal

- cli/command_snapshot_list.go
- cli/command_snapshot_storage_stats_test.go
- snapshot/manifest.go
- snapshot/snapshotfs/snapshot_storage_stats.go
- snapshot/snapshotfs/snapshot_storage_stats_test.go
For #1722
Related #1755
Usage `kopia snapshot list --storage-stats`
The data is based on walking the snapshot list either chronologically or in reverse (when `--reverse` is passed). This is more costly than regular list, thus slower. For each snapshot we emit new bits of information:
* `new-data:X B`
* `new-files:N`
* `new-dirs:N`
* `compression:X%`
```
2020-12-31 23:50:00 PST k7440c27bbddf3b7ee40f546b28bb7baa 572.5 KB drwxr-xr-x files:140 dirs:23 new-data:403.6 KB new-files:51 new-dirs:23 compression:0% (monthly-11,annual-3)
2021-01-31 23:46:58 PST k1ff379103e7a8b413344b44007fa95ed 640.9 KB drwxr-xr-x files:151 dirs:25 new-data:501.5 KB new-files:77 new-dirs:25 compression:0% (monthly-10)
2021-02-28 22:50:02 PST k0c8787879b81d39c72c85b82313684ab 680 KB drwxr-xr-x files:182 dirs:35 …
```
> feat(cli): added `snapshot list` flags: `--storage-stats` and `--reverse`

- internal/repotesting/repotesting.go
- internal/retry/retry.go
- repo/blob/beforeop/beforeop.go
- repo/open.go
- repo/repository_test.go
- repo/upgrade_lock_test.go
Upgrade lock monitor for Kopia does two things:
- Monitors the upgrade lock during runtime before each operation. This is protected by a cache-refresh timeout so that we do not do a hard pull on ever Get/Put etc or impact performance.
- The repository open() operation will wait poll and block on the upgrade lock until timeout.
POC PR: https://github.com/kopia/kopia/pull/1622
Monitor Design: https://docs.google.com/document/d/1zIghQc4i4vJSANjSDBOvjzMiqnZSEp1cCasxSUkltSk/edit#heading=h.khston2oxmxy
> feat(general): Upgrade lock retries & monitoring during open & write sessions

- tools/robustness-job.sh
Before running a robustness test using tools/robustness_job.sh, it
may be useful to perform some other work or to set some environment
variables to prepare the environment/test repo (for example, to clean
up files, redirect input/output). This commit adds an additional
optional argument TEST_RC, to be consumed as an environment variable.
If TEST_RC is set, then the script sources its value before launching
the robustness job.
> test(infra): Source an RC file before launching robustness job

- site/content/docs/Contribution guidelines/_index.md
To save reviewers' time and CI/CD cloud spend (if any), this commit adds
a short checklist to the contribution guidelines, outlining some checks
developers can run locally against their code before creating/updating
a pull request on Github.
> docs(site): Add PR checklist to contribution guidelines

- tools/robustness-job.sh
If the TEST_RC environment variable is unset, the robustness_job.sh
script exits prematurely due to an unbound variable error, instead of
starting the robustness job without that argument. This commit
evaluates said variable conditionally so that the script doesn't fail.
> fix(infra): Fix failed robustness job script if TEST_RC unset

- internal/repotesting/repotesting.go
- repo/open.go
This was broken in #1758 by holding onto a context beyond its intended lifetime.
More specifically `upgradeLockMonitor` was using `ctx` in a closure that lasted beyond the lifetime of the function and when the original context was canceled (which sometimes happens, e.g. in KopiaUI), the lock monitor would stop working.
Fixes #1796
> fix(repository): fixed 'context canceled' regression

- repo/blob/beforeop/beforeop.go
- repo/blob/beforeop/beforeop_test.go
- repo/open.go
- repo/repository_test.go
- repo/upgrade_lock_test.go
This helps eliminate a class of bugs where 'ctx' used in a callbacks
is captured from a closure variable/parameter, which is almost never
correct, because it can be canceled while the beforeop wrapper is
still alive.
Follow-up for #1796.
> chore(repository): added context to beforeop callbacks

- cli/command_server_start.go
- internal/ctxutil/detach.go
- internal/epoch/epoch_manager.go
- internal/repotesting/repotesting.go
- internal/server/server_test.go
- repo/open.go
- tests/end_to_end_test/api_server_repository_test.go
Instead of ignoring context cancelation in Open(), ensure we don't
spawn goroutines that might be canceled.
> refactor(repository): better context cancelation handling

- internal/testutil/testutil.go
- repo/content/content_manager.go
- snapshot/snapshotfs/upload_test.go
- tests/end_to_end_test/snapshot_migrate_test.go
This issue was reported on Slack by Ming. Thanks!
This is particularly easy to reproduce when compression is used.
> fix(repository): fix deduplication when snapshotting identical files in parallel

- internal/server/api_cli.go
- internal/server/api_content.go
- internal/server/api_estimate.go
- internal/server/api_manifest.go
- internal/server/api_mount.go
- internal/server/api_object_get.go
- internal/server/api_paths.go
- internal/server/api_policies.go
- internal/server/api_repo.go
- internal/server/api_restore.go
- internal/server/api_snapshots.go
- internal/server/api_sources.go
- internal/server/api_tasks.go
- internal/server/api_ui_pref.go
- internal/server/api_user.go
- internal/server/grpc_session.go
- internal/server/request_context.go
- internal/server/server.go
- internal/server/server_authz_checks.go
- internal/server/server_mount_manager.go
- internal/server/source_manager.go
- snapshot/stats.go
This removes big shared lock held for for the duration of each request
and replaces it with trivially short lock to capture the current
state of the server/repository before passing it to handlers.
Handlers are now limited to only accessing a small subset of Server
functionality to be able to better reason about them.
> refactor(repository): major server code refactoring

- cli/command_restore.go
- internal/iocopy/copy.go
- internal/sparsefile/sparsefile.go
- internal/sparsefile/sparsefile_test.go
- internal/stat/stat_bsd.go
- internal/stat/stat_test.go
- internal/stat/stat_unix.go
- internal/stat/stat_windows.go
- internal/testutil/testutil.go
- snapshot/restore/local_fs_output.go
- tests/end_to_end_test/restore_test.go
Implements support for restoring sparse files from snapshots.
When specifying `--mode=sparse` in a `snapshot restore`
command, Kopia will make a best effort to make sure the underlying
filesystem allocates the minimum amount of blocks needed to persist
restored files. In other words, enabling this feature will "force"
all restored files to be sparse-blocks of zero bytes in the source
file should not be allocated. This feature will only be enabled if:
- the OS is not Windows
- `--write-files-atomically` is not also selected
Otherwise, the flag will be silently ignored. Partially addresses the
concern in #540.
> feat(snapshots): support restoring sparse files

- internal/cache/content_cache_data.go
- repo/content/content_manager_lock_free.go
- repo/content/content_manager_test.go
We were incorrectly assigning the same content cache key regardless of
the storage format of the content (compression format, etc.)
This means that if a content has both compressed and non-compressed
entry in the index, it would sometimes get cached incorrectly
and the subsequent reads would fail.
Clearing the cache would fix the issue - this change appends
format-specific suffix to cache keys, so that clearing the cache is not
needed.
Huge thanks to Mark Derricutt who helped get to the bottom of this
on Slack.
Fix #1843
> fix(repository): fixed 'unable to get content data and info'

- cli/command_repository_status.go
- repo/blob/storage.go
- repo/repository.go
The connected repository's backing storage capacity and available
space can be now retrieved from `kopia repository status`. In text
format, these fields are printed in a human friendly form (MB, GB).
In JSON mode (`--json`), they are output as bytes.
> feat(cli): show storage capacity in repo status

- repo/manifest/committed_manifest_manager.go
This can usually help open corrupted repository and partially restore data.
> feat(cli): added KOPIA_IGNORE_MALFORMED_MANIFEST_CONTENTS

- .github/workflows/dependency-review.yml
This Action will scan dependency manifest files that change as part of a Pull Request, surfacing known-vulnerable versions of the packages declared or updated in the PR. Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable packages will be blocked from merging.
[Source repository](https://github.com/actions/dependency-review-action)
[Documentation](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement)
> build(ci): Dependency Review Action

- site/content/docs/Mounting/_index.md
windows 2012 not install WebClient by default
> docs(site): update documentation about WebDAV in Windows

- tests/tools/fswalker/fswalker.go
The directory size is affected by the underlying filesystem. Filter directory size check to make the tests more robust.
> test(general): Ignore directory size check before and after restore

- cli/command_content_delete.go
- repo/content/committed_content_index.go
- repo/content/content_manager.go
- repo/content/content_manager_test.go
- tests/end_to_end_test/content_info_test.go
This allows low-level hiding of entries in the index, which makes them completely invisible instead of just marking for deletion.
For #1906
> feat(cli): added 'content delete --forget' flag

- cli/command_content_delete.go
- repo/content/committed_content_index.go
- repo/content/content_manager.go
- repo/content/content_manager_test.go
- tests/end_to_end_test/content_info_test.go
This reverts commit d990af4dc21687867f07b990fdc6119a9b2f7a40.
Discussed with @julio-lopez, we don't need this concept after all.
> feat(cli): REVERT added 'content delete --forget' flag (#1932)

- repo/blob/s3/s3_storage.go
Recently #1942 was merged disabling minio multipart
uploads for S3 storage backend. This commit adds
a comment explaining the reasoning for that change.
Since Kopia already splits snapshot content into
(small) blobs for upload, there is no need to further
split those for multipart uploading.
> chore(providers): Add comment explaining disabling multipart upload

- internal/osexec/osexec.go
- internal/osexec/osexec_test.go
- internal/osexec/osexec_unix.go
- internal/osexec/osexec_windows.go
- repo/blob/rclone/rclone_storage.go
Based on https://stackoverflow.com/questions/33165530/prevent-ctrlc-from-interrupting-exec-command-in-golang
Fixes #1934
> feat(providers): ensure Ctrl-C is not passed to rclone

- cli/command_repo_throttle_test.go
- cli/command_repository.go
- cli/command_repository_throttle.go
- cli/command_repository_throttle_get.go
- cli/command_repository_throttle_set.go
- cli/command_server.go
- cli/command_server_control_test.go
- cli/command_server_throttle.go
- cli/command_server_throttle_get.go
- cli/command_server_throttle_set.go
- cli/throttle_get.go
- cli/throttle_set.go
- internal/server/server.go
- internal/testutil/testutil.go
- repo/blob/throttling/throttler.go
- repo/blob/throttling/throttling_semaphore.go
- repo/blob/throttling/throttling_semaphore_test.go
- repo/blob/throttling/throttling_storage.go
- repo/blob/throttling/throttling_storage_test.go
- repo/local_config.go
- repo/open.go
- repo/repository.go
Supported are:
```
$ kopia throttle set \
--download-bytes-per-second=N | unlimited
--upload-bytes-per-second=N | unlimited
--read-requests-per-second=N | unlimited
--write-requests-per-second=N | unlimited
--list-requests-per-second=N | unlimited
--concurrent-reads=N | unlimited
--concurrent-writes=N | unlimited
```
To change parameters of a running server use:
```
$ kopia server throttle set \
--address=<server-url> \
--server-control-password=<password> \
--download-bytes-per-second=N | unlimited
--upload-bytes-per-second=N | unlimited
--read-requests-per-second=N | unlimited
--write-requests-per-second=N | unlimited
--list-requests-per-second=N | unlimited
--concurrent-reads=N | unlimited
--concurrent-writes=N | unlimited
```
> feat(cli): added CLI for controlling throttler

- .golangci.yml
- fs/entry.go
- fs/localfs/local_fs.go
- fs/localfs/shallow_fs.go
- fs/virtualfs/virtualfs.go
- internal/mockfs/mockfs.go
- snapshot/snapshotfs/all_sources.go
- snapshot/snapshotfs/repofs.go
- snapshot/snapshotfs/source_directories.go
- snapshot/snapshotfs/source_snapshots.go
As the first part of #1955 add an interface method that uses callbacks to process directory entries. Right now it defaults to calling the underlying `Readdir` implementation and then iterating over that result internally
> feat(snapshots): Add callback-based iteration function to Directory interface

- repo/maintenance/maintenance_run.go
Avoid adding an entry to the maintenance schedule for a maintenance run that may not execute at all.
Also, avoids the potential race of overwriting the schedule of an already running maintenance task.
> refactor(general): acquire maintenance lock before updating schedule

- go.mod
- go.sum
- repo/content/committed_content_index.go
- repo/content/committed_content_index_disk_cache.go
- repo/content/committed_content_index_mem_cache.go
- repo/content/content_index_recovery.go
- repo/content/content_manager_indexes.go
- repo/content/index/index.go
- repo/content/index/index_encode_util.go
- repo/content/index/index_v1.go
- repo/content/index/index_v2.go
- repo/content/index/merged_test.go
- repo/content/index/packindex_test.go
- repo/content/index_blob_manager_v0.go
Previous mmap implementation only allowed io.ReaderAt API
this one allows direct access to the underlying bytes which helps
remove a bunch of buffers, copying and allocation in index parsing.
> feat(repository): switched to using go-mmap for indexes

- cli/app.go
- cli/command_repository.go
- cli/command_repository_connect.go
- cli/command_repository_create.go
- cli/command_repository_repair.go
- cli/command_repository_sync.go
- cli/inproc.go
- cli/observability_flags.go
- cli/observability_flags_test.go
- tests/testenv/cli_test_env.go
When enabled, metrics are pushed to the provided Prometheus Push
Gateway at the start and end of each command and periodically every
few seconds.
```
--metrics-push-addr=http://address:port
--metrics-push-interval=5s
--metrics-push-job=kopia
--metrics-push-grouping=a:b --metrics-push-grouping=c:d
--metrics-push-username=user
--metrics-push-password=pass
```
> feat(cli): added flags for pushing kopia metrics

- fs/ignorefs/ignorefs.go
- internal/mockfs/mockfs.go
- snapshot/snapshotfs/repofs.go
- snapshot/snapshotfs/upload.go
- snapshot/snapshotfs/upload_test.go
This removes dependency on `fs.Directory.Readdir()` from the Uploader, ignorefs and repofs so instead of reading entire directory ahead of time, the contents can be streamed using `IterateEntries()`.
This both reduces memory consumption by quite a lot and speeds up snapshot creation by a tiny bit:
Backing up Kopia git enlistment (2.8 GB files:74722 dirs:12352):
* before (680e3f29bba59e76d118d877afea8c70fd782dcf) : 7.4s     420.422 MB RAM
* after:    7.2s     358.328 MB RAM
Note that this temporarily disables asynchronous uploads of singular large files, since it wasn't compatible with asynchronous iteration model. This will be restored and further improved by #1984 following this one.
For #1955
> feat(snapshots): streaming upload support

- .github/workflows/endurance-test.yml
- .github/workflows/provider-tests.yml
- .github/workflows/stress-test.yml
There's a lot of CI spam in my email because some of these tests occasionally fail. This limits these flows to run only on the upstream repository since they have a schedule. This also potentially saves some GH action cycles on everyone's respective accounts.
> chore(ci): restrict GH actions for provider and stress tests to upstream repository.

- snapshot/snapshotgc/gc.go
- snapshot/snapshotmaintenance/snapshotmaintenance.go
- snapshot/snapshotmaintenance/snapshotmaintenance_test.go
Previously, the reference time used to determine whether a content had been recently created would change throughout a snapshot GC execution. For long-running GC tasks, this non-deterministically shrank the safety window specified in `MinContentAgeSubjectToGC`.
Now, the maintenance starting time is used as a fix reference for the safety check.
> fix(general): use a fixed time for protecting newly created content

- go.sum
- snapshot/snapshotfs/upload.go
This fixes memory usage increase from #1988
> refactor(snapshots): disable fine-grained Span creation when tracing is disabled

- internal/workshare/workshare_test.go
- internal/workshare/workshare_waitgroup.go
- snapshot/snapshotfs/dir_rewriter.go
- snapshot/snapshotfs/snapshot_tree_walker.go
- snapshot/snapshotfs/upload.go
The deadlock was caused by not properly waiting for all asynchronous
work to complete before closing the worker pool.
Introduced `workshare.AsyncGroup.Close()` and some assertions.
Fixes #2019
> fix(snapshots): fixed random deadlock when Uploader results in a failure

- site/content/docs/Repositories/_index.md
Updated directions for Google Cloud access. You don't need Google Cloud SDK.
> docs(site): updated directions for Google Cloud access

- repo/content/content_manager.go
- repo/content/content_manager_lock_free.go
- repo/content/index/id.go
- repo/content/index/id_test.go
- repo/logging/logging_buf.go
- repo/logging/logging_buf_test.go
This fixes regression introduced in #1960.
Tested by backing up Linux 5.14.8 source on M1 Mac (average of 15 runs):
Before: duration=6.7s avg_heap_objects=7411657 avg_heap_bytes=871794888
After: duration=5.6s (17% faster) avg_heap_objects=5947800 (20% less) avg_heap_bytes=795762120 (9% less)
> chore(repository): reduced memory allocations when logging content.ID

- repo/content/committed_content_index.go
- repo/content/committed_content_index_disk_cache.go
Fixed regression caused by #1980
Switching to new mmap library uncovered a bug where we were not properly
closing indices that are no longer in use, since previous mmap had
a finalizer defined to do so.
> fix(repository): fixed stress test caused by index leaking file handles

- .github/dependabot.yml
Allow more frequent update while limiting the number of open PRs to 1.
Similarly, for GHA deps.
> chore(deps): update dependabot frequency for go

- repo/content/content_manager.go
- repo/content/content_manager_lock_free.go
- snapshot/snapshotfs/upload_test.go
This fixes a performance regression where all blob writes were serialized under a lock introduced by mistake in https://github.com/kopia/kopia/pull/1838.
Added regression test to prevent this in the future.
> refactor(repository): re-enabled parallel uploads of blobs

- cli/command_snapshot_estimate.go
- fs/entry.go
- fs/localfs/local_fs.go
- fs/localfs/shallow_fs.go
- fs/virtualfs/virtualfs.go
- fs/virtualfs/virtualfs_test.go
- internal/mockfs/mockfs.go
- internal/server/api_estimate.go
- snapshot/snapshotfs/all_sources.go
- snapshot/snapshotfs/estimate.go
- snapshot/snapshotfs/estimate_test.go
- snapshot/snapshotfs/repofs.go
- snapshot/snapshotfs/source_directories.go
- snapshot/snapshotfs/source_snapshots.go
- snapshot/snapshotfs/upload_scan.go
- snapshot/snapshotfs/upload_test.go
part of #1955 
Create `virtualfs.StreamingDirectory` that allows users to dynamically materialize entries in a directory. Combined with previous changes, this allows users to begin an upload without knowing ahead of time what all the entries in the file hierarchy will be
> feat(snapshots): Allow users to dynamically create entries in a directory during an upload

- cli/command_repository_set_parameters_test.go
- go.mod
- go.sum
This PR fixes any errors thrown by standard `time` library while parsing string that mentions days and weeks.
Fix was added in upstream kingpin library https://github.com/alecthomas/kingpin/pull/329 and would now be consumed in Kopia with this version bump.
The fix is also validated with an updated unit test.
Fixes #1972
> fix(cli): update kingpin version to fix --retention-period and other time.Duration type flags

- cli/command_repository_set_parameters_test.go
This PR adds another test case that sets number of days using a --retention-period flag
Further validates fix https://github.com/kopia/kopia/pull/2054 for bug https://github.com/kopia/kopia/issues/1972
> test(cli): add test case for days in --retention-period flag

- BUILD.md
- Makefile
- tools/localhtmlui.work
This allows building of KopiaUI with local changes make to `htmlui` repository.
In order for this to work you must have 3 repositories checked out side-by-side:
* https://github.com/kopia/kopia
* https://github.com/kopia/htmlui
* https://github.com/kopia/htmluibuild
> feat(infra): added `make kopia-ui-with-local-htmlui-changes`

- .golangci.yml
The `run` section was repeated.
`run.go` should be a string.
nits:
- alphabetically sort filters and checks
- alphabetically sort stanzas in `linters-settings` section
> chore(ci): fix golangci.yml

- cli/command_policy_set.go
- cli/command_policy_set_upload.go
- cli/command_policy_set_upload_test.go
- cli/command_policy_show.go
- repo/api_server_repository.go
- repo/grpc_repository_client.go
- repo/object/indirect.go
- repo/object/object_manager.go
- repo/object/object_reader.go
- repo/object/object_writer.go
- repo/repository.go
- snapshot/policy/optional.go
- snapshot/policy/policy_merge.go
- snapshot/policy/policy_merge_test.go
- snapshot/policy/policy_tree.go
- snapshot/policy/upload_policy.go
- snapshot/snapshotfs/upload.go
- snapshot/snapshotfs/upload_test.go
This is controlled by an upload policy which specifies the size threshold above which indvidual files are uploaded in parts and concatenated.
This allows multiple threads to run splitting, hashing, compression and encryption in parallel, which was previously only possible across multiple files, but not when a single file was being uploaded.
The default is 2GiB for now, so this feature only kicks in for very larger files. In the future we may lower this.
Benchmark involved uploading a single 42.1 GB file which was a VM disk snapshot of fresh Ubuntu installation (fresh EXT4 partition with lots of zero bytes) to a brand-new filesystem repository on local SSD of M1 Pro Macbook Pro 2021.
* before: 59-63s (~700 MB/s)
* after: 15-17s  (~2.6 GB/s)
> feat(snapshots): improved performance when uploading huge files

- internal/serverapi/serverapi.go
Also fixes #2060.
In general, this PR provides a server API to save the pageSize as UI preference. 
Other changes will be made in kopia/htmlui.
> feat(ui): Save page size

- .github/workflows/make.yml
- .github/workflows/tests.yml
The docker images we used were discontinued upstream, we either need to:
* drop 32-bit ARM validation, keep publishing builds since they
are cross-compiled from AMD64 Linux anyway
* drop 32-bit ARM validation and releases altogether, looking at stats
there are only tiny amounts of 7-day active users who pull from the
APT repository
* find a replacement for this runner
> chore(ci): temporarily disable ARMHF runners

- fs/entry.go
- fs/localfs/local_fs.go
- fs/virtualfs/virtualfs.go
- internal/mockfs/mockfs.go
- snapshot/snapshotfs/all_sources.go
- snapshot/snapshotfs/repofs.go
- snapshot/snapshotfs/source_directories.go
- snapshot/snapshotfs/source_snapshots.go
This is not used yet, but will be used to avoid allocation in performance-critical portions of the upload.
> feat(snapshots): added fs.Entry.Close which can be used to release any resources

- fs/localfs/local_fs.go
- fs/localfs/local_fs_pool.go
- go.mod
- go.sum
- internal/freepool/freepool.go
- snapshot/snapshotfs/estimate.go
- snapshot/snapshotfs/upload.go
This avoids allocations of entries as large directories are traversed.
Backing up 100k small files in a single directory:
```
duration: current:8.1 baseline:8.6 change:-5.7 %
avg_heap_objects: current:7330688.9 baseline:7463750.6 change:-1.8 %
avg_heap_bytes: current:829248496.6 baseline:864880473.2 change:-4.1 %
avg_ram: current:159.3 baseline:159.1 change:+0.1 %
max_ram: current:283.2 baseline:285.4 change:-0.8 %
avg_cpu: current:153.1 baseline:143.6 change:+6.7 %
max_cpu: current:295.6 baseline:292.4 change:+1.1 %
```
Backing up Linux 5.14.8 using --parallel=4:
```
duration: current:6.0 baseline:6.0 change:-0.0 %
avg_heap_objects: current:5654431.1 baseline:5845078.3 change:-3.3 %
avg_heap_bytes: current:764526988.2 baseline:806833320.4 change:-5.2 %
avg_ram: current:218.2 …
```
> feat(snapshots): added free pool of localfs entries

- internal/gather/gather_write_buffer_chunk_test.go
- internal/logfile/logfile.go
- internal/logfile/logfile_test.go
- internal/testlogging/printf.go
- internal/zaplogutil/zaplogutil.go
- repo/content/committed_content_index.go
- repo/content/internal_logger.go
- repo/logging/logging.go
- repo/logging/logging_test.go
Turns out standard ConsoleEncoder is not optimized at all and we're
emitting up to 8 log entries per file. This change avoids massive
amount of allocations and brings in some latency reduction.
Backing up 100k files in a flat directory:
```
duration: current:7.8 baseline:7.9 change:-1.0 %
repo_size: current:1019954521.4 baseline:1019976318.9 change:-0.0 %
num_files: current:58.0 baseline:58.0 change:0%
avg_heap_objects: current:6682141.0 baseline:7508631.3 change:-11.0 %
avg_heap_bytes: current:845404672.0 baseline:867325413.9 change:-2.5 %
avg_ram: current:156.5 baseline:159.1 change:-1.7 %
max_ram: current:278.3 baseline:287.2 change:-3.1 %
avg_cpu: current:153.8 baseline:156.4 change:-1.7 %
max_cpu: current:298.4 baseline:297.1 change:+0.4 %
```
Backing up Linux 5.18.4:
```
duration: …
```
> feat(general): implemented custom log encoder for ZAP

- site/content/docs/Installation/_index.md
We link to this page when telling people to download Kopia (see the download button at https://kopia.io), so it will be less confusing if we rename the page to "Download & Installation". We don't need to change the URL, just the title.
> docs(site): Changing Page Title from Installation to Download & Installation

- cli/command_snapshot_list.go
- cli/command_snapshot_list_test.go
This is caused by a fix where fs.Directory was incorrectly reporting
its size == total size of all files in all subdirectories and
`snapshot list` was relying on that.
Fixes #2144
> fix(cli): fixed snapshot sizes in the snapshot list

- app/public/electron.js
Just removing the extra space
Related: https://github.com/kopia/htmlui/pull/84
> fix(ui): "Kopia UI" to "KopiaUI"

- cli/command_cache_set.go
- cli/command_cache_set_test.go
This was caused by a default `-1ns` which is no longer supported in latest Kingpin.
The effect was that `kopia cache set` without `--max-list-cache-duration` would fail. Unforutnately test was passing that flag so it was missed during the upgrade of dependency.
This was likely caused by https://github.com/alecthomas/kingpin/pull/329
> fix(cli): fixed 'cache set' CLI regression due to kingpin change

- cli/command_snapshot_create.go
- snapshot/snapshotfs/upload.go
- tests/end_to_end_test/snapshot_create_test.go
Also hide the flag, since it's not recommended to be tweaked anyway.
The value of <=45m is very important for safety of the garbage collection algorithms - too long an interval between checkpoints could mean that GC treats contents in the middle of being uploaded as unused, because they are not reachable from any snapshots or checkpoints.
Fixes #2193
> feat(cli): BREAKING CHANGE ensure `--checkpoint-interval` is <=45min

- repo/content/content_formatting_options.go
- repo/local_config.go
- repo/repository.go
- repo/upgrade_lock.go
- repo/upgrade_lock_intent.go
- repo/upgrade_lock_intent_test.go
- repo/upgrade_lock_test.go
There are no real `content` dependencies here and JSON at the repo level can store the upgrade lock in exactly the same way.
> refactor(repository): moved upgrade lock intent from content to repo

- snapshot/snapshotgc/gc.go
Noticed that running maintenance produces logs like:
```text
...
GC found 32773 unused contents (12.7 GiB bytes)
...
```
Seems like the units are already suffixed appropriately, so the 'bytes' in the string is not required.
> fix(cli): content sizes are already suffixed, so 'bytes' in the string is redundant.

- repo/blob/s3/s3_storage.go
When kopia is used as a SDK for applications running inside AWS, IAM credentials cannot be directly leveraged. This PR addresses that need. Now, when running inside AWS environment, if instance role allows access to s3, then kopia will by default have s3 access (only via SDK). 
In the future, this can be done via CLI too.
> feat(providers): add AWS IAM as a credential provider for s3 storage

- repo/blob/s3/s3_storage.go
* add AWS IAM as a credential provider for s3 storage
* Update s3_storage.go
Co-authored-by: Jarek Kowalski <jaak@jkowalski.net>
> feat(providers): add AWS IAM as a credential provider for s3 storage (tested in #2213)

- cli/app.go
- cli/command_repository.go
- cli/command_repository_set_parameters_test.go
- cli/command_repository_status.go
- cli/command_repository_upgrade.go
- cli/command_repository_upgrade_test.go
- cli/config.go
- cli/suite_test.go
- internal/repotesting/repotesting.go
- repo/blob/retrying/retrying_storage.go
- repo/content/content_formatting_options.go
- repo/content/content_manager.go
- repo/initialize.go
- repo/local_config.go
- repo/maintenance/suite_test.go
- repo/open.go
- repo/repository.go
- repo/suite_test.go
- repo/upgrade_lock.go
- repo/upgrade_lock_test.go
- snapshot/snapshotmaintenance/suite_test.go
- tests/compat_test/compat_test.go
- tests/end_to_end_test/suite_test.go
This change lets any Kopia repository owner set an upgrade intent on the repository to enable the draining protocol based upgrade coordination between multiple clients of Kopia and help gain an upgrade quorum before actually upgrading the repository.
- A dedicated upgrade CLI with the ability to set a new upgrade lock, update an existing lock and also revoke a previous orphaned lock.
- The change maintains backwards compatibility with existing `set-parameters --upgrade` based upgrade mechanism. However, it is encouraged to use the new CLI with new projects.
- Adding a new upgrade status section to the Kopia repository status CLI to allow any user to check for an ongoing upgrade status.
- Increments the max supported format version from 2 to 3. Version 3 repository format is not a data …
> feat(cli): New Upgrade CLI / Switch to Format Version 3 (upgrade coordination)

- cli/command_repository_set_parameters.go
- cli/command_repository_status.go
- cli/command_repository_upgrade.go
- internal/epoch/epoch_manager.go
- internal/epoch/epoch_manager_test.go
- internal/server/api_repo.go
- internal/server/grpc_session.go
- repo/content/committed_read_manager.go
- repo/content/content_formatter_test.go
- repo/content/content_formatting_options.go
- repo/content/content_index_recovery.go
- repo/content/content_manager.go
- repo/content/content_manager_indexes.go
- repo/content/content_manager_lock_free.go
- repo/content/content_manager_test.go
- repo/content/content_reader.go
- repo/content/encrypted_blob_mgr.go
- repo/content/encrypted_blob_mgr_test.go
- repo/content/index_blob_manager_v0.go
- repo/content/index_blob_manager_v0_test.go
- repo/content/index_blob_manager_v1.go
- repo/content/internal_logger.go
- repo/content/sessions.go
- repo/maintenance/content_rewrite.go
- repo/manifest/manifest_manager_test.go
- repo/open.go
- repo/repository.go
- repo/upgrade_lock_test.go
- tests/stress_test/stress_test.go
Instead of passing static content.FormattingOptions (and caching it)
we now introduce an interface to provide its values.
This will allow the values to dynamically change at runtime in the
future to support cases like live migration.
> refactor(repository): introduce interface for reading FormattingOptions

- cli/command_blob_list.go
- cli/command_index_recover.go
- cli/command_repository_set_parameters.go
- cli/command_repository_upgrade.go
- repo/content/committed_read_manager.go
- repo/content/content_index_recovery_test.go
- repo/content/content_manager.go
- repo/content/content_manager_test.go
- repo/content/index_blob_manager_v0.go
- repo/content/index_blob_manager_v0_test.go
- repo/open.go
- repo/repository_test.go
- tests/compat_test/compat_test.go
When upgrading from legacy to epoch manager-based index, we will write
an intentionally-corrupted index blob, such that old clients won't be
able to understand it when they read the repository index using legacy
format.
The error message emitted by very old clients is not great, but it's
safer to do that rather than corrupt the repository.
Note that this additional safety has a delay of up to 15 minutes
which is the time required for old clients to stop relying on index list
cache in case of very long-running snapshots, server or KopiaUI.
> feat(cli): improved safety of v1->v2 index format upgrade

- cli/app.go
- cli/command_repository_set_parameters.go
- cli/command_repository_set_parameters_test.go
- cli/command_repository_status.go
- cli/command_repository_upgrade.go
- cli/command_server_start.go
- cli/config.go
- cli/inproc.go
- internal/feature/feature.go
- internal/feature/feature_test.go
- repo/local_config.go
- repo/open.go
- repo/parameters.go
- repo/repository.go
- site/cli2md/cli2md.go
This is intended for future compatibility to be able to reliably
stop old kopia client from being able to open a repository when
the old code does not understand new `required feature`.
Required features are checked on startup and periodically using the
same method as upgrade lock, where they will return errors during blob
operations.
> feat(repository): added `required features` to the repository

- cli/app.go
Currently, passing --profile-* to benchmarks does not work. This fixes that.
> feat(cli): allow to profile benchmarks

- fs/virtualfs/virtualfs.go
- fs/virtualfs/virtualfs_test.go
- snapshot/snapshotfs/upload.go
- snapshot/snapshotfs/upload_test.go
Main changes in this PR:
* allow user to set mod time on a `StreamingFile` if they want
* set `StreamingFile` mod time when the struct is created, not in the uploader when the directory manifest entry is added
* relax metadata equality checks for `StreamingFile` in the uploader when looking for cached files
Together these allows the uploader to skip reuploading `StreamingFile` content if the file has the same mod time, mode, and owner. Size is no longer checked as that is only populated after the `StreamingFile` has been completely uploaded
This patch is not expected to change the behavior of backups that don't explicitly set the mod time as `StreamingFile` will default to using the current time. This means that different backups should have different mod times for `StreamingFile`s, …
> feat(snapshots): Allow uploader to find cached `StreamingFile`s

- cli/command_repository_upgrade.go
- cli/command_repository_upgrade_test.go
This PR removes the advance-notice setting from the upgrade CLI that was introduced in PR #1818 . This PR also updates some of the existing Advance Notice tests as "upgrade status while locked" style testing, so instead of removing them we change them slightly here to give us additional coverage under lock.
> fix(cli): drop the ability to set advance-notices on upgrade

- internal/mockfs/mockfs.go
- internal/server/source_manager.go
- snapshot/snapshotfs/upload.go
- snapshot/snapshotfs/upload_progress.go
- snapshot/snapshotfs/upload_test.go
Add a callback that gives implementations of `UploadProgress` insight into the fate of uploaded files. This callback provides a slightly different surface area compared to listening on `FinishedHashingFile` and `Error`. Notably, it combines the completion of a file with whether or not there was an error processing the file. By combining this, listeners do not have to worry about seeing a `FinishedHashingFile` call and then maybe seeing an `Error` call. Instead, they know the outcome right away. This can save listeners from caching all files reported by `FinishedHashingFile` until the end of the upload (at which point `Error` will definitely not be called on them)
> feat(snapshots): Callback for when uploader finishes processing a file

- fs/utc_timestamp.go
- fs/utc_timestamp_test.go
This actually fixes test runs on non-UTC timezone which were broken
by #2343.
> feat(snapshots): always serialize timestamps in UTC timezone

- cli/command_restore.go
- cli/command_restore_test.go
- cli/command_snapshot_list.go
- cli/command_snapshot_list_test.go
- snapshot/snapshotfs/objref.go
- tests/end_to_end_test/restore_test.go
When using a path, it finds the last snapshot that contains that path.
One thing that is somewhat sketchy: the function `findSnapshotsForSource` is being used from another command. But it did not seem like a good idea to duplicate the function.
This also allows to use `\` in windows after a snapshot id.
> feat(cli): Allow restore from snapshoted path

- tests/robustness/snapmeta/kopia_persister_light_test.go
Since the fix https://github.com/minio/minio-go/pull/1682 has merged and `go-minio` dependency was bumped to `v7.0.36` in #2378, this reverts commit 7fbf8636079dfe4b51edcadaaff596aa6f1dcea8 from #2246. Resolves #2247.
> fix(general): resume TestS3Connect() after fixing regression

- tools/tools.mk
https://github.com/kopia/kopia/runs/8243012442?check_suite_focus=true
This is caused by weird permissions set on files by `go install` which makes it hard to remove the entire directory using `rm -rf`.
The solution is to clean (local) module cache after `go install` which makes subsequent `rm -rf` work without a problem.
> fix(ci): fixed git working directory cleanup issue

- cli/command_snapshot_fix.go
- internal/testutil/testutil.go
- repo/content/content_manager_iterate.go
- repo/content/index/id.go
- repo/content/index/id_test.go
- repo/object/objectid.go
- repo/object/objectid_test.go
- snapshot/snapshotfs/dir_rewriter.go
- snapshot/snapshotfs/snapshot_storage_stats.go
- snapshot/snapshotfs/snapshot_tree_walker.go
- snapshot/snapshotfs/snapshot_tree_walker_test.go
- snapshot/snapshotfs/snapshot_verifier.go
- snapshot/snapshotgc/gc.go
This is achieved by using bigmap.Map and bigmap.Set which are disk-based data structures instead of holding large maps in memory.
> feat(general): reduce memory usage in GC, verification and snapshot fix

- snapshot/snapshotfs/upload.go
- snapshot/snapshotfs/upload_test.go
Previously the value of --parallel flag was (unintentionally) capped at max number of CPUs. This PR fixes the logic.
> fix(snapshots): fixed --parallel flag when snapshotting

- internal/tempfile/tempfile_linux.go
In response to https://github.com/kopia/kopia/pull/2402#pullrequestreview-1107221866
> feat(general): always try O_TMPFILE on Linux when creating temporary files

- tests/robustness/robustness_test/main_test.go
- tests/robustness/robustness_test/robustness_test.go
- tests/robustness/snapmeta/kopia_snapshotter.go
Use `repository upgrade` command in the robustness tests.
> test(general): Use new kopia upgrade cli in robustness upgrade tests

- cli/command_snapshot_create.go
In the function that parses the tags passed to the create snapshot command, if the tag had an incorrect format, an error message would be returned which did not show the tag itself, making debugging such error difficult. This commit includes the tag in the error message to make debugging easier.
> chore(cli): log bad snapshot tag when parsing fails

- site/content/docs/Features/_index.md
'Server mode' link leads to a 404 error at https://kopia.io/docs/docs/faqs/#what-is-a-kopia-repository-server 
Removed extra /docs/ in the URL.
> docs(site): Fix 'server mode' link

- snapshot/policy/retention_policy.go
The effective number of latest snapshots to keep is not persisted anywhere, making it hard for code using kopia as a library to determine how many snapshots will be kept. Export the function determining this value so that callers have more confidence they have configured the retention policy properly.
> feat(snapshots): Export EffectiveKeepLatest function

- snapshot/policy/scheduling_policy.go
- snapshot/policy/scheduling_policy_test.go
The server was ignoring when "Manual Snapshots Only" was set to true in policy. This fixes that.
> fix(server): Respect manual scheduling policy

- repo/open.go
- tests/compat_test/compat_test.go
This is a regression in 0.12.0 and was reported on Slack by Amir Zarrinkafsh.
Repository connections made using old version of Kopia did not properly save format blob cache duration so it was defaulting to 0s instead of 15 minutes causing endless format refreshes, slowing things down and causing unnecessary read traffic to blob storage.
> fix(repository): fixed frequent repository refreshes for older repositories

- tools/docker/docker-compose.yml
Nginx reverse proxy
```
location / {
grpc_pass grpcs://container_ip:51515;
}
```
Fusermount
A volume should be mounted with property :shared to the /tmp folder of the kopia container.
```
-v /mnt/kopia:/tmp:shared
```
So KopiaUI mounts would be browsable at /mnt/kopia/
Above is required to add some readme to docker-compose.yml works.
> feat(general): Added example docker-compose.yml

- repo/manifest/manifest_manager.go
- repo/manifest/manifest_manager_test.go
Allow matching on labels with empty values. Previously, the "empty value" for `map[string]string` ("") would match the empty value of the label key, causing the system to return all manifests. This separates key existence from value equality to handle labels with empty values.
> fix(repository): Manifest label comparison when value is empty

- internal/metrics/metrics_registry.go
- repo/api_server_repository.go
- repo/content/committed_read_manager.go
- repo/content/content_formatter_test.go
- repo/content/content_index_recovery_test.go
- repo/content/content_manager.go
- repo/content/content_manager_metrics.go
- repo/content/content_manager_test.go
- repo/grpc_repository_client.go
- repo/manifest/manifest_manager_test.go
- repo/open.go
- repo/refcount_closer.go
- repo/repository.go
- tests/stress_test/stress_test.go
This ensures metric registry is always closed on last Close().
> refactor(repository): refactored Repository close logic

- internal/acl/access_level_test.go
- internal/cache/storage_protection_test.go
- internal/repotesting/repotesting_test.go
- internal/server/api_cli_test.go
- internal/server/api_paths_test.go
- internal/server/api_policies_test.go
- internal/server/api_restore_test.go
- internal/server/api_snapshots_test.go
- internal/server/api_sources_test.go
- internal/server/api_ui_pref_test.go
- internal/server/server_test.go
- internal/servertesting/servertesting.go
- internal/sparsefile/sparsefile_test.go
- internal/stat/stat_test.go
- repo/blob/filesystem/filesystem_storage_test.go
- repo/blob/sftp/sftp_storage_test.go
- repo/content/sessions_test.go
- repo/maintenance/blob_gc_test.go
- repo/object/object_manager_test.go
- snapshot/snapshot_test.go
- snapshot/snapshotmaintenance/snapshotmaintenance_test.go
- tests/end_to_end_test/api_server_repository_test.go
- tests/end_to_end_test/restore_test.go
- tests/end_to_end_test/snapshot_actions_test.go
- removed repo.OpenAPIServer() which was only needed for testability
- introduced servertesting package to replace it
> test(repository): server testability refactoring

- internal/metricid/id_mapping.go
- internal/metricid/id_mapping_test.go
- internal/metricid/metricid.go
- internal/metricid/metricid_test.go
- repo/repository_test.go
This manages mapping of metric names to IDs which allows efficient JSON representation of counter values for each set of metrics where only values are in the index order.
This will be used in the telemetry protocol and for storing counters in the repository.
Added test that ensures all metrics registered in a repository have the corresponding mapping.
> feat(repository): added internal/metricid package

- cli/command_repository_set_parameters.go
- cli/command_repository_set_parameters_test.go
Fixes https://github.com/kopia/kopia/issues/2513
Do not allow downgrade of an index by using the `set-parameter` command on Kopia.
> fix(cli): do not allow index downgrade by using `set-parameter`

- repo/blob/filesystem/filesystem_storage.go
- repo/blob/filesystem/filesystem_storage_unix_test.go
- repo/blob/filesystem/osinterface.go
- repo/blob/filesystem/osinterface_mock_other_test.go
- repo/blob/filesystem/osinterface_mock_test.go
- repo/blob/filesystem/osinterface_mock_unix_test.go
- repo/blob/filesystem/osinterface_realos_other.go
- repo/blob/filesystem/osinterface_realos_unix.go
Running Kopia over certain (like NFS) backends can lead to ESTALE errors when working with a stale mount or file-descriptors. Currently an ESTALE from FS calls like o.Stat() end up getting retried unnecessarily. This patch introduces a fix to prevent retries on UNIX platforms.
> fix(general): prevent storage retries on ESTALE errors

- snapshot/snapshotfs/upload.go
- snapshot/snapshotfs/upload_test.go
When checking if an entry is cached and using StreamingFile, source the file size from the cached entry. StreamingFiles don't know their size until they are read so this fixes the issue where files would have 0 size but still have their full content. Also fixes stats reporting for StreamingFiles
> fix(snapshots): cached stream file size

- cli/command_snapshot_create.go
- fs/entry.go
- fs/virtualfs/virtualfs.go
- fs/virtualfs/virtualfs_test.go
- snapshot/snapshotfs/upload.go
- snapshot/snapshotfs/upload_test.go
- tests/tools/kopiaclient/kopiaclient.go
Allow better resource cleanup by returning ReadClosers from StreamingFiles and having the uploader close it when it's done
This breaks the previous interface for external users for virtualfs.streamingFile as it changes one of the parameters for the initializer
> feat(snapshots): Return ReadCloser from StreamingFiles

- repo/grpc_repository_client.go
[Issue 2660](https://github.com/kopia/kopia/issues/2660)
Kopia remote client needs GRPC message size > 2GB, due to nig repo with 160k+ of snapshots. Suggest to double the max. GRPC message size to 4GB for the time being. It would probablöy be best, to make this a tuneable via the config file.
> feat(repository): increase GRPC maximum message size to 36 MiB

- .github/workflows/race-detector.yml
- Makefile
- cli/command_repository_upgrade_test.go
- cli/command_server_start.go
- internal/logfile/logfile_test.go
- repo/grpc_repository_client.go
- tests/end_to_end_test/api_server_repository_test.go
- tests/htmlui_e2e_test/htmlui_e2e_test.go
- tests/testenv/cli_test_env.go
Added `--shutdown-grace-period` flag to `kopia server start` command which can be used to specify how long the server will wait for active connections to finish before forcibly shutting down.
This allowed removal of final out-of-process execution of during integration tests and the need for `integration-tests` target which was running the same tests as `tests` but in out-of-process mode.
We thus now have all the test coverage in-process without having to build and launch `kopia` binary.
> feat(server): improved server shutdown and integration tests

- tests/tools/kopiarunner/kopia_snapshotter.go
Parse `stdout` instead of `stderr` in `KopiaSnapshotter.CreateSnapshot`.
This is contained to the Robustness Framework.
> test(general): parse stdout instead of stderr in robustness framework helper

- site/content/docs/FAQs/_index.md
Currently not found - should probably link to https://kopia.io/docs/repositories/
> docs(site): fix link to repositories docs

- internal/user/user_manager.go
- repo/api_server_repository.go
- repo/grpc_repository_client.go
- repo/maintenance/maintenance_params.go
- repo/repository.go
- snapshot/policy/policy_manager.go
This simplifies use cases where we intend to replace a manifest uniquely identified by a set of labels with another one as is the case for policies.
This helped fix annoying test flake on Windows where the clock is not guaranteed to move forward when read in quick succession.
This is now passing on Windows:
```
$ go test -timeout 1000s ./internal/server -run TestSourceRefreshesAfterPolicy -count=1000
```
> feat(repository): added RepositoryWriter.ReplaceManifests

- app/entitlements.mac.plist
This fixes crash on startup after recent upgrade of Electron dependency.
> fix(kopiaui): added missing entitlement for M1 build

- .gitignore
- site/content/docs/Getting started/_index.md
- site/content/docs/Installation/_index.md
- Rephrased the installation guide 
- Added a docker-compose example in the "docker images" section
- Restructured the outline of the guide to match the actual content
- Fixed a typo in the "Getting started" section
> docs(site): rephrased and restructured the installation guide - added an example docker-compose

- app/public/server.js
The fix is to use `127.0.0.1` instead of `localhost` when starting the server and polling for the server status.
This resolves an issue where KopiaUI can't connect to the server which only listens on IPv4 localhost (127.0.0.1) but the Javascript client prefers IPv6 (::1) and fails to connect.
> fix(kopiaui): fixed '<starting up>' in the tray menu.

- site/content/docs/Advanced/Actions/_index.md
- site/content/docs/Advanced/Caching/_index.md
- site/content/docs/Advanced/Compatibility/_index.md
- site/content/docs/Advanced/Kopiaignore/_index.md
- site/content/docs/Advanced/Logging/_index.md
- site/content/docs/Advanced/Sharding/_index.md
- site/content/docs/Advanced/Synchronization/_index.md
- site/content/docs/Advanced/_index.md
- site/content/docs/Installation/_index.md
Hi, 
this PR comes with the following changes:
- Added a new under "Advanced Topics" to document kopiaignore files and patterns
- Added an example for kopiaignore for better understanding
I have tested the patterns with kopia 0.12.1 and they should work as described. However, I think there is still a strange behavior when using "/" together with "*" in a pattern. 
This PR closes #1945 and #2847
Open for feedback.
> docs(site): added a documentation on kopiaignore

- cli/command_repository_set_parameters_test.go
- cli/command_repository_upgrade.go
- cli/command_repository_upgrade_test.go
- repo/format/upgrade_lock.go
- repo/format/upgrade_lock_test.go
This commit changes the behavior of the command
`kopia repo upgrade begin...` to not fail (exit code 1) when the repository is already using the latest format version. Instead, a helpful message is output and the program exits with zero code. In effect the command becomes idempotent-successive upgrades would return the same exit code. Such an idempotent api is desirable, especially in cases where we build automation around format upgrades.
Before this change, an error code `1` is returned when upgrading a repository that is already up to date:
```console
$ kopia repo status | grep "Format Version"
Format version:      3
$ kopia repo upgrade begin --upgrade-owner-id admin
[1] ERROR error setting the upgrade lock intent: repository is using version 3, and version 3 is the maximum
```
and …
> feat(cli): Make format upgrade command idempotent

- internal/epoch/epoch_manager_test.go
- repo/blob/s3/s3_versioned_test.go
- repo/content/content_manager_test.go
- repo/content/indexblob/index_blob_manager_v0_test.go
- repo/object/object_manager_test.go
- tests/repository_stress_test/repository_stress_test.go
Lint fixes in preparation for moving to Go 1.20
Split into self-contained commits to simplify reviewing
> fix(general): remove uses of deprecated rand.Read

- site/config.toml
- site/content/docs/Advanced/Kopiaignore/_index.md
- site/content/docs/FAQs/_index.md
- site/content/docs/Features/_index.md
The PR comes with the following changes:
- Added the documentation on kopiaignore to the FAQs
- Added the FAQs to the main menu
- Added a link the kopiaignore documentation in the "features" section
- Added a paragraph on incomplete snapshots in the FAQs. 
This PR closes #2681
Feedback is welcomed. 
Cheers,
> docs(site): improved faq and kopiaignore section 

- internal/ospath/ospath.go
There is a special case when checking if a given path is absolute. 
On Windows paths like "\\hostname\share" are treated as absolute. Therefore, the function "isAbs" has to first check for this before calling "filepath.IsAbs" as this returns true for non-absolute paths (e.g. \\host).  
The test for internal\ospath now return success and was failing before on windows due to the wrong order.  
Cheers,
> fix(general): Fixed ordering in function "isAbs" in ospath

- .github/workflows/code-coverage.yml
- .github/workflows/compat-test.yml
- .github/workflows/endurance-test.yml
- .github/workflows/htmlui-tests.yml
- .github/workflows/license-check.yml
- .github/workflows/make.yml
- .github/workflows/provider-tests.yml
- .github/workflows/race-detector.yml
- .github/workflows/stress-test.yml
- .github/workflows/tests.yml
This way GH caching for Go packages has a chance to work.
See https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
A cursory test shows that restoring the Go mod cache takes about ~20s.
Downloading the dependencies without a cache takes 60+s. With a cache, that step is ~5s.
Overall the gains are between 2x - 3x for this stage.
Now, when the go mod cache is modified (e.g., during a dependency upgrade) there is an additional 60s cost at the end of the job to update the cache. Once the cache is updated, other jobs get the benefit. Notice that the cache is only updated when the job is successful. When the job fails, the cache artifact is not uploaded.
> build(infra): checkout repo before setting up Go

- app/public/server.js
- cli/command_cache_info.go
- cli/command_index_list.go
- cli/command_maintenance_run.go
- cli/command_manifest_ls.go
- cli/command_repository_set_parameters_test.go
- cli/command_repository_upgrade.go
- cli/command_repository_upgrade_test.go
- cli/command_server_start.go
- cli/command_snapshot_create.go
- tests/compat_test/compat_test.go
- tests/robustness/snapmeta/kopia_snapshotter.go
| Command        | Previous default subcommand |
| ---------------| --------------------------- |
| `cache`        | `info`   |
| `index`        | `list`   |
| `manifest`     | `list`   |
| `maintenance`  | `run`    |
| `repo upgrade` | `begin`  |
| `snapshot`     | `create` |
Ref #2823
> breaking(cli): remove default behavior for CLI command

- tools/tools.mk
MinIO's MC installation broke in minio/mc#4531
This is a temporary fix until upstream is fixed.
> build(infra): fix minio's mc installation

- .github/workflows/stale.yml
That requires repo content write access.
> chore(infra): do not remove branches on stale workflow

- internal/cache/persistent_lru_cache.go
- internal/metrics/metrics_distribution.go
- internal/metrics/prom_cache.go
- repo/blob/s3/s3_versioned_test.go
- repo/content/committed_content_index.go
- repo/content/content_manager_test.go
- repo/format/upgrade_lock.go
- tests/testenv/cli_test_env.go
We can't enable checklocks on CI yet until https://github.com/google/gvisor/pull/8807 is merged upstream.
This was tested with private build of checklocks with this patch applied and the results were clean.
> chore(general): fixed remaining checklocks violations

- Makefile
this is a dummy change to trigger CI/CD pipeline. This should produce updated DEB binaries in `unstable` to address #2949 #2947 #2946.
Once it's confirmed the key has been fixed, we'll re-sign stable and testing.
> chore(ci): trigger CI rebuild after signing key update

- site/content/docs/Installation/_index.md
The current installation instructions mention `/usr/share/keyrings` as the location to copy the apt key files to, but according to the sources.list and apt-key manpages, the correct location for manually installed keys would be `/etc/apt/keyrings`.
This PR changes the instructions to point to that location instead.
From the sources.list manpage:
> The recommended locations for keyrings are /usr/share/keyrings for keyrings managed by packages, and /etc/apt/keyrings for keyrings managed by the system operator.
From the apt-key manpage:
> FILES
>    /etc/apt/trusted.gpg
>            Keyring of local trusted keys, new keys will be added here. Configuration Item: Dir::Etc::Trusted.
> 
>    /etc/apt/trusted.gpg.d/
>            File fragments for the trusted keys, additional keyrings can be …
> docs(site): update installation instructions for apt key location

- repo/manifest/committed_manifest_manager.go
- repo/manifest/serialized.go
- repo/manifest/serialized_test.go
- repo/manifest/testdata/manifests.go
Golang's stdlib JSON decoder allocates lots of memory when decoding large objects/arrays because it needs to have the entire object/array in-memory (see a [medium post](https://medium.com/safetycultureengineering/analyzing-and-improving-memory-usage-in-go-46be8c3be0a8) by another person for some debugging of this phenomenon in an unrelated project). This can cause OOMs or increased costs when accessing manifests in a kopia repo that has lots of snapshots in it
This PR adds some manual parsing to the decoding of manifests in kopia. It manually parses the `manifest` struct and pulls off the `[` and `]` denoting the array of manifest entries. Parsing of individual entries in the array is deferred to the stdlib decoder as it behaves reasonably well for those
This does not completely solve the …
> feat(repository): Reduce memory usage when parsing manifests

- app/Makefile
- app/package-lock.json
- app/package.json
- site/Makefile
Fixed semi-manually:
```
npm remove electron-first-run
npm install electron@25.0.0
npm install semver@7.5.3
```
Turns out we don't need `electron-first-run` at all.
Replaces #3100
> chore(ci): fix `npm audit` failure by removing `electron-first-run` and upgrading `electron` and `semver`

- .github/auto-merge.yml
- .github/config.yml
- .github/dependabot.yml
- .github/workflows/auto-merge.yml
- .github/workflows/check-pr-title.yml
This reverts commit f9de453efc198b6e993af8922f953a7e5322dc5f.
Turns out Snyk has many more quirks than Dependabot and our dependencies have not been regularly updated.
> chore(ci): restore dependabot removed in PR3017

- .github/dependabot.yml
This generates larger PRs for multiple dependencies at a time, such as https://github.com/jkowalski/kopia/pull/476
It uses relatively new feature of Dependabot described here: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
> chore(ci): group dependabot updates and make them weekly

- .github/workflows/stale.yml
- add message to provide additional information when issues or PRs are closed.
- exclude PRs and issues with the 'keep-open' label
- run twice a week
> chore(infra): update stale workflow settings

- repo/blob/filesystem/filesystem_storage.go
- repo/blob/filesystem/osinterface.go
- repo/blob/filesystem/osinterface_realos_other.go
- repo/blob/filesystem/osinterface_realos_unix.go
Renames `IsESTALE(error)` to `IsStale(error)` to make it consistent with the conventions in the Go ecosystem.
Uses `errors.Is()` instead of `==` comparison. It is more robust.
> chore(general): cleanup "stale" error naming

- internal/logfile/logfile_test.go
Hi, 
there were a couple failed runs for logfile_test. In edge cases both sizes were the same and therefore the test failed. 
An analysis of the test output revealed that the test itself works as intented. 
Further analysis will be carried out to find the root cause. 
For now it should fix #3128 
Feedback is welcomed.
Cheers,
> fix(ci): Potential fix for TestLogFileMaxTotalSize

- cli/command_snapshot_create.go
- explicitly pass username and hostname instead of repo writer
- nit: name return values
Follow up to #3041
> style(general): minor followups form #3041

- go.mod
- go.sum
- repo/blob/s3/s3_storage_test.go
Refactor S3 test to use minio SDK credentials package in STS test
- return `credentials.Value` in `createMinioSessionToken` helper
- `go mod tidy -compat=1.20` => Removes dependency on AWS SDK v1 packages
- cleanup: remove alias for minio credentials package
Test output:
```
go test -timeout 10m -tags testing -run ^TestS3StorageMinioSTS$ github.com/kopia/kopia/repo/blob/s3 -v -count=1
=== RUN   TestS3StorageMinioSTS
=== PAUSE TestS3StorageMinioSTS
=== CONT  TestS3StorageMinioSTS
/Users/j/devel/kopia/repo/blob/s3/s3_storage_test.go:473: running docker [run --rm -p 0:9000 -e MINIO_ROOT_USER=fake-key -e MINIO_ROOT_PASSWORD=fake-secret -e MINIO_REGION_NAME=fake-region-1 -v /var/folders/h3/gdwzylnj4gd681l9fv25r6b40000gq/T/kopia-test1319019249:/root/.minio -d minio/minio server /data] …
```
> refactor(providers): use minio SDK credentials package in S3 STS test

- BUILD.md
Using `server` only, the following error message was shown:
```
kopia: error: unknown long flag '--insecure', try --help
```
The fix is to start the Kopia server by `server start`.
> docs(infra): update instructions to start server in BUILD.md

- .golangci.yml
Reverts to default behavior from golangci_lint
> chore(infra): run golangci_lint in Go version from go.mod

- .github/workflows/providers-core.yml
- .github/workflows/providers-extra.yml
Split into _core_ and _extra_ providers.
Core providers tests run after merging into the main branch and daily on schedule.
Extra providers tests run twice a week (T, Th).
Both workflows can be triggered on demand as well.
Executions of these workflows:
- [Core](https://github.com/kopia/kopia/actions/runs/5593459887)
- [Extras](https://github.com/kopia/kopia/actions/runs/5593459886/jobs/10227123698?pr=3158)
> test(providers): split providers test workflow

- cli/command_policy_set_scheduling.go
- cli/command_policy_set_test.go
- cli/command_policy_show.go
- go.mod
- go.sum
- internal/server/api_policies.go
- internal/server/api_policies_test.go
- internal/serverapi/serverapi.go
- snapshot/policy/scheduling_policy.go
- snapshot/policy/scheduling_policy_test.go
We use `github.com/hashicorp/cronexpr` to parse and evaluate expressions, as documented in https://github.com/hashicorp/cronexpr#implementation
https://github.com/kopia/htmlui/assets/249880/cde6b575-d077-4a0d-8f43-ff5cd2babde9
Fixes #671
Related #1723
> feat(snapshots): added ability to use cron expressions to schedule snapshots

- cli/command_snapshot_create.go
- tests/end_to_end_test/restore_fail_test.go
- tests/end_to_end_test/snapshot_fail_test.go
Changes kopia's behavior to match the exit code that would have been returned when the `--json` flag was not specified.
`kopia snapshot create my/path --json` terminates with a 0 status code in cases where
`kopia snapshot create my/path` terminates with a non-zero exit code. One such case is when there are permissions errors reading files or directories to snapshot.
> fix(cli): preserve error exit code when '--json' output is specified

- internal/blobtesting/object_locking_map.go
- repo/blob/storage_extend_test.go
- repo/maintenance/blob_retain_test.go
Two minor cleanups for tests around retention:
* define an error and use `assert.ErrorIs` rather than comparing error messages when a blobtesting backend is used
* switch to `require.NoError` instead of an `if err != nil`/`t.Fatal` block
> refactor(general): Cleaner error checking in retention tests

- tests/htmlui_e2e_test/htmlui_e2e_test.go
Dear all, 
this PR contains:
- Added test for changing themes
- Encapsulated the creation of a test repository in a function
- Added test for changing the byte representation
- Added test for changing the pagination
The PR is currently a draft. While the test for selecting different themes works, the tests for testing pagination and byte representation still needs to be finished. I was not able to extract the text within the cell, where the size of the snapshot is located. 
The idea was to get the size in both byte representations and compare them. 
Feedback is welcomed. 
Cheers,
> fix(ci): add test for theme selection

- app/Makefile
This happens on PR from branches in the kopia repo.
> fix(ci): avoid hung CI jobs while notarizing the kopia app on MacOS 

- internal/fshasher/fshasher.go
- internal/providervalidation/providervalidation.go
- internal/providervalidation/providervalidation_test.go
- tests/end_to_end_test/restore_test.go
- fixed directory iteration order
- reduced providervalidation memory usage
- disabled one test case of TestSnapshotSparseRestore (filed https://github.com/kopia/kopia/issues/3178 to fix)
> chore(ci): fixes for ARM64 runner on AWS

- cli/command_repository_connect_from_config.go
- cli/command_repository_create.go
- cli/command_repository_create_test.go
- cli/storage_providers.go
- repo/token.go
When creating a repo we are currently required to supply storage config secrets as CLI arguments. CLI commands often get logged which can accidentally expose these creds. This PR extends the `from-config` storage flags to be supplied at the time of creation with a dedicated `--token-file` option or `--token-stdin` option that reads from stdin.
```
echo "${kopia_string}" | kopia repository create from-config --token-stdin
```
```
kopia repository create from-config --token-file /path/to/token-file
```
> feat(cli): new storage config input from file when creating a repo

- snapshot/snapshotfs/upload_progress.go
Hi, 
currently, the task summary shows the total number of ignored errors. Since the user is interested in non ignored errors, the summary should show fatal errors (see https://kopia.discourse.group/t/kopiaui-bug-on-log/2171/2)
Fatal errors are already shown when browsing the snapshot (indicated by a warning sign). However, the task summary showed ignored errors causing inconsistencies between both views. 
This PR contains the following fix:
- Store and send the total number of fatal errors
It would also be possible to extend the task summary to show ignored and fatal errors separately.
Feedback is welcomed. 
Cheers,
> fix(ui): Task summary should show fatal errors

- internal/cache/persistent_lru_cache.go
Followups to #3085
Change cache full logging frequency to once every 10 minutes. Addresses concerns about too many messages in the logs in #3085 
Avoid logging cache key. Instead log the cache description, which provides information about the types of contents being cached.
> fix(general): change cache full logging frequency & message

- cli/observability_flags.go
Motivation: reduce the function complexity for the linter, so additional functionality can be added to `startMetrics()`
No functional changes.
Breaks down `observability.startMetrics()` into:
- `maybeStartListener`
- `maybeStartMetricsPusher`
- `maybeStartTraceExporter`
> refactor(cli): break down observability.startMetrics()

- .github/workflows/make.yml
Currently, on MacOS, this step hangs when attempting to notarize the newly built binary. The job eventually times out after 360 min.
This is a temporary workaround that will terminate the job sooner to avoid wasting runner cycles. The chose timeout value is ~2x the maximum typical elapsed time for this specific step.
In all platforms this step finishes in less than 20 minutes.
The actual cause of the notarization timeout needs to be investigated.
Ref: #488 #3168 #3175
> fix(infra): add timeout for make.yml build.Build step

- cli/observability_flags.go
- cli/observability_flags_test.go
Objective: to facilitate capturing metrics for relatively short-lived kopia executions.
Motivation: Currently, kopia allows a. exposing metrics via a Prometheus exporter; and b. pushing metrics to a Prometheus gateway. In certain scenarios, such as short lived executions, it is not possible to reliably scrape the metrics from the exporter endpoint. And, while the pusher approach would work, it requires starting a separate push gateway.
This change allows saving the metrics to a local file before kopia exists by specifying the metrics output directory. For example,
```
kopia --metrics-directory /tmp/kopia-metrics/ snapshot create ....
```
In this case, after kopia exists, the `/tmp/kopia-metrics/` directory will contain a file with a named of the form …
> feat(cli): save observability metric before exiting the process

- repo/format/format_manager_test.go
It avoids a package name shadowing and linting errors in an upcoming PR.
> refactor(general): rename cache variable in test

- repo/format/format_manager_test.go
- repo/format/format_set_parameters.go
Fix minor issue with caching the storage blob config blob settings in-memory which could cause other blob PUTs after a reconfiguration to have incorrect settings
Most of PR is tests similar to the retention extension tests to ensure changing repo settings works as expected
> fix(repository): Storage config blob caching

- internal/blobtesting/object_locking_map.go
- internal/blobtesting/storage.go
- repo/blob/storage_extend_test.go
- repo/format/format_manager_test.go
- repo/maintenance/blob_retain_test.go
Store and return information about retention in the blobtesting storage used for retention tests. This allows more precise checks on when a blob expires and the retention mode applied to the blob
closes #3218
> test(repository): More precise check for retention in tests

- internal/gather/gather_write_buffer.go
- internal/gather/gather_write_buffer_test.go
- repo/blob/sftp/sftp_storage.go
This improves the performance of gather writes (p and q blobs) in particular on high-latency links by reducing round-trips.
Tested by uploading Kopia working directory
(3 GB, files:32157 dirs:6051) to SFTP server on LAN (TrueNAS) over WiFi:
Before: 2m4s (~24 MB/s)
After: 1m13s (~41 MB/s)
> feat(providers): improve performance of SFTP uploads

- cli/command_server_control_test.go
- cli/command_server_tls.go
- internal/apiclient/apiclient.go
- internal/testutil/tmpdir.go
- repo/grpc_repository_client.go
- site/content/docs/Repository Server/_index.md
Enable using unix domain sockets with kopia server.
unix sockets can be useful to allow connecting services without going throgh the network interface.  They tend to be faster than using tcp sockets, and can be restricted via file-access permissions.
I'm using unix sockets in a container solution using rootless containers with networking disabled via podman + systemd socket-activated-sockets.  This means that the reverse-proxy (nginx) doesn't need any network interface, as it speaks to the outside world through a socket-activated-socket, and speaks to other services via unix sockets.
The patch also implements the ability to use unixsockets for client connections, but  I'm not sure what the use of that is other than enabling testing
> feat(server): add server support for unix domain sockets

- internal/blobtesting/map.go
- internal/blobtesting/object_locking_map.go
- repo/blob/azure/azure_storage.go
- repo/blob/b2/b2_storage.go
- repo/blob/filesystem/filesystem_storage.go
- repo/blob/gcs/gcs_storage.go
- repo/blob/gdrive/gdrive_storage.go
- repo/blob/readonly/readonly_storage.go
- repo/blob/s3/s3_storage.go
- repo/blob/sftp/sftp_storage.go
- repo/blob/sharded/sharded.go
- repo/blob/storage.go
- repo/blob/webdav/webdav_storage.go
Create a stub struct that has default implementations of trivial functions that providers are expected to implement. This allows for easier additions in the future as the new struct can be modified instead of all provider implementations. Providers that desire different functionality can just override specific functions
Reviewing by commit should help isolate individual sets of changes
> refactor(providers): Create default provider that has common functions

- repo/content/committed_read_manager.go
- repo/manifest/committed_manifest_manager.go
- repo/manifest/manifest_manager.go
- repo/manifest/manifest_manager_test.go
- repo/open.go
Add a new field to the manifest manager that denotes whether it should act in read-only mode or not. The main difference between read-only and normal modes for the manager is that manifest compaction is disabled in read-only mode
This allows kopia to successfully read manifest information in the repo when either the repo was opened in read-only mode or the repo uses a versioned S3 bucket and was opened at a specific point in time with the `--point-in-time` flag
The value of this new field is taken from the local client options `ReadOnly` parameter. Client options can be provided during `repository.Open` calls to kopia giving the user control over this if needed
closes #3219
> fix(repository): Disable manifest manager compaction when in read-only mode

- .github/workflows/lint.yml
Sample output:
```
Run govulncheck -C . ./...
govulncheck -C . ./...
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
UNIX_SHELL_ON_WINDOWS: true
ENABLE_UNICODE_FILENAMES: 
ENABLE_LONG_FILENAMES: 
Scanning your code and 636 packages across 105 dependent modules for known vulnerabilities...
No vulnerabilities found.
```
> chore(ci): add govulncheck step to lint workflow

- cli/command_server_start.go
- internal/server/server.go
- internal/uitask/uitask_manager.go
- internal/uitask/uitask_test.go
- repo/content/committed_read_manager.go
- repo/logging/broadcast.go
- repo/logging/ctx.go
- repo/logging/logging_test.go
Previously some logs from a running server were only kept in memory (including storage activity logs) which was confusing to many folks.
This changes the behavior so that logs are sent to their regular (console/file) file locations in addition to the UI tasks.
Old behavior can be restored by adding `--no-persistent-logs` to server.
> feat(server): fixed server logging to file & console

- cli/command_snapshot_verify.go
- snapshot/snapshotfs/snapshot_verifier.go
This should address user confusion for very small repositories that are very quickly verified printing only `Processed 0 objects.`
> fix(cli): added output to indicate completion of snapshot verification

- .github/workflows/code-coverage.yml
- .github/workflows/compat-test.yml
- .github/workflows/endurance-test.yml
- .github/workflows/htmlui-tests.yml
- .github/workflows/license-check.yml
- .github/workflows/lint.yml
- .github/workflows/make.yml
- .github/workflows/providers-core.yml
- .github/workflows/providers-extra.yml
- .github/workflows/race-detector.yml
- .github/workflows/stress-test.yml
- .github/workflows/tests.yml
This simplifies managing the Go version used in CI, as it will only require updating the `go.mod` file when upgrading the Go toolchain.
> chore(ci): use 'with.go-version-file' in actions/setup-go

- cli/command_repository_validate_provider.go
- internal/blobtesting/verify.go
- internal/providervalidation/providervalidation.go
- internal/providervalidation/providervalidation_test.go
- repo/blob/logging/logging_storage_test.go
- repo/blob/rclone/rclone_storage.go
- repo/blob/rclone/rclone_storage_test.go
Added improved providervalidation logic which tests for read-after-write property between connections. The new test was failing before the change and is now passing for Google Drive, OneDrive and DropBox.
This has been verified by pushing to `test/providers` branch - https://github.com/kopia/kopia/actions/runs/6132645691/job/16643740278
> fix(providers): fixed list/get caching with rclone providers

- site/content/docs/Advanced/Actions/_index.md
This PR adds an example of using LVM (Logical Volume Manager) snapshots to create consistent filesystem backups.
> docs(site): Add LVM example for actions

- cli/command_server_control_linux_test.go
- cli/command_server_tls.go
- go.mod
- go.sum
- site/content/docs/Repository Server/_index.md
I'm not sure how much interest there is in this, but the attached patch adds systemd socket-activation support for Kopia.  Normally socket-activation is used for on-demand application startup, but that probably isn't an ideal setup for Kopia as it could prevent the running of maintenance tasks.  However socket activation has a few other uses:
* Allows configuring permissions of a unix-domain-socket
* Allows exposing ports when running in a rootless podman container without the need for slirp4netns (socket-activation does not work with Docker as far as I know)
* Can be used to allow running of privileged ports as non-root user (additional setup required)
My personal use is the 1st one, as it provides a race-free way to ensure my reverse-proxy can access the unix-domain-socket I use for …
> feat(server): Add socket-activation support

- internal/serverapi/serverapi.go
When I connect to the server http page, I prefer to see all snapshots shown by default.  every time I switch away and come back I need to reselect 'All' instead of 'Local'.  This just makes the default a preference option.
Requires https://github.com/kopia/htmlui/pull/186
> feat(ui): Allow specifying whether local or all snapshots are shown by default

- internal/scheduler/scheduler.go
- internal/scheduler/scheduler_test.go
This is a generic scheduler that executes a loop consisting of:
- determining upcoming set of events
- waiting until the appropriate time
- triggering the events
(Note this is part of #3265 after addressing comments made on that review, only limited to scheduler)
> feat(server): introduced generic scheduler

- .github/workflows/code-coverage.yml
- .github/workflows/compat-test.yml
- .github/workflows/endurance-test.yml
- .github/workflows/htmlui-tests.yml
- .github/workflows/license-check.yml
- .github/workflows/lint.yml
- .github/workflows/make.yml
- .github/workflows/ossf-scorecard.yml
- .github/workflows/providers-core.yml
- .github/workflows/providers-extra.yml
- .github/workflows/race-detector.yml
- .github/workflows/stress-test.yml
- .github/workflows/tests.yml
Upgrade actions/upload-artifact to v3.1.3
Release notes: https://github.com/actions/upload-artifact/releases
Upgrade codecov-action to 3.1.4
Release notes: https://github.com/codecov/codecov-action/releases/tag/v3.1.4
> chore(deps): use commit id for GH action versions

- tools/apt-publish.sh
- tools/rpm-publish.sh
This was previously done in `unstable` track, now doing it everywhere. At the same time bumped the count 2=>3.
> chore(ci): auto-delete old RPM and DEB packages

- cli/command_policy_set_scheduling.go
- cli/command_policy_set_test.go
- cli/command_policy_show.go
- go.mod
- go.sum
- snapshot/policy/scheduling_policy.go
- snapshot/policy/scheduling_policy_test.go
This PR adds a configuration option to create an immediate snapshot if a previous time-of-day snapshot was missed.  Today, interval snapshots will automatically be taken immediately if they were missed, but a time-of-day snapshot will not be taken until the next schedule.
made this a configuration item instead of just enabling it because it may be that some users would prefer to miss a snasphot and take the next one off-hours rather than doing it immediately on startup.
This implements https://github.com/kopia/kopia/issues/3197
This is associated wit the htmlui patch: https://github.com/kopia/htmlui/pull/190
> feat(cli): Added option to allow running missed snapshots on Kopia start

- site/content/docs/Contribution guidelines/_index.md
I've run into the title checker on almost every one of my PRs, despite trying to get it right each time.  So I've documented it in the hopes to make it easier to get right in one attempt.
> docs(site): Add description of title-checker when submitting a PR

- snapshot/policy/scheduling_policy_test.go
After debugging several snapshot-policies, I found it would be nicer to have names for each test rather than needing to count them.
> test(snapshots): Name policy tests to make debugging easier

- cli/command_policy_set_scheduling.go
- cli/command_policy_set_test.go
- cli/command_policy_show.go
- internal/server/api_sources_test.go
- snapshot/policy/error_handling_policy_test.go
- snapshot/policy/optional.go
- snapshot/policy/policy_tree.go
- snapshot/policy/scheduling_policy.go
- snapshot/policy/scheduling_policy_test.go
As per discussion on #3330 this converts --run-missed from a bool to a Enum to allow 'inherit' to properly work.  It keeps the the default as 'false', and so will not change the behavior of existing or new repositories.
Changing the default to 'true' can be decided on independently.
> fix(cli): Convert --run-missed from bool to Enum

- snapshot/policy/scheduling_policy.go
I've seen a few comments now indicating that defaulting the RunMissed policy option to 'true' may be a better option.  This PR also converts it into a Tri-State which makes setting/clearing the value more intuitive from the cmdline (in current production, --run-missed must be specified whenever changing the schedule, whereas when using the tristate, it is only modified when the user specifically requests it.
Note that this PR will conflict with #3323, so if both are accepted, one of them will need to be reconciled with the other.
> fix(cli): RunMissed policy now defaults to true

- app/public/electron.js
This PR contains the following fix:
- Fixed missing window in cases where external displays are detached
- Maximize the window now works as expected
This PR is an **emergency fix** for #3315. If an external display is detached after the kopia-ui window has been closed on this display, the ui won't open anymore. 
The logic now checks if the scaling factors of attached displays are the same (covers https://github.com/electron/electron/issues/10862). Additionally it checks, whether the window bounds lie within a display's working area. Both conditions has to be true, so that the stored window bounds are restored. 
If not, the window will default to the center of the primary screen with it's default width and height. 
Please review. 
Cheers,
> fix(kopiaui): Fix missing window when external displays are detached

- cli/command_policy_edit.go
Hi, 
this PR should fix #2670. 
The helptext is formatted with the target provided by the function. 
Cheers,
> fix(cli): Fixing help text when editing policies externally

- snapshot/snapshotfs/upload.go
Reorder streaming file upload defer functions slightly so the reader is closed prior to calling FinishedFile. This allows folks who hook into those callbacks to make stronger assumptions about the ordering/state of things if needed.
> refactor(snapshots): Minor reorder of defer funcs for streaming files

- cli/command_policy_set_scheduling.go
- snapshot/policy/scheduling_policy.go
- snapshot/policy/scheduling_policy_test.go
The current algorithm assumes a singe snapshot per-day.  It doesn't work well with either >1 time-of-day snapshots or with cron snapshots.
This PR calculates the next snapshot time that should have happened based on the previous snapshot.  If that time is before now, then we missed a snapshot and should do a catchup snapshot.
I kept the heuristic of not running a snapshot if the next snapshot would occur within the next 30 minutes.  I'm no longer sure if that is a good policy or not.
Fixes #3319
> feat(server): improve scheduler algorithm to run missed snapshots 

- cli/command_index_inspect.go
- cli/command_repository_upgrade.go
- cli/command_repository_upgrade_test.go
- cli/command_snapshot_fix_test.go
- cli/json_output.go
- internal/indextest/indextest.go
- repo/api_server_repository.go
- repo/content/committed_content_index.go
- repo/content/committed_content_index_cache_test.go
- repo/content/content_index_recovery.go
- repo/content/content_manager.go
- repo/content/content_manager_indexes.go
- repo/content/content_manager_test.go
- repo/content/content_prefetch.go
- repo/content/index/index.go
- repo/content/index/index_builder.go
- repo/content/index/index_v1.go
- repo/content/index/index_v2.go
- repo/content/index/info.go
- repo/content/index/merged.go
- repo/content/index/merged_test.go
- repo/content/index/packindex_test.go
- repo/content/indexblob/index_blob_manager_v0.go
- repo/content/info.go
- repo/grpc_repository_client.go
- repo/object/object_manager_test.go
- tests/end_to_end_test/policy_test.go
- tests/end_to_end_test/snapshot_gc_test.go
Previously `content.Info` was an interface which was implemented by:
* `index.InfoStruct`
* `index.indexEntryInfoV1`
* `index.indexEntryInfoV2`
The last 2 implementations were relying on memory-mapped files which in rare cases could be closed while Kopia was still processing them leading to #2599.
This changes fixes the bug and strictly separates `content.Info` (which is now always a struct) from the other two (which were renamed as `index.InfoReader` and only used inside repo/content/...).
In addition to being safer, this _should_ reduce memory allocations. Perf testing pending...
Quick testing results using https://github.com/kopia/benchmark-scenarios/tree/main/runbench
E2E duration is slightly better, average memory usage is about 5% up, fewer heap objects, more heap bytes, which looks …
> fix(repository): fixed handling of content.Info

- cli/command_repository_set_parameters.go
- cli/command_repository_set_parameters_test.go
Currently there is an [inconsistency](https://github.com/search?q=repo%3Akopia%2Fkopia%20%22no%20change%22&type=code) between what to do when `!anyChanges`...some return an error while others log it and return nil. I'm not sure if in any of the commands it makes sense to return an error in such cases (I would guess always nil) but in the case of SetParameters I think it's not needed. People want a desired state and they have the desired state so all is good; similar to how DeleteBlob returns nil when the blob doesn't exist
At least one path where it is reached is setting `retentionMode` to `none` but retention is already disabled; whereas it's not the case if you set it to `COMPLIANCE` although the value is also not changed. ~~Maybe the logging should also be removed due to this (it only …
> fix(cli): Don't return error when parameters unchanged

- site/content/docs/Advanced/Actions/_index.md
Hello,
Thanks a lot for sharing this super tool (never seen a more efficient backup tool). While setting up VSS following the smart suggestion, I had an issue which I fixed adding a -File to the powershell command...
I hope it is not related to different powershell versions (I’m refering to [V2.0](https://learn.microsoft.com/en-us/previous-versions//dd315276(v=technet.10)?redirectedfrom=MSDN))... If you know more than me about this, please discard this fix.
> docs(cli): add missing -File for powershell vss script policy setup

- site/content/docs/Advanced/Ransomware Protection/_index.md
DeleteObject needs to be allowed. This is needed for kopia to work correctly.
The assumption is that S3 versioning is enabled.
> docs(providers): fix documentation for S3 permissions

- go.mod
- go.sum
FSWalker recently upgraded its protobuf dependency and removes
the need for the deprecated `github.com/golang/protobuf` version.
The dependency on `github.com/golang/protobuf` will be removed in a separate PR.
google/fswalker#39
> chore(deps): upgrade google/fswalker

- internal/epoch/epoch_manager.go
- internal/epoch/epoch_manager_test.go
- repo/content/content_manager.go
Unexport `epoch.Manager.forceAdvanceEpoch`. It is only used in tests.
Remove unused `RetentionMode` and `RetentionPeriod` fields from
`content.ManagerOptions` struct.
> refactor(general): minor cleanups

- internal/epoch/epoch_advance_test.go
- internal/epoch/epoch_manager.go
- internal/epoch/epoch_manager_test.go
- internal/faketime/faketime.go
- internal/faketime/faketime_test.go
- internal/listcache/listcache_test.go
- internal/ownwrites/ownwrites_test.go
- internal/repotesting/repotesting_test.go
- repo/content/committed_read_manager.go
- repo/content/content_manager_test.go
- repo/content/indexblob/index_blob_manager_v0_test.go
- repo/content/indexblob/index_blob_manager_v1.go
- repo/format/format_manager_test.go
- repo/maintenance/maintenance_run.go
- snapshot/snapshotfs/upload_test.go
- snapshot/snapshotmaintenance/snapshotmaintenance_test.go
No externally visible functional changes.
* Rename `faketime.AutoAdvance` parameter to start for clarity
* Clarify `faketime.ClockTimeWithOffset.Advance` documentation
* Refactor: remove 2nd parameter from `faketime.TimeAdvance`, use 0 as default.
* Introduce a `faketime.NewAutoAdvance()` function to create a new `TimeAdvance` with a non-zero auto-advance time. 
* Rename function to `sm.setupCachesAndIndexManagers` for clarity.
* Unexport `indexblob.ManagerV1.epochMgr`. Not used outside the package.
* Rename function for clarity to `advanceEpochMarker`
* Refactor: cleanup logs after cleaning up epoch manager.
* Make 'def' a test-local variable.
* Minor cleanup for epoch test `newTestEnv()`
* Use `log.Debug` for non-formatted output
* Fix log message
* Reword comment and fix typo.
See …
> refactor(general): minor cleanups related to index managers

- cli/cli_progress.go
My backup had a fatal error. The end of the log looked like this:
```
Created snapshot with root k5ab05dd5a8aaf9da8a6a822abd0afabb and ID 04caa6e10f4e2866a74492a4162ea943 in 2m44s
WARN Ignored 943 error(s) while snapshotting root@tower:/.
ERROR Found 1 fatal error(s) while snapshotting root@tower:/.
```
Note that "WARN" is yellow and "ERROR" is red.
Since I got a fatal error, I wanted to check what the fatal error was in the log. Because "ERROR" in the lines above is red, I expected the fatal error in the kopia log to also be red, but it was yellow like the non-fatal errors. This was unexpected to me.
Also note that I have lots of `! Ignored error when processing` in the kopia log because I also backup Docker containers, so right now it is not easy to find the fatal error among the …
> fix(cli): print errors during processing in red

- .github/workflows/code-coverage.yml
- .github/workflows/compat-test.yml
- .github/workflows/endurance-test.yml
- .github/workflows/htmlui-tests.yml
- .github/workflows/make.yml
- .github/workflows/ossf-scorecard.yml
- .github/workflows/stress-test.yml
- .github/workflows/tests.yml
This is causing various workflows to fail. 
There was a breaking change in the action.
https://github.com/actions/toolkit/tree/main/packages/artifact#breaking-changes
Partially reverts commit 276f302d2c5ccb87763d04a0eb2b55f448eedceb.
"build(deps): bump the github-actions group with 3 updates (#3525)"
> build(deps): downgrade GHA actions/upload-artifact

- internal/epoch/epoch_manager_test.go
... instead of `assert.Eventually` with return check
> test(general): use require.Eventually to ensure test stops

- repo/blob/azure/azure_pit.go
- repo/blob/azure/azure_storage.go
- repo/blob/azure/azure_versioned.go
- repo/blob/azure/azure_versioned_test.go
It is unusable if `kopia.respository` is deleted. This changes it to work with deleted or not
> fix(providers): change versioning check for Azure storage

- cli/app.go
- cli/command_mount.go
- cli/command_repository_upgrade.go
- cli/command_server_start.go
- cli/command_snapshot_create.go
- cli/command_snapshot_migrate.go
- cli/config.go
- cli/inproc.go
- cli/terminate_signal_test.go
- tests/testenv/cli_exe_runner.go
- tests/testenv/cli_inproc_runner.go
- tests/testenv/cli_test_env.go
`SIGTERM` is often used as a termination signal for long running processes, in particular in UNIX and containerized environments.
Handling SIGTERM enables graceful shutdown in those environments.
Look at individual commits for easier reviewing.
The one-line functional change is in 058c48072dfe475f4a44475edb44233741b676e2
The rest of the changes are:
- test for SIGTERM
- test refactoring to support sending a signal to the child process
- refactoring / renaming function to better reflect the new functionality
Thanks to @aaron-kasten for pointing this out and suggesting this change.
> feat(cli): handle SIGTERM

- internal/scrubber/scrub_sensitive.go
- internal/scrubber/scrub_sensitive_test.go
Add recursive checks to ensure that sub-structures with sensitive fields also get scrubbed by `ScrubSensitiveData`.
> fix(cli): Ensure scrubber checks all fields recursively for sensitive tags

- site/content/docs/Repositories/_index.md
I believe it is `Rclone` instead of `Rcone` there.
> docs(site): fix typo

- .github/workflows/htmlui-tests.yml
- tests/htmlui_e2e_test/htmlui_e2e_test.go
The exact reason why Linux runner started suddenly failing is unknown, but it's not essential for this test to run on Linux since it's about UI.
> fix(ci): fixed HTMLUI E2E test by switching to macOS runner

- site/content/docs/Repository Server/_index.md
Make the documentation for Repository Server easier to read by isolating v0.8 notes under a separate heading
> docs(site): Group Kopia Repository Server v0.8 usage notes under separate heading

- cli/command_snapshot_migrate.go
- internal/logfile/logfile_test.go
- Simplification in `onTerminate` callback function for snapshot migrate command.
- Quote strings, via `%q`, in assertion failure message for clarity.
Proposed by @aaron-kasten
> refactor(cli): miscellaneous code simplifications

- cli/command_server_start.go
Discard content when server reads `stdin` to avoid allocating a buffer, in the rare case that a large amount of data is streamed to the server's standard input.
nit: use `log.Info` variant for message with no parameters.
> refactor(cli): minor cleanups in server start

- internal/epoch/epoch_manager.go
Refactoring related to #3638 to simplify later PRs as much as possible.
These changes are mostly code movement except for a functional change noted below.
---
Changes
Move index compaction and cleanup out of `refreshAttemptLocked`, and perform it in `refreshLocked` after `refreshAttempLock` succeeds. See inline comments.
Refactor: Introduce an `allowWritesOnLoadHelper` to check whether or not writes can be performed when loading the indexes. Currently this is only a function of whether the storage is in read-only mode. In the near future, an explicit flag will be added to control this behavior.
_Functional change_: Avoid single epoch compaction when writes are disallowed, that is when using read-only storage. Currently, the epoch manager will attempt to perform single epoch compactions, …
> refactor(general): move index cleanup out to refreshAttempt

- internal/epoch/epoch_manager.go
This is only a temporary mechanism for changing the default behavior.
Future PRs will:
- change default value
- remove index writes altogether from the write path
Followup to: #3603
Ref:
- #3638
- #3639
> refactor(general): allow disabling writes on index index loads

- internal/server/api_repo.go
- internal/server/grpc_session.go
- internal/server/server.go
- repo/api_server_repository.go
- repo/content/content_manager.go
- repo/content/content_manager_test.go
- repo/content/content_reader.go
- repo/format/content_format.go
- repo/format/format_manager.go
- repo/format/format_provider.go
- repo/grpc_repository_client.go
- repo/object/object_manager.go
- repo/object/object_manager_test.go
- repo/object/object_writer.go
also reduce global server lock scope
This API call is frequently invoked by KopiaUI. This should improve #2226 and #2453  by never blocking in the critical API call.
> fix(server): do not make blocking calls inside server status API

- internal/pproflogging/pproflogging.go
This is a continuation of https://github.com/kopia/kopia/pull/3454
This is one of 8 PRs in a PR train:
`aaron-kasten/kopia:pprof-extensions-c-1a`
`aaron-kasten/kopia:pprof-extensions-c-1b`
`aaron-kasten/kopia:pprof-extensions-c-1c`
`aaron-kasten/kopia:pprof-extensions-c-1d`
`aaron-kasten/kopia:pprof-extensions-c-1e`
`aaron-kasten/kopia:pprof-extensions-c-1f`
`aaron-kasten/kopia:pprof-extensions-c-1g`
Usage
=====
pprof dumps are configured using the `KOPIA_DEBUG_PPROF` environment variable.  The variable is a list of pprof profile names (see `pprof.Lookup`) separated by `,`.  Optional parameters can be set with '=', delimited by ':'.
example:
`export KOPIA_DEBUG_PPROF=cpu,heap=debug=1,mutex=debug=1:rate=1000`
The above setting will produce CPU, heap and mutex profiles.  The block profile …
> feat(cli): 1A: PPROF extensions: rename env var

- go.mod
- go.sum
This change upgrades to google.golang.org/protobuf@v1.33.0 to mitigate a security vulnerability.
> Version v1.33.0 of the google.golang.org/protobuf module fixes a bug in the google.golang.org/protobuf/encoding/protojson package which could cause the Unmarshal function to enter an infinite loop when handling some invalid inputs. This condition could only occur when unmarshaling into a message which contains a google.protobuf.Any value, or when the UnmarshalOptions.UnmarshalUnknown option is set. Unmarshal now correctly returns an error when handling these inputs.
This is CVE-2024-24786.
— https://groups.google.com/g/golang-announce/c/ArQ6CDgtEjY
> fix(deps): upgrade google.golang.org/protobuf to v1.33.0

- internal/epoch/epoch_manager.go
- internal/epoch/epoch_manager_test.go
Adds `epoch.Manager.MaybeAdvanceEpoch helper` and tests.
The helper is not yet invoked in maintenance, a separate change
will add all the epoch management cleanup tasks to maintenance.
Ref:
- #3638
- #3645
- #3651
> refactor(general): add epoch.Manager.MaybeAdvanceEpoch helper

- internal/server/api_content.go
The Content Get handler of the API server currently only returns `content not found` error responses. Other errors are swallowed and returned as successful, along with a `nil` data payload.
Fix by handling other errors as internal errors instead, equivalent to the behavior of e.g. `handleContentInfo`.
> fix(server): Return internal server errors for Content Get errors

- cli/command_server_start.go
- tests/end_to_end_test/acl_test.go
- tests/end_to_end_test/api_server_repository_test.go
Disable legacy API by default in the `kopia server start` command. The `--legacy-api` flag can be provided to start the server with the API enabled.
#3716
> chore(server): Disable legacy API by default

- internal/apiclient/apiclient.go
- internal/server/api_snapshots_test.go
Proposal to include the payload being returned by the API server in the case of an error in the error message logged to STDERR. If the error message payload is present in the response body, include it in the error message. Otherwise the error message will remain unchanged.
Simulated `"some error"` being thrown in a query to `/api/v1/contents/{contentID}`, resulting in an internal server error response:
Before:
After:
> fix(cli): Output error msg returned by API server payload when possible

- internal/crypto/pbkdf.go
- internal/crypto/scrypt.go
This PR updates the minimum salt size for the key derivers to 16. 
This may not be the recommended size for a key derivation algorithm however the current cache keys require this.
There will be follow up work for the cache keys to conform to the minimum length equal to the sha (32).
> fix(general): Update minimum salt size of key derivers to 16

- internal/epoch/epoch_utils.go
- internal/epoch/epoch_utils_test.go
Refactoring for the original implementation with `intRange` and `getKeyRange` from _closed-open_ ranges `[lo, hi)` to closed ranges: `[lo, hi]`. The primary motivation is for consistency with the implementation of `epoch.RangeMetadata` in the same package, and thus  avoid confusion and reduce cognitive load.
Changes:
- adds a `getContiguousKeyRange` wrapper that checks for contiguity.
- `getKeyRange` simply returns a range with minimum and maximum values for the keys in the map.
- changes the range implementation from _closed-open_ ranges `[lo, hi)` to closed ranges: `[lo, hi]` where both lo and hi are included in the range. Additional unit tests are included.
- renames `intRange` to `closedIntRange` to reflect new functionality.
Ref:
- Follow up #3721
- Needed for #3728
- #3638
> refactor(general): closedIntRange

- internal/epoch/epoch_manager.go
- internal/epoch/epoch_manager_test.go
- internal/epoch/epoch_utils.go
- internal/epoch/epoch_utils_test.go
Subset and dependency of #3651
Depends on #3735
Ref:
- #3638
- #3639
> refactor(general): add epoch.Manager.MaybeCompactSingleEpoch

- repo/manifest/committed_manifest_manager.go
Clobbering the error loses information and makes debugging more difficult
> fix(repository): Wrap manifest compaction error instead of clobbering it

- internal/epoch/epoch_manager.go
- internal/epoch/epoch_manager_test.go
Ref:
- Subset and dependency of #3651
- #3638
- #3639
> refactor(general): add epoch.Manager.MaybeGenerateRangeCheckpoint

- go.mod
- go.sum
Compare: https://github.com/kopia/htmlui/compare/44ad26dabec430b9a1d1cad30aef2b984f55e515...HEAD
* Oct 23 2023 https://github.com/kopia/htmlui/commit/98d4a1b dependabot[bot] build(deps-dev): bump @babel/traverse from 7.18.5 to 7.23.2
* Nov 3 2023 https://github.com/kopia/htmlui/commit/6412ee7 dependabot[bot] build(deps): bump react-select from 5.7.4 to 5.7.7
* Nov 7 2023 https://github.com/kopia/htmlui/commit/9aa9839 dependabot[bot] build(deps-dev): bump @testing-library/jest-dom from 6.1.3 to 6.1.4
* Nov 9 2023 https://github.com/kopia/htmlui/commit/59fdf8e Christoph Anderson Removed obsolet dependencies
* Nov 11 2023 https://github.com/kopia/htmlui/commit/1fd4dd2 dependabot[bot] build(deps-dev): bump axios from 1.4.0 to 1.6.0
* Nov 12 2023 https://github.com/kopia/htmlui/commit/644d9af …
> feat(ui): upgraded htmlui to the latest version

- cli/command_restore.go
- tests/end_to_end_test/restore_test.go
Fixes  #2945
The tryToConvertToPath would return an error when given an ID with an I prefix. Call object.parseID instead of index.parseID Also set the default for snapshot-time as that was missing. In my testing this seems to fix the issue
> fix(cli): restore objects with I prefix fails

- repo/maintenance/maintenance_run.go
Perform index epoch compaction and cleanup during repository maintenance.
Ref:
- #3638
- #3639
Followup to:
- #3603
- #3645
Related helpers and changes:
- #3721
- #3735
> refactor(general): perform index compaction during repo maintenance

- internal/epoch/epoch_manager.go
- internal/epoch/epoch_manager_test.go
Change default `allowWritesOnIndexLoad` to false when the corresponding environment variable is unset.
Add unit test to ensure epoch is not advanced on index loads by default
Followup to #3645
Ref:
- #3638
- #3639
> fix(general): disable writes on index loads

- go.mod
- internal/providervalidation/providervalidation.go
- repo/content/index/merged.go
- repo/refcount_closer.go
- snapshot/snapshotfs/upload.go
Since go1.20, standard errors package provides [Join function](https://pkg.go.dev/errors#Join) that can replace `go.uber.org/multierr`.
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
> refactor(deps): migrate from `go.uber.org/multierr` to standard `errors`

- cli/command_user_add_set.go
- internal/auth/authn_repo.go
- internal/auth/authn_repo_test.go
- internal/crypto/key_derivation_nontest.go
- internal/crypto/key_derivation_testing.go
- internal/crypto/pbkdf.go
- internal/crypto/scrypt.go
- internal/user/user_profile.go
- internal/user/user_profile_hash_v1.go
- internal/user/user_profile_test.go
This PR allows users to set the key derivation algorithm in a profile. 
The previous control `user-password-hash-version` was in place to handle any variations, however it has only ever supported 1 version and is not quite accurate. It has been replace with `key-derivation-algorithm`.
There is support to handle older profiles that have the PasswordHashVersion set. It will default to using the `Scrypt` key derivation algorithm as it had in the past.
An example where a profile is created with the old changes and one that is created with these new ones-
```
./kopianew2 server user list --json
[
{"username":"tes2@test","passwordHashVersion":1,"passwordHash":"CE/3mjeFF6PnFYfXw7H6Lxq6MWG0TKLzKZ1C2cH5YIQSnVtL9gP8KpHmlK88BiA0qhXKUwOvPHgiumCDQUFmTw=="}, …
```
> feat(general): User_profile_add_set cli changes

- repo/content/committed_content_index_disk_cache.go
> refactor(general): avoid wrapping known-to-be-nil error

- internal/crypto/pbkdf.go
Use `pbkdf2-sha256-600000` as the name to be consistent with the scrypt instantiation.
The format is `pbkdf2-<hash_type>-<number_of_iterations>`
> refactor(general):  include parameters in pbkdf2 instantiation

- cli/command_user_add_set.go
This PR updates the `user-password-hashing-algorithm` option to be hidden and note that it is an experimental setting.
> fix(cli): user add set user-password-hashing-algorithm cli option

- repo/grpc_repository_client.go
Connecting to gRPC repository API using an IPv6 address does not correctly configure the URI for the client's dial. Reconstructing the parsed URL into `hostname + ":" + port` will remove the square brackets required for IPv6 addressing, resulting in a `too many colons in address` error.
Fix the issue by instead using the helper `net.JoinHostPort()`, which will add square brackets for IPv6 hostnames.
Tested by running `TestServer` with `httptest.serve` flag set, forcing the test server to listen on the IPv6 loopback:
```
cd internal/server
go test -v -run=TestServer$ --httptest.serve=[::1]:0 ./server
```
Fails without fix:
```
server_test.go:48: 
Error Trace:    /workspaces/kopia/internal/server/server_test.go:48
Error:          Received unexpected error:
failed to exit idle mode: invalid …
```
> fix(cli): Fix client IPv6 URI generation for gRPC connections

- internal/crypto/key_derivation.go
- internal/crypto/key_derivation_test.go
- internal/repotesting/repotesting.go
- repo/format/format_manager.go
- repo/repository_test.go
Previously, empty master keys were passed to the underlying cryptographic primitives (HKDF, AEAD, etc.).
While this worked because the authentication mechanisms returned an error, it's best to avoid passing empty master keys to these primitives in the first place. This refactor avoids passing empty master keys and enforces this via an assertion in the key derivation function.
> refactor(general): avoid using empty master keys

- internal/crypto/pb_key_deriver_pbkdf2.go
Changing the minimum salt length of Pbkdf2 key derivation algorithm to the NIST recommended minimum of 16 bytes.
> fix(general): change pbkdf2 min salt length to 16 bytes

- site/content/docs/Repository Server/_index.md
Add context to why `--insecure` cannot be used behind a reverse proxy.
I am using kopia behind traefik as a reverse proxy. With the current wording, I thought that the lack of --insecure was required by the nginx (config) and not kopia itself. [This thread](https://kopia.discourse.group/t/cant-connect-to-insecure-repository-server/871/4) finally helped me to resolve the connection issues to the repo server.
> docs(server): explain why --insecure cannot be used behind a reverse proxy

- site/content/docs/Repositories/_index.md
This expands the note about using B2 storage as S3-compatible storage by providing some additional context on where to get the endpoint value.
I've also changed the redundant fully qualified "Backblaze B2" to "B2" in the note.
> docs(providers): info about the B2 S3-compatible endpoint

- site/content/docs/Repository Server/_index.md
When starting the server, the typical use case will not involve responding to interactive prompts. This change better reflects the expectations of a user given that fact.
> docs(server): add repo password in server start example

- internal/user/password_hashings_test.go
- internal/user/user_profile_pw_hash.go
Motivation: avoid making accidental decisions based on all-zeros content in the future.
While the dummyHash is a non-zero-value slice, that is it is non-empty (thus not nil), it is still the default value produced by `make([]byte, hashLength)`, and it is possible to accidentally compare and have a positive match against a newly initialized slice.
> refactor(server): initialize dummy hash with non-zero value

- internal/auth/authn_repo.go
- internal/user/user_profile.go
- internal/user/user_profile_pw_hash.go
- internal/user/user_profile_test.go
Rationale: this code path is primarily executed from the server. A potential error, say from a corrupt, unsupported or otherwise invalid user profile should not cause the server to panic (and crash).
It is possible for `computePasswordHash` to return an error, not just an impossibility.
> fix(general): avoid panic on computing password hash error

- go.mod
Addresses govulncheck flagged vulnerability
> chore(ci): update Go toolchain to 1.22.5

- .github/dependabot.yml
In the past, otel dependencies have introduced non-trivial depencency conflicts.
> chore(deps): group observability dependencies

- cli/command_server_start.go
- tests/end_to_end_test/server_start_test.go
Ensure repository disconnection at the end of the `server start` CLI command.
This was caught as a result of fixing the test below.
Fix `TestServerStartInsecure`:
Remove `--password=xxx` parameter, which causes a server start failure due to incorrect repo password, and not for the case being checked, which is the lack of the `--insecure` parameter.
Update test comments accordingly.
> fix(server): ensure repo disconnection on `server start` exit

- cli/command_user.go
- cli/command_user_add_set.go
- cli/command_user_hash_password.go
- cli/command_user_hash_password_test.go
- internal/user/hash_password.go
- internal/user/hash_password_test.go
- internal/user/password_hashing_version.go
- internal/user/password_hashings.go
- internal/user/password_hashings_test.go
- internal/user/user_manager.go
- internal/user/user_manager_test.go
- internal/user/user_profile.go
- internal/user/user_profile_pw_hash.go
- internal/user/user_profile_test.go
Objectives:
- Facilitate the generation of valid password hashes that can be used with the `server user --user-password` CLI command.
- Encapsulate implementation details of password hashing in the `user` package.
Adds a new `server user hash-password` CLI command to generate the hash from a supplied password.
Modifies the `server user set/add --user-password-hash` CLI command to accept the password hash generated using the `hash-password` command.
Adds `GetNewProfile(ctx, rep, username)` helper to move implementation details to the `user` package.
Includes CLI and unit tests.
Cleans up and removes unused functions.
> feat(cli): add server user set-password-hash command

- tests/robustness/multiclient_test/multiclient_test.go
This PR fixes a failure introduced in https://github.com/kopia/kopia/pull/3963
The function `tryDeleteAction` should allow the delete-random-snapID action. 
Local run was successful.
> test(general): allow delete random snapshot action

- Makefile
Looks like GHA switched to ARM64 runners on macOS.
> chore(ci): re-enable KopiaUI build on macOS

- Makefile
`TestIndexBlobManagerStress` is flaky and its failures produce
extremely large output that slowdown the GH UI, and are ultimately
truncated.
Adding a special-case (Make target) to ignore the output for these tests.
> chore(ci): silence `TestIndexBlobManagerStress` output on failure

- Makefile
Reverts kopia/kopia#4028
It's causing issues in CI
> Revert "chore(ci): silence `TestIndexBlobManagerStress` output on failure"

- cli/json_output.go
- internal/gather/gather_bytes_test.go
- internal/repodiag/log_manager_test.go
- repo/blob/s3/s3_versioned_test.go
- repo/content/content_manager.go
- repo/content/content_manager_lock_free.go
- repo/ecc/ecc_rs_crc.go
- repo/ecc/ecc_utils.go
- snapshot/snapshotfs/upload_test.go
- tests/recovery/recovery_test/recovery_test.go
- tests/robustness/multiclient_test/framework/client.go
Cleanups:
- use non-format variants of `Log`/`Print` with no additional args;
- fold in `Fprintf` call with no args into the following one;
- add missing arg placeholder in format strings;
- use `require.Positive` instead of `Greater(..., 0)`;
- rename function to `fillWithZeros` to avoid collision with builtin `clear`;
- define type for context key to avoid collisions;
See individual commits.
> refactor(general): minor miscellaneous cleanups

- cli/command_benchmark_compression.go
- cli/command_benchmark_crypto.go
- cli/command_benchmark_ecc.go
- cli/command_benchmark_encryption.go
- cli/command_benchmark_hashing.go
- cli/command_benchmark_splitters.go
- cli/command_blob_stats.go
- cli/command_content_stats.go
- cli/command_policy_show.go
- cli/command_repository_set_parameters.go
- cli/command_repository_status.go
- cli/show_utils.go
- internal/units/units.go
- tests/tools/kopiaclient/kopiaclient.go
Generalize a couple of functions in the `units` package using generics.
This allows removing duplicate code and simplifying callers by removing unnecessary integer conversions.
Additional cleanups:
- make `"/s"` part of the `Printf` format string ;
- simplify `setSizeMBParameter`;
- generalize `cli.maybeHumanReadable*` helpers;
- remove unneeded receiver in `commandRepositorySetParameters` helpers.
Reviewing it commit-wise should simplify the review process.
> refactor(general): generalize `units` package

- repo/manifest/serialized_test.go
Create a basic test that requires all manifest fields to be populated and then checks if deserialization works as expected. This is meant to help ensure tests stay updated across changes since there's currently custom code to deserialize manifests.
> test(repository): Ensure all manifest fields are populated during select tests

- internal/repodiag/internal_logger.go
- internal/repodiag/log_manager.go
- internal/repodiag/log_write_syncer.go
- repo/content/content_manager.go
This name reflects:
- the function of the struct; and
- the interface it implements (`zapcore.WriteSyncer`)
Also: clarify comments.
> refactor(general): rename `repodiag.logWriteSyncer`

- cli/command_snapshot_verify.go
- cli/command_snapshot_verify_test.go
Snapshot verify can now accept a list of one or more snapshot IDs (manifest IDs) to be used as the subject(s) of the snapshot verify operation.
Added a unit test that ensures only the requested snapshots are verified when their IDs are provided.
Now in addition to the existing `--source`, `--file-id`, and `--directory-id` flags, which work the same, the user can provide snapshot IDs as args:
```
kopia snapshot verify <snapID> <snapID> <snapID>
```
> feat(cli): Allow snapshot ID arguments for command snapshot verify

- cli/storage_gcs.go
- repo/blob/gcs/gcs_immu_test.go
- repo/blob/gcs/gcs_options.go
- repo/blob/gcs/gcs_pit.go
- repo/blob/gcs/gcs_storage.go
- repo/blob/gcs/gcs_storage_test.go
- repo/blob/gcs/gcs_versioned.go
- repo/blob/gcs/gcs_versioned_test.go
It seems not possible to create a PR train in this repo. I created 1 PR but the base only shows me master or providers. So instead it's broken down by commits. 
Put/Extend commit: Adds `ExtendBlobRetention` and removes the `ErrUnsupportedPutBlobOption` check from `PutBlob`. Also some slight refactorings to make it more like `azure_storage.go` and tweak to support getting a blob by its versionID. 
PITR commit: Code is largely identical to `azure_` and `s3_` equivalents. Based on @kreare's #3564 but more complete.
Tests commit:
`gcs_immu_test.go` and `gcs_versioned_test.go` are basically identical to `azure_` equivalents. Only `createBucket` is a bit different based on Google client. Tweaked `gcs_storage_test.go` slightly to make it more like the az/s3 ones with consts for env vars
Requires …
> feat(providers): GCS immutability

- repo/blob/s3/s3_storage.go
The s3 storage provider had a different http transports for different cases:
- HTTPS without TLS verification: `&http.Transport{}` with default values;
- HTTPS with TLS verification: `http.DefaultTransport.Clone()`
This change uses `http.DefaultTransport` in all cases, instead of creating an empty (zero-value) `http.Transport` for consistency.
Author: @alexvbg
> refactor(providers): always clone default HTTP transport in S3 provider

- repo/blob/gcs/gcs_immu_test.go
- repo/blob/gcs/gcs_storage_test.go
- repo/blob/gcs/gcs_versioned_test.go
The GCS provider tests broke in #4134
This is an attempt to fix the tests by using the credentials that are available in the providers validation job. Note that a credentials file is not available.
However, the tests still fail because:
- there isn't a versioned / immutable bucket for the tests; and
- the credentials available in the test do not allow creating buckets.
The GCS versioning / immutability tests are skipped in the mean time until the required bucket is created.
> fix(providers): GCS tests

- repo/blob/gcs/gcs_immu_test.go
- repo/blob/gcs/gcs_storage_test.go
- repo/blob/gcs/gcs_versioned_test.go
- Use `getEnvVarOrSkip()` helper
- Use creds from JSON env for test to actually run the test. A file with creds is not available in the testing environment.
- nit: relocate helpers
> test(providers): cleanup GCS tests

- repo/manifest/committed_manifest_manager.go
- repo/manifest/manifest_manager.go
- repo/manifest/manifest_manager_test.go
Mostly aimed at reducing memory allocations during manifest compaction by not modifying the passed in set of items being persisted. Previously this set had persisted entries removed from it, which necessitated cloning the set of committed manifests during compaction. Assuming the number of manifests in the committed set is much larger than the number of dirty entries persisted during calls to `Flush()` this saves copying a map of pointers
Also makes a minor update to how committed contents are tracked since only the value `true` was stored in the map
Consolidated benchmark results with and without these changes where `XItems` represents the total number of manifest entries (benchmark included in PR for reference)
```
go test -v -run X -timeout 120m -bench . -benchmem -benchtime 100x …
```
> refactor(repository): Reduce memory allocations during manifest compaction

- cli/command_server.go
- cli/command_server_start.go
- tests/end_to_end_test/server_start_test.go
Use shorter key size to speed up cert generation in `TestServerStartInsecure`.
Refactor: add const for default server-control username.
> test(server): speedup cert key generation in server tests

- cli/command_server_start.go
- cli/command_server_tls.go
Checks whether any of the `httpServer.Serve*()` calls returns `ErrServerClosed`.
Hhandles `ErrServerClosed` inside the `startServerWithOptionalTLS` function instead of propagating it up.  This means that `startServerWithOptionalTLS` returns a nil error when the HTTP server is closed, so the caller does not need to check for `ErrServerClosed`
No functional changes otherwise.
> refactor(server): handle `ErrServerClosed` where it occurs

- site/content/docs/Advanced/Ransomware Protection/_index.md
Remove no longer relevant Google section + clarify that `set --extend-object-locks` also needs setting for Azure/Google
Google section:
> docs(site): Clarify ransomware requirements for Google/Azure

- repo/maintenance/maintenance_schedule_test.go
Allows to check for marshaling errors, although those are not expected.
Trivial otherwise.
> refactor(general): make toJSON a test helper

- repo/blob/gcs/gcs_storage.go
Extending a blob requires full control. On the newer client styles (e.g. `option.WithCredentialsJSON(j)`), this is the default if no scope is specified. 
Before:
```
gcs_immu_test.go:90:
Error Trace:	/Users/admin/repo/kopia/repo/blob/gcs/gcs_immu_test.go:90
Error:      	Received unexpected error:
googleapi: Error 403: Access denied., forbidden
unable to extend retention period to 2024-10-01 20:02:11 +0000 UTC
```
After:
```
PASS
ok  	github.com/kopia/kopia/repo/blob/gcs	3.176s
```
> fix(repository): allow extending blob retentions

- cli/command_benchmark_hashing.go
Fixes: #4181
```
kopia benchmark hashing --repeat=20
Benchmarking hash 'BLAKE2B-256' (20 x 1048576 bytes, parallelism 1)
Benchmarking hash 'BLAKE2B-256-128' (20 x 1048576 bytes, parallelism 1)
Benchmarking hash 'BLAKE2S-128' (20 x 1048576 bytes, parallelism 1)
Benchmarking hash 'BLAKE2S-256' (20 x 1048576 bytes, parallelism 1)
Benchmarking hash 'BLAKE3-256' (20 x 1048576 bytes, parallelism 1)
Benchmarking hash 'BLAKE3-256-128' (20 x 1048576 bytes, parallelism 1)
Benchmarking hash 'HMAC-SHA224' (20 x 1048576 bytes, parallelism 1)
Benchmarking hash 'HMAC-SHA256' (20 x 1048576 bytes, parallelism 1)
Benchmarking hash 'HMAC-SHA256-128' (20 x 1048576 bytes, parallelism 1)
Benchmarking hash 'HMAC-SHA3-224' (20 x 1048576 bytes, parallelism 1)
Benchmarking hash 'HMAC-SHA3-256' (20 x 1048576 bytes, …
```
> fix(cli): hashing benchmark repeat

- tests/testenv/cli_test_env.go
Facilitates troubleshooting test failures.
Sample output:
```
Error Trace:	kopia/tests/testenv/cli_test_env.go:257        	            				  
kopia/cli/command_logs_test.go:100
Error:      	"[20241025124935_bb69 2024-10-25 12:49:35 PDT 0s 1.1 KB 1 20241025124935_36e0 2024-10-25 12:49:35 PDT 0s 1 KB 1 20241025124935_0532 2024-10-25 12:49:35 PDT 0s 1.6 KB 1 20241025124935_03b8 2024-10-25 12:49:35 PDT 0s 1.1 KB 1 20241025124935_61e8 2024-10-25 12:49:35 PDT 0s 1.1 KB 1]" should have 1 item(s), but has 5
Test:       	TestLogsMaintenance
Messages:   	unexpected output lines for 'kopia logs list', lines:
20241025124935_bb69 2024-10-25 12:49:35 PDT 0s 1.1 KB 1
20241025124935_36e0 2024-10-25 12:49:35 PDT 0s 1 KB 1
20241025124935_0532 2024-10-25 12:49:35 PDT 0s 1.6 KB 1
20241025124935_03b8 …
```
> test(cli): prefer require in cli_test_env

- README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Kopia Guru](https://gurubase.io/g/kopia) to Gurubase. Kopia Guru uses the data from this repo and data from the [docs](https://kopia.io/docs/) to answer questions by leveraging the LLM.
In this PR, I showcased the "Kopia Guru", which highlights that Kopia now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to disable …
> docs(site): Introducing Kopia Guru on Gurubase.io

- cli/command_benchmark_crypto.go
- cli/command_benchmark_encryption.go
Reuse the output buffer by resetting it between iterations.
- Fixes: #4210
> fix(cli): avoid memory bloat in `benchmark encryption` command

- internal/server/server.go
A minimal commit to add support for monitoring, troubleshooting, and to allow using tools like crowdsec or fail2ban. This to ease the comfort a bit on opening up access to a kopia server over internet.
When/if change is merged or a similar is created I can create instructions and templates for using said tools to protect a kopia server instance running om Linux.
> feat(server): add logging of failed and successful login attempts

- cli/command_snapshot_create.go
- notification/notifydata/multi_snapshot_status.go
- notification/notifytemplate/embeddedtemplate.go
- notification/notifytemplate/notifytemplate_test.go
- notification/notifytemplate/snapshot-report.html
- notification/notifytemplate/snapshot-report.txt
- notification/notifytemplate/testdata/snapshot-report.html.alt.expected
- notification/notifytemplate/testdata/snapshot-report.html.default.expected
- notification/notifytemplate/testdata/snapshot-report.txt.alt.expected
- notification/notifytemplate/testdata/snapshot-report.txt.default.expected
* round durations to 0.1 seconds
* added delta indicators for size/files/dirs
> feat(cli): improved snapshot reports

- Makefile
- cli/command_repository_connect_server.go
- internal/servertesting/servertesting.go
- repo/api_server_repository.go
- repo/open.go
- repo/repository_test.go
- tests/compat_test/compat_test.go
- tests/end_to_end_test/api_server_repository_test.go
- tools/gettool/checksums.txt
- tools/tools.mk
This was caused by the client using key derivation algorithm from a config file (which did not have it when it was generated using old version of Kopia).
Fixes #4254
> fix(cli): fixed v0.18.0 failures when using v0.17.0-generated client config

- .chglog/config.yml
- .github/workflows/check-pr-title.yml
- notification/sender/email/email_sender.go
- notification/sender/email/email_sender_test.go
This fixes sending emails via SendGrid as reported by a user on Slack. The fix has been tested already.
> fix(notifications): fixed headers for email notifications

- internal/server/server.go
> feat(server): only log successful authentication events when --log-server-requests is enabled

- cli/command_benchmark_compression.go
make sure MB-or-GB is not separated from /s in table. %-12v will put spaces on the right of the number, then print /s after the spaces.
> feat(cli): improve compression benchmark output

- internal/blobtesting/map.go
- internal/repodiag/log_manager.go
- internal/repodiag/log_manager_test.go
- tests/end_to_end_test/server_repo_logs_test.go
The kopia server was not uploading any logs to the repository, because _"repodiag"_ blob uploads would always fail.
The cause was the following: When the (log) repodiag blob PUT operation was initiated, the `Context` used for this operation was already canceled.
The context used for blob uploads is passed to `repodiag.NewLogManager` when opening the repository. In the case of the kopia server, the repository is asynchronously opened in `server.Server.InitReposotoryAsync`. The context passed to `repo.Open` is canceled after the "open repository" server task completes. This issue was introduced in #1691
Change:
Use `context.WithoutCancel()` instead of the context passed when the repo "diagnoser" is created.
New tests are included to reproduce this failure and verify the fix.
Ref:
- #1691 …
> fix(server): ensure server uploads "repodiag" blobs

- .github/workflows/make.yml
Bumps [docker/setup-qemu-action](https://github.com/docker/setup-qemu-action).
Updates `docker/setup-qemu-action` from 3.2.0 to 3.3.0
- [Release notes](https://github.com/docker/setup-qemu-action/releases)
- [Commits](https://github.com/docker/setup-qemu-action/compare/49b3bc8e6bdd4a60e6116a5414239cba5943d3cf...53851d14592bedcffcf25ea515637cff71ef929a)
---
- dependency-name: docker/setup-qemu-action
- dependency-type: direct:production
- update-type: version-update:semver-minor
- dependency-group: docker ...
> build(deps): bump docker/setup-qemu-action

- .github/workflows/code-coverage.yml
- .github/workflows/compat-test.yml
- .github/workflows/endurance-test.yml
- .github/workflows/htmlui-tests.yml
- .github/workflows/license-check.yml
- .github/workflows/lint.yml
- .github/workflows/make.yml
- .github/workflows/ossf-scorecard.yml
- .github/workflows/providers-core.yml
- .github/workflows/providers-extra.yml
- .github/workflows/race-detector.yml
- .github/workflows/stale.yml
- .github/workflows/stress-test.yml
- .github/workflows/tests.yml
- .github/workflows/volume-shadow-copy-test.yml
Updates:
Bumps the github-actions group with 4 updates in the / directory: [actions/setup-go](https://github.com/actions/setup-go), [actions/upload-artifact](https://github.com/actions/upload-artifact), [github/codeql-action](https://github.com/github/codeql-action) and [actions/stale](https://github.com/actions/stale).
Updates `actions/setup-go` from 5.2.0 to 5.3.0
- [Release notes](https://github.com/actions/setup-go/releases)
- [Commits](https://github.com/actions/setup-go/compare/v5.2.0...f111f3307d8850f501ac008e886eec1fd1932a34)
Updates `actions/upload-artifact` from 4.5.0 to 4.6.0
- [Release notes](https://github.com/actions/upload-artifact/releases)
- [Commits](https://github.com/actions/upload-artifact/compare/v4.5.0...65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08)
Updates …
> build(deps): bump the github-actions group

- go.mod
- go.sum
Updates the common-golang-dependencies group with 1 update: [google.golang.org/grpc](https://github.com/grpc/grpc-go).
Updates `google.golang.org/grpc` from 1.69.4 to 1.70.0
- [Release notes](https://github.com/grpc/grpc-go/releases)
- [Commits](https://github.com/grpc/grpc-go/compare/v1.69.4...v1.70.0)
---
- dependency-name: google.golang.org/grpc
- dependency-type: direct:production
- update-type: version-update:semver-minor
- dependency-group: common-golang-dependencies
> build(deps): bump google.golang.org/grpc

- go.mod
This addresses a govuln reported issue present [crypto/internal/nistec](https://pkg.go.dev/crypto/internal/nistec) on `ppc64le`
> build(deps): update Go's toolchain to 1.23.6

- internal/repotesting/repotesting.go
- internal/server/server.go
- internal/server/server_maintenance.go
- internal/server/server_maintenance_test.go
- snapshot/snapshotmaintenance/snapshotmaintenance.go
- snapshot/snapshotmaintenance/snapshotmaintenance_test.go
Avoid starting a maintenance task on the server when the repository connection (configuration) is read-only.
- Fixes: #4373
> fix(server): prevent maintenance task on read-only repos

- fs/entry.go
- fs/ignorefs/ignorefs.go
- fs/ignorefs/resolve_test.go
- fs/localfs/local_fs.go
Other cleanups:
- simplify error messages
- remove spurious error wrapping
Ref:
- #2037
- #4190
> fix(general): prevent infinite loop while resolving ignore file symlinks

- snapshot/snapshotfs/dir_manifest_builder.go
- snapshot/snapshotfs/dir_manifest_builder_test.go
- snapshot/snapshotfs/upload_test.go
Fix propagation of symlink counts to parent directories. Add tests to check the directory summary has correct counts for symlinks and files.
Before the fix, symlink counts would not be passed to parent directories, resulting in summary data that do not reflect the count of symlinks in the directory tree.
> fix(snapshots): fix accounting for symlinks in directory summary

- go.mod
- go.sum
Addresses CVE-2025-22870 and Go issue https://go.dev/issue/71984
> build(deps): upgrade Go toolchain to 1.23.7 and x/net packages

- snapshot/snapshotgc/gc.go
> fix(general): use correct error in call to `errors.Wrap`

- cli/password.go
- internal/passwordpersist/passwordpersist_keyring.go
Extends error message with a generic, OS-independent hint about what the source of the error may be and a potential solution.
Also, modifies error message to avoid duplicate messages.
- #4449
> chore(cli): add details to persistent password error message

- go.mod
- addresses CVE-2025-22871
- https://go.dev/issue/71988
- https://github.com/kopia/kopia/security/advisories/GHSA-63xm-hhjf-fwvg
- https://github.com/golang/vulndb/issues/3563
> build(deps): use Go 1.23.8 toolchain

- internal/diff/diff.go
- remove spurious log message, duplicates what is being sent to the output;
- nit: update struct comment;
- consolidate code via a parameterized function;
- rename variable for clarity, it makes it easier to understand by avoiding negative condition check;
- remove unused return value;
- replace if blocks with switch.
> refactor(cli): misc cleanups in internal/diff

- repo/buildinfo.go
- repo/buildinfo_test.go
- repo/initialize.go
Sets `repo.BuildInfo` and `repo.BuildVersion` when they are not specified via link flags.
The behavior for binaries built via CI and Make remains the same.
> build(cli): set build info version and info when not set

- internal/tempfile/tempfile_linux.go
- internal/tempfile/tempfile_test.go
- Add `TestCreateSucceedsWhenDirIsNotSpecified`
- Use `os.TempDir` when `dir` is not specified (empty string)
Ref:
- Fixes #4331
- Fixes #2415
> fix(general): `tempfile.Create` on Linux (x64/arm64)

- tools/tools.mk
This is only used in unofficial regular builds and not in tagged releases.
> chore(ci): UTC commit date

- cli/command_notification_configure_common.go
- internal/acl/acl_manager.go
- internal/cache/content_cache_test.go
- internal/metrics/prom_cache.go
- internal/pproflogging/pproflogging_test.go
- internal/user/user_manager.go
- notification/notifytemplate/repotemplate.go
- notification/sender/notification_message.go
- repo/content/index/id.go
- repo/grpc_repository_client.go
- repo/open.go
- repo/repository.go
- tests/robustness/multiclient_test/multiclient_test.go
- tests/robustness/robustness_test/robustness_test.go
- tests/socketactivation_test/socketactivation_test.go
- use `uint8` for clarity
- unexport `writeContentAsyncAndVerify`
- fix typo in test function names
- remove commented interface functions
- use `atomic.Int32`
- cleanups in socket server activation test
- leverage stdlib's `maps` and `slices` packages
- leverage `maps.Values`
> chore(general): minor cleanups and other nits

- internal/bigmap/bigmap_internal.go
- internal/tempfile/tempfile.go
- internal/tempfile/tempfile_linux.go
- internal/tempfile/tempfile_linux_fallback_test.go
- internal/tempfile/tempfile_test.go
- internal/tempfile/tempfile_unix_fallback.go
- internal/tempfile/tempfile_unix_nonlinux.go
- internal/tempfile/tempfile_verify_test.go
- internal/tempfile/tempfile_windows.go
- tests/os_snapshot_test/os_snapshot_windows_test.go
Use `os.CreateTemp` when creating temporary files in `tempfile.createUnixFallback` function
> refactor(general): leverage `os.CreateTemp`

- fs/localfs/local_fs_test.go
- tests/robustness/snapmeta/index_test.go
- tests/robustness/snapmeta/kopia_persister_light_test.go
- tests/robustness/snapmeta/simple_test.go
Cleanup robustness tests and `local_fs_test.go`
- Use `require` helpers
- Use `testing.T` helpers
"Mechanical" changes.
Note change in functionality: The use of `require` helpers stops tests once a check fails. Before, various checks were using `t.Error`, which fails the test but allows the test to continue its execution.
> refactor(general): cleanup a few tests

- tools/cli2md/cli2md.go
- tools/cli2md/cli2md_test.go
In the generated markdown docs, flags like `--foo` inside help texts currently get pretty-printed as `–foo` with an em-dash.
This PR applies backticks via a regex replacement (run by `cli2md`), so that they appear as `--foo` in the docs but remain as --foo (without backticks) in the CLI output.
See also #4341
> fix(site): escape flags with backticks

- cli/storage_azure.go
- repo/blob/azure/azure_options.go
- repo/blob/azure/azure_storage.go
- repo/blob/azure/azure_storage_test.go
Allow the use of a client certificate when authenticating to an Azure Blob storage provider.
Tests included.
Credit: @DeepikaDixit
> feat(providers): client certificate authentication for Azure Blob

- .golangci.yml
- internal/epoch/epoch_manager_test.go
- internal/testutil/testutil.go
- use 'localmodule' for gci linter config
- enable `wastedassign` linter and fix linter issues
- disable `zerologlint` linter
- block dependencies
> style(general): cleanup linter config

- .golangci.yml
Update `forbidigo` linter config to remove patterns for deprecated `ioutil` functions and symbols.
The usage of deprecated symbols already flagged by the other linters, in particular `staticcheck` (SA1019 rule)
> style(general): cleanup `forbidigo` linter config

- repo/blob/rclone/rclone_options.go
- repo/blob/rclone/rclone_storage.go
This allows persistingand reading back the timeout as a duration.
~~The name reflects the unit used for the timeout.~~
There are be no backwards compatibility issues, since the field is
not currently set, so it is not persisted in the configuration file.
> refactor(providers): change rclone's `StartupTimeout` type to Duration

- cli/command_diff.go
- internal/diff/diff.go
- internal/diff/diff_test.go
- tests/end_to_end_test/restore_test.go
- tests/recovery/recovery_test/recovery_test.go
Added the `--stats-only` flag to the  kopia-diff command to reduce output verbosity. When kopia diff is invoked with the `--stats-only` flag it only outputs the aggregate statistics of changes.
> feat(cli): Added a stats-only flag to the kopia diff command

- go.mod
- https://go.dev/doc/devel/release#go1.23.minor
- https://github.com/golang/go/issues?q=milestone%3AGo1.23.8+label%3ACherryPickApproved
> chore(ci): upgrade Go toolchain to 1.23.9

- internal/diff/diff.go
- internal/diff/diff_test.go
- snapshot/snapshotfs/objref.go
Added helper functions to find preceding snapshots.
Part of the planned enhancements for the `diff` command.
Added the helper methods to fetch preceding snapshots. These helpers will be consumed to enhance the CLI for the existing `diff` command implementation.
- Method to fetch the immediately preceding snapshot manifest given a snapshot ID
- Method to fetch the two latest snapshot manifests for a given source
Also added relevant unit tests for the above methods:
- In order to test `GetPrecedingSnapshot`, first the method is invoked with a wrong `snapshotID` and an error is expected. Next a snapshot is saved and the method is invoked again, since there is only a single snapshot in the repo, an error is expected. Subsequently more snapshots are saved and the method is invoked and the …
> feat(cli): helper functions to get preceding snapshots for `diff`

- tests/end_to_end_test/norace_test.go
- tests/end_to_end_test/snapshot_create_test.go
Avoid allocating 1GB of RAM to write a test file.
Exclude test from race detector.
- Fixes #4610
- #4439
> test(general): fix `TestSnapshotNoLeftoverCheckpoints` slowness

- snapshot/upload/upload_test.go
- use testify's `require/assert` in upload test
- refactor `TestUploadMetadataCompression` as a table test
- allow tests to run in parallel
- use `t.Cleanup` and adds a missing cleanup
- use `maps.Clone`
> refactor(general): upload tests

- internal/testutil/tmpdir.go
While sorting by modification time is possible with OS tools, such as `ls`, including the directory creation time in the name facilitates cleanup in local dev environments where tests fail often.
> chore(ci): include date-time in temp dir name used for tests

- go.mod
Addresses reported security vulnerabilities in Go's standard library.
> chore(ci): upgrade Go toolchain to 1.23.10

- internal/crypto/aesgcm.go
- internal/crypto/key_derivation.go
- internal/crypto/key_derivation_test.go
- internal/crypto/pb_key_deriver_pbkdf2.go
- repo/format/upgrade_lock_test.go
- repo/hashing/sha_hashes.go
- repo/maintenance/maintenance_schedule.go
- repo/open.go
- repo/repository.go
- repo/repository_test.go
Functional changes:
- Key derivation no longer panics, instead it returns an error on failed condition checks.
- Migration to `crypto/hkdf` required changes in various function signatures, adding an error return value for propagating key derivation errors up the calling chain. Tests were refactored to account for the signature change as well.
Non-functional changes:
- Added a key derivation helper to reduce function complexity.
> refactor(general): migrate to `crypto/{hkdf,pbkdf2,sha3}`

- cli/command_snapshot_fix_invalid_files.go
- cli/command_snapshot_verify.go
- cli/command_snapshot_verify_test.go
- snapshot/snapshotfs/snapshot_verifier.go
- snapshot/snapshotfs/snapshot_verifier_test.go
- Add read stats to snapshot verifier output.
- Add periodic JSON progress output.
- Refactor the use of directory summary.
- Use stats mutex for all stats.
- Add processedBytes to the snapshot verify output.
- Output more frequently, when bytes processed changes.
- Change depends on #4644; full diff includes both changes until that PR merges. Please see commit c59be0fe615cda71dab9e0bbb53bcf9f94b47467 for changes introduced by this PR.
> feat(snapshots): Add periodic JSON progress output to snapshot verify

- cli/command_ls.go
Adds a `-h`/`--human-readable` option to `kopia ls` to print sizes in human-readable format.
- Closes #4501
> feat(cli): human-readable sizes for kopia ls

- repo/content/sessions.go
- repo/content/sessions_test.go
Check for clock skew between the local clock and the storage clock when the session blob is written (on session creation). Tests included.
The check is currently disabled by default.
> feat(general): check for clock skew on write session creation

- cli/command_restore.go
- snapshot/restore/restore.go
- tests/end_to_end_test/restore_test.go
The PR performs following:
- Add `delete-extra` flag to `kopia snaphot restore` command, false by default.
- During restore, if this flag is enabled, it would delete any new file or directory that already exists in the filesystem and that does not match from the snapshot list.
Test plan:
- Ran tests by generating multiple data sets and confirmed any new file, directory that was not in snapshot was getting deleted with the change.
> feat(cli): added support for deleting extra files in restore path

- fs/localfs/local_fs.go
- fs/localfs/local_fs_os.go
This is a fix for #3842.
It's a slightly modified version of the patch in https://github.com/kopia/kopia/issues/3842#issuecomment-2105616219, I separated the code out into a `maybe` function and added some tests. 
The root cause of this issue seems to be a regression in Go 1.22 (see https://github.com/kopia/kopia/issues/3842#issuecomment-2141250166), but as discussed with jkowalski in the issue, it seems better to just fix this up with a special case in Kopia.
> fix(snapshots): Append path separator to Shadow Copy root directory on Windows

- site/content/docs/Installation/_index.md
Kopia is available via winget. They seem to track new releases automatically.
`winget` comes preinstalled on Windows 11 since 21H2.
> docs(site): Add Windows winget installation

- cli/app.go
- cli/config.go
- cli/observability_flags.go
- tests/end_to_end_test/index_recover_test.go
Removes:
- `--caching`: no-op
- `--list-caching`: no-op
- `--enable-jaeger-collector`: errors out when specified.
> refactor(cli): remove deprecated no-op flags

- cli/command_content_verify.go
- cli/command_index_inspect.go
- repo/blob/storage.go
- repo/content/content_manager_iterate.go
- repo/content/content_manager_test.go
- repo/content/index/index_builder.go
- repo/maintenance/blob_gc.go
- repo/maintenance/maintenance_run.go
- snapshot/manifest.go
Nits and cleanups:
- clarify log message to indicate the effect of advancing the deletion watermark;
- add `omitzero` JSON tag to appropriate fields in `snapshot.Manifest` struct;
- use `maps.Clone` instead of explicit loop;
- rename function to `IterateUnreferencedPacks` for clarity;
- use `atomic.Int32` type;
- move a `continue` check to the beginning of the loop, no actual work / side effects were performed before the check;
- reduce type requirement in `blob.ReadBlobMap`
> refactor(general): miscellaneous cleanups

- repo/blob/azure/azure_options.go
- repo/blob/azure/azure_storage.go
- repo/blob/azure/azure_storage_test.go
- repo/blob/storage.go
- Adds `kopia` as the application ID.
- Adds a unit test verifying that the header sent to Azure contains the application ID in the user agent string.
- Adds an option to use an insecure connection to Azure, primarily for testing.
Authored by: @andrason
> feat(providers): add user-agent string in Azure storage provider

- cli/command_content_verify.go
- repo/content/content_reader.go
- repo/content/verify.go
- repo/content/verify_test.go
Move general functionality from the `content verify` CLI command implementation to helpers in the `content` package.
The primary motivation is to allow reusing the content verification functionality during maintenance. In a separate change request.
A separate followup change also extends content verification to include additional stats useful for debugging repository corruptions.
Overview of the changes:
- Relocation of the content verification functionality to the `content` package. The entry point is `content.WriteManager.VerifyContents`. This is primarily code movement with no functional changes.
- Addition of unit tests for the content verification functionality by exercising `content.WriteManager.VerifyContents`.
- Minor functional change: changing the logging level from Error to …
> refactor(general): move `content verify` functionality to the `content` package

- repo/initialize.go
Code cleanup.
This variable is no longer used.
> refactor(cli): remove overriding repository format via env variable

- internal/stats/count_map.go
- internal/stats/count_map_test.go
- repo/content/verify.go
Track and report errors separately according to the type of error:
- missing pack
- truncated pack
- unreadable content.
Add a counter stat for the contents that are read and fully verified (via `GetContent`).
Count errors grouped by pack ID using a `CountersMap`. This allows determining the number of referenced contents that were missing in a particular pack.
Report the counter stats via structured logging.
Sample output
```
$ kopia content verify --progress-interval=0.5s --download-percent=100
Listing blobs...
Listed 102 blobs.
Verifying contents...
Verified 1 contents, 0 errors, estimating...
Verified 279 contents, 0 errors, estimating...
Verified 512 of 624 contents (82.1%), 0 errors, remaining 0s, ETA 2025-09-17 23:03:38 PDT
Finished verifying contents
verifyCounters: …
```
> feat(cli): extend stats for content verification

- go.mod
- go.sum
Bumps the common-golang-dependencies group with 1 update in the / directory: [github.com/Azure/azure-sdk-for-go/sdk/azidentity](https://github.com/Azure/azure-sdk-for-go).
Updates `github.com/Azure/azure-sdk-for-go/sdk/azidentity` from 1.11.0 to 1.12.0
- [Release notes](https://github.com/Azure/azure-sdk-for-go/releases)
- [Changelog](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/sdk-breaking-changes-guide-migration.md)
- [Commits](https://github.com/Azure/azure-sdk-for-go/compare/sdk/azcore/v1.11.0...sdk/azcore/v1.12.0)
---
- dependency-name: github.com/Azure/azure-sdk-for-go/sdk/azidentity dependency-version: 1.12.0 dependency-type: direct:production update-type: version-update:semver-minor dependency-group: common-golang-dependencies ...
> build(deps): bump github.com/Azure/azure-sdk-for-go/sdk/azidentity

- tests/endurance_test/endurance_test.go
Prevent running "auto-maintenance" on snapshot create.
Ref:
- #4851
Context: the test fails because there are concurrent "endurance" runners and each of these advances the clock, some of them significantly (`action{Small,Medium,Large}ClockJump`), which causes the clock skewness check to fail when (auto-)maintenance runs. The test maintenance action does not run into this issue because it runs exclusively on its own, that is, other actions have to wait until maintenance completes.
> test(general): fix endurance test failures

- .github/workflows/endurance-test.yml
Run endurance tests:
- on push to the `test/endurance` branch
- on workflow dispatch, it allows choosing the target branch for the run.
> test(general): expand triggers for endurance tests
